EntertainmentInfothek: EntertainmentDB.Data.Status Class Reference
EntertainmentDB.Data.Status Class Reference
Provides a status.
Public Member Functions
Status (DBReader reader)
Initializes a status with an empty id string.
Status (DBReader reader, string id)
Initializes a status with the given id string.
virtual int Retrieve (bool retrieveBasicInfoOnly)
Retrieves the information of the status from the database.
Protected Member Functions
virtual int RetrieveBasicInformation (bool retrieveBasicInfoOnly)
Retrieves the basic information of the status from the database.
virtual int RetrieveAdditionalInformation ()
Retrieves the additional information of the status from the database (none available).
Properties
DBReader Reader [getprotected set]
The database reader to be used to read the status information from the database.
string ID [getset]
The id of the status.
string EnglishTitle [getset]
The english title of the status.
string GermanTitle [getset]
The german title of the status.
string Details [getset]
The details of the status.
string StatusString [getset]
The status string of the status.
string LastUpdated [getset]
The date of last update of the status.
Static Private Attributes
static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides a status.
Constructor & Destructor Documentation
Status() [1/2]
EntertainmentDB.Data.Status.Status (DBReader reader)
Initializes a status with an empty id string.
Parameters
reader The database reader to be used to read the status information from the database.
Status() [2/2]
EntertainmentDB.Data.Status.Status (DBReader reader, string id)
Initializes a status with the given id string.
Parameters
reader The database reader to be used to read the status information from the database.
id The id of the status.
Exceptions
ArgumentNullException Thrown when the given id is null.
Member Function Documentation
Retrieve()
virtual int EntertainmentDB.Data.Status.Retrieve (bool retrieveBasicInfoOnly) virtual
Retrieves the information of the status from the database.
Parameters
retrieveBasicInfoOnly true if only the basic info is to be retrieved; false if also additional data is to be retrieved.
Returns
The number of data records retrieved.
Implements EntertainmentDB.DBAccess.Read.IDBReadable.
Referenced by EntertainmentDB.Data.AspectRatio.RetrieveBasicInformation(), EntertainmentDB.Data.AspectRatioItem.RetrieveBasicInformation(), EntertainmentDB.Data.Award.RetrieveBasicInformation(), EntertainmentDB.Data.AwardItem.RetrieveBasicInformation(), EntertainmentDB.Data.Camera.RetrieveBasicInformation(), EntertainmentDB.Data.CameraItem.RetrieveBasicInformation(), EntertainmentDB.Data.CastPersonItem.RetrieveBasicInformation(), EntertainmentDB.Data.Certification.RetrieveBasicInformation(), EntertainmentDB.Data.CertificationItem.RetrieveBasicInformation(), EntertainmentDB.Data.CinematographicProcess.RetrieveBasicInformation(), EntertainmentDB.Data.CinematographicProcessItem.RetrieveBasicInformation(), EntertainmentDB.Data.Color.RetrieveBasicInformation(), EntertainmentDB.Data.ColorItem.RetrieveBasicInformation(), EntertainmentDB.Data.Company.RetrieveBasicInformation(), EntertainmentDB.Data.CompanyItem.RetrieveBasicInformation(), EntertainmentDB.Data.Connection.RetrieveBasicInformation(), EntertainmentDB.Data.Country.RetrieveBasicInformation(), EntertainmentDB.Data.CountryItem.RetrieveBasicInformation(), EntertainmentDB.Data.DistributorCompanyItem.RetrieveBasicInformation(), EntertainmentDB.Data.Edition.RetrieveBasicInformation(), EntertainmentDB.Data.FilmFormat.RetrieveBasicInformation(), EntertainmentDB.Data.FilmLengthItem.RetrieveBasicInformation(), EntertainmentDB.Data.Genre.RetrieveBasicInformation(), EntertainmentDB.Data.GenreItem.RetrieveBasicInformation(), EntertainmentDB.Data.Image.RetrieveBasicInformation(), EntertainmentDB.Data.ImageItem.RetrieveBasicInformation(), EntertainmentDB.Data.Laboratory.RetrieveBasicInformation(), EntertainmentDB.Data.LaboratoryItem.RetrieveBasicInformation(), EntertainmentDB.Data.Language.RetrieveBasicInformation(), EntertainmentDB.Data.LanguageItem.RetrieveBasicInformation(), EntertainmentDB.Data.Location.RetrieveBasicInformation(), EntertainmentDB.Data.LocationItem.RetrieveBasicInformation(), EntertainmentDB.Data.Movie.RetrieveBasicInformation(), EntertainmentDB.Data.NegativeFormatItem.RetrieveBasicInformation(), EntertainmentDB.Data.Person.RetrieveBasicInformation(), EntertainmentDB.Data.PersonItem.RetrieveBasicInformation(), EntertainmentDB.Data.PrintedFilmFormatItem.RetrieveBasicInformation(), EntertainmentDB.Data.RuntimeItem.RetrieveBasicInformation(), EntertainmentDB.Data.Series.RetrieveBasicInformation(), EntertainmentDB.Data.SoundMix.RetrieveBasicInformation(), EntertainmentDB.Data.SoundMixItem.RetrieveBasicInformation(), EntertainmentDB.Data.Text.RetrieveBasicInformation(), EntertainmentDB.Data.TextItem.RetrieveBasicInformation(), EntertainmentDB.Data.TimespanItem.RetrieveBasicInformation(), EntertainmentDB.Data.Type.RetrieveBasicInformation(), EntertainmentDB.Data.Weblink.RetrieveBasicInformation(), and EntertainmentDB.Data.WeblinkItem.RetrieveBasicInformation().
RetrieveAdditionalInformation()
virtual int EntertainmentDB.Data.Status.RetrieveAdditionalInformation () protected virtual
Retrieves the additional information of the status from the database (none available).
Returns
0
Referenced by EntertainmentDB.Data.Status.Retrieve().
RetrieveBasicInformation()
virtual int EntertainmentDB.Data.Status.RetrieveBasicInformation (bool retrieveBasicInfoOnly) protected virtual
Retrieves the basic information of the status from the database.
Parameters
retrieveBasicInfoOnly true if only the basic info is to be retrieved; false if also additional data is to be retrieved.
Returns
1 if data record was retrieved; 0 if no data record matched the id.
Referenced by EntertainmentDB.Data.Status.Retrieve().
Member Data Documentation
Logger
readonly NLog.Logger EntertainmentDB.Data.Status.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by EntertainmentDB.Data.Status.Retrieve(), EntertainmentDB.Data.Status.RetrieveBasicInformation(), and EntertainmentDB.Data.Status.Status().
Property Documentation
Details
string EntertainmentDB.Data.Status.Details get set
The details of the status.
Referenced by EntertainmentDB.Data.Status.RetrieveBasicInformation().
EnglishTitle
string EntertainmentDB.Data.Status.EnglishTitle get set
The english title of the status.
Referenced by EntertainmentDB.Data.Status.RetrieveBasicInformation().
GermanTitle
string EntertainmentDB.Data.Status.GermanTitle get set
The german title of the status.
Referenced by EntertainmentDB.Data.Status.RetrieveBasicInformation().
ID
string EntertainmentDB.Data.Status.ID get set
The id of the status.
Referenced by EntertainmentDB.Data.AspectRatio.RetrieveBasicInformation(), EntertainmentDB.Data.AspectRatioItem.RetrieveBasicInformation(), EntertainmentDB.Data.Award.RetrieveBasicInformation(), EntertainmentDB.Data.AwardItem.RetrieveBasicInformation(), EntertainmentDB.Data.Camera.RetrieveBasicInformation(), EntertainmentDB.Data.CameraItem.RetrieveBasicInformation(), EntertainmentDB.Data.CastPersonItem.RetrieveBasicInformation(), EntertainmentDB.Data.Certification.RetrieveBasicInformation(), EntertainmentDB.Data.CertificationItem.RetrieveBasicInformation(), EntertainmentDB.Data.CinematographicProcess.RetrieveBasicInformation(), EntertainmentDB.Data.CinematographicProcessItem.RetrieveBasicInformation(), EntertainmentDB.Data.Color.RetrieveBasicInformation(), EntertainmentDB.Data.ColorItem.RetrieveBasicInformation(), EntertainmentDB.Data.Company.RetrieveBasicInformation(), EntertainmentDB.Data.CompanyItem.RetrieveBasicInformation(), EntertainmentDB.Data.Connection.RetrieveBasicInformation(), EntertainmentDB.Data.Country.RetrieveBasicInformation(), EntertainmentDB.Data.CountryItem.RetrieveBasicInformation(), EntertainmentDB.Data.DistributorCompanyItem.RetrieveBasicInformation(), EntertainmentDB.Data.Edition.RetrieveBasicInformation(), EntertainmentDB.Data.FilmFormat.RetrieveBasicInformation(), EntertainmentDB.Data.FilmLengthItem.RetrieveBasicInformation(), EntertainmentDB.Data.Genre.RetrieveBasicInformation(), EntertainmentDB.Data.GenreItem.RetrieveBasicInformation(), EntertainmentDB.Data.Image.RetrieveBasicInformation(), EntertainmentDB.Data.ImageItem.RetrieveBasicInformation(), EntertainmentDB.Data.Laboratory.RetrieveBasicInformation(), EntertainmentDB.Data.LaboratoryItem.RetrieveBasicInformation(), EntertainmentDB.Data.Language.RetrieveBasicInformation(), EntertainmentDB.Data.LanguageItem.RetrieveBasicInformation(), EntertainmentDB.Data.Location.RetrieveBasicInformation(), EntertainmentDB.Data.LocationItem.RetrieveBasicInformation(), EntertainmentDB.Data.Movie.RetrieveBasicInformation(), EntertainmentDB.Data.NegativeFormatItem.RetrieveBasicInformation(), EntertainmentDB.Data.Person.RetrieveBasicInformation(), EntertainmentDB.Data.PersonItem.RetrieveBasicInformation(), EntertainmentDB.Data.PrintedFilmFormatItem.RetrieveBasicInformation(), EntertainmentDB.Data.RuntimeItem.RetrieveBasicInformation(), EntertainmentDB.Data.Series.RetrieveBasicInformation(), EntertainmentDB.Data.SoundMix.RetrieveBasicInformation(), EntertainmentDB.Data.SoundMixItem.RetrieveBasicInformation(), EntertainmentDB.Data.Status.RetrieveBasicInformation(), EntertainmentDB.Data.Text.RetrieveBasicInformation(), EntertainmentDB.Data.TextItem.RetrieveBasicInformation(), EntertainmentDB.Data.TimespanItem.RetrieveBasicInformation(), EntertainmentDB.Data.Type.RetrieveBasicInformation(), EntertainmentDB.Data.Weblink.RetrieveBasicInformation(), EntertainmentDB.Data.WeblinkItem.RetrieveBasicInformation(), and EntertainmentDB.Data.Status.Status().
LastUpdated
string EntertainmentDB.Data.Status.LastUpdated get set
The date of last update of the status.
Referenced by EntertainmentDB.Data.Status.RetrieveBasicInformation().
Reader
DBReader EntertainmentDB.Data.Status.Reader get protected set
The database reader to be used to read the status information from the database.
Referenced by EntertainmentDB.Data.Status.RetrieveBasicInformation(), and EntertainmentDB.Data.Status.Status().
StatusString
string EntertainmentDB.Data.Status.StatusString get set
The status string of the status.
Referenced by EntertainmentDB.Data.Status.RetrieveBasicInformation().
The documentation for this class was generated from the following file:
EntertainmentInfothek_public/src/EntertainmentDB/Data/Status.cs