EntertainmentInfothek: WikiPageCreator.Export.Create.ArticleContentCreator Class Reference
WikiPageCreator.Export.Create.ArticleContentCreator Class Reference abstract
Provides a content creator for an article.
Public Member Functions
virtual string GetFileName (Entry entry, Formatter formatter)
Creates the file name of the article page (or not).
virtual string GetFileName (Article article, Formatter formatter)
Creates the file name of the article page.
virtual List< string > CreateFileContent (Entry entry, string targetLanguageCode, Formatter formatter)
Creates the file content of a given entry.
Protected Member Functions
ArticleContentCreator ()
Initializes a new ArticleContentCreator.
virtual List< string > CreateInfoBoxContent (Entry entry, string targetLanguageCode, Formatter formatter)
Creates the infobox content of a given entry.
abstract List< string > CreateChapterContent (Entry entry, string targetLanguageCode, Formatter formatter)
Creates the chapter content of a given entry.
virtual List< string > CreateFileHeader (Article article, string targetLanguageCode, Formatter formatter)
Creates the formatted header content of a given article.
virtual List< string > CreateFileFooter (Article article, string targetLanguageCode, Formatter formatter)
Creates the formatted footer content of a given article.
virtual List< string > CreateInfoBoxBegin (Article article, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox begin content of a given article.
virtual List< string > CreateInfoBoxEnd (Article article, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox end content of a given article
virtual List< string > CreateNewChapter (Dictionary< string, string > title, string targetLanguageCode, Formatter formatter)
Creates a formatted chapter heading with the given title.
virtual List< string > CreateNewSection (Dictionary< string, string > title, string targetLanguageCode, Formatter formatter)
Creates a formatted section heading with the given title.
virtual List< string > CreateFileTitle (Article article, string targetLanguageCode, Formatter formatter)
Creates the formatted file title content of a given article.
virtual List< string > CreateInfoBoxTitle (Article article, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox title content of a given article.
virtual List< string > CreateInfoBoxReleaseDate (Article article, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox release date content of a given article.
virtual List< string > CreateInfoboxType (Article article, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox type content of a given article.
virtual List< string > CreateChapterConnection (Article article, string targetLanguageCode, Formatter formatter)
Creates the formatted connection chapter content of a given article.
Static Private Attributes
static NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides a content creator for an article.
Constructor & Destructor Documentation
ArticleContentCreator()
WikiPageCreator.Export.Create.ArticleContentCreator.ArticleContentCreator () protected
Initializes a new ArticleContentCreator.
Member Function Documentation
CreateChapterConnection()
virtual List< string > WikiPageCreator.Export.Create.ArticleContentCreator.CreateChapterConnection (Article article, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted connection chapter content of a given article.
Parameters
article The article that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted conncetion chapter content of the article.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
CreateChapterContent()
abstract List< string > WikiPageCreator.Export.Create.ArticleContentCreator.CreateChapterContent (Entry entry, string targetLanguageCode, Formatter formatter) protected pure virtual
Creates the chapter content of a given entry.
Parameters
entry The entry that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted content of the entry.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Implemented in WikiPageCreator.Export.Create.MovieContentCreator, and WikiPageCreator.Export.Create.SeriesContentCreator.
Referenced by WikiPageCreator.Export.Create.ArticleContentCreator.CreateFileContent().
CreateFileContent()
virtual List< string > WikiPageCreator.Export.Create.ArticleContentCreator.CreateFileContent (Entry entry, string targetLanguageCode, Formatter formatter) virtual
Creates the file content of a given entry.
Parameters
entry The entry that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted content of the entry.
Implements WikiPageCreator.Export.Create.IFileContentCreatable.
Referenced by WikiPageCreator.Program.CreateMoviePage(), and WikiPageCreator.Program.CreateSeriesPage().
CreateFileFooter()
virtual List< string > WikiPageCreator.Export.Create.ArticleContentCreator.CreateFileFooter (Article article, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted footer content of a given article.
Parameters
article The article that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted footer content of the article.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.ArticleContentCreator.CreateFileContent().
CreateFileHeader()
virtual List< string > WikiPageCreator.Export.Create.ArticleContentCreator.CreateFileHeader (Article article, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted header content of a given article.
Parameters
article The article that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted haeder content of the article.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.ArticleContentCreator.CreateFileContent().
CreateFileTitle()
virtual List< string > WikiPageCreator.Export.Create.ArticleContentCreator.CreateFileTitle (Article article, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted file title content of a given article.
Parameters
article The article that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted file title content of the article.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.ArticleContentCreator.CreateFileContent().
CreateInfoBoxBegin()
virtual List< string > WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxBegin (Article article, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox begin content of a given article.
Parameters
article The article that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox begin content of the article.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.ArticleContentCreator.CreateFileContent().
CreateInfoBoxContent()
virtual List< string > WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxContent (Entry entry, string targetLanguageCode, Formatter formatter) protected virtual
Creates the infobox content of a given entry.
Parameters
entry The entry that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted content of the entry.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Reimplemented in WikiPageCreator.Export.Create.MovieContentCreator, and WikiPageCreator.Export.Create.SeriesContentCreator.
Referenced by WikiPageCreator.Export.Create.ArticleContentCreator.CreateFileContent(), and WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoboxType().
CreateInfoBoxEnd()
virtual List< string > WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxEnd (Article article, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox end content of a given article
Parameters
article The article that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox end content of the article.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.ArticleContentCreator.CreateFileContent().
CreateInfoBoxReleaseDate()
virtual List< string > WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxReleaseDate (Article article, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox release date content of a given article.
Parameters
article The article that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox release date content of the article.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent().
CreateInfoBoxTitle()
virtual List< string > WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxTitle (Article article, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox title content of a given article.
Parameters
article The article that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox title content of the article.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxContent().
CreateInfoboxType()
virtual List< string > WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoboxType (Article article, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox type content of a given article.
Parameters
article The article that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox type content of the article.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxContent().
CreateNewChapter()
virtual List< string > WikiPageCreator.Export.Create.ArticleContentCreator.CreateNewChapter (Dictionary< string, string > title, string targetLanguageCode, Formatter formatter) protected virtual
Creates a formatted chapter heading with the given title.
Parameters
title The title that is to be used as heading.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The fomatted chapter heading.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterConnection(), and WikiPageCreator.Export.Create.SeriesContentCreator.CreateChapterConnection().
CreateNewSection()
virtual List< string > WikiPageCreator.Export.Create.ArticleContentCreator.CreateNewSection (Dictionary< string, string > title, string targetLanguageCode, Formatter formatter) protected virtual
Creates a formatted section heading with the given title.
Parameters
title The title that is to be used as heading.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The fomatted chapter heading.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
GetFileName() [1/2]
virtual string WikiPageCreator.Export.Create.ArticleContentCreator.GetFileName (Article article, Formatter formatter) virtual
Creates the file name of the article page.
Parameters
article The article that is to be used to create the file name.
formatter The formatter that is to be used to format the file name.
Returns
The formatted file name.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
GetFileName() [2/2]
virtual string WikiPageCreator.Export.Create.ArticleContentCreator.GetFileName (Entry entry, Formatter formatter) virtual
Creates the file name of the article page (or not).
Parameters
entry The entry that is to be used to create the file name.
formatter The formatter that is to be used to format the file name.
Returns
The formatted file name.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Implements WikiPageCreator.Export.Create.IFileContentCreatable.
Referenced by WikiPageCreator.Program.CreateMoviePage(), WikiPageCreator.Program.CreateSeriesPage(), and WikiPageCreator.Export.Create.ArticleContentCreator.GetFileName().
Member Data Documentation
Logger
NLog.Logger WikiPageCreator.Export.Create.ArticleContentCreator.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by WikiPageCreator.Export.Create.ArticleContentCreator.ArticleContentCreator(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateChapterConnection(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateFileContent(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateFileFooter(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateFileHeader(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateFileTitle(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxBegin(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxContent(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxEnd(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxReleaseDate(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxTitle(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoboxType(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateNewChapter(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateNewSection(), and WikiPageCreator.Export.Create.ArticleContentCreator.GetFileName().
The documentation for this class was generated from the following file:
C:/Users/Sandra/Projekte/GitHub/EntertainmentInfothek_public/src/WikiPageCreator/Export/Create/ArticleContentCreator.cs