EntertainmentInfothek: WikiPageCreator.Export.Create.CountryContentCreator Class Reference
WikiPageCreator.Export.Create.CountryContentCreator Class Reference
Provides a content creator for a country.
Public Member Functions
CountryContentCreator (List< CountryItem > countries, Formatter formatter, string targetLanguageCode)
Initializes a new CountryContentCreator.
override List< string > CreateInfoBoxContent ()
Creates the infobox content of a given country.
Public Member Functions inherited from WikiPageCreator.Export.Create.EntryContentCreator
virtual string GetPageName ()
Returns the page name of the entrys page.
virtual List< string > CreatePageContent ()
Creates the page content of the entry.
virtual List< string > CreateInfoBoxContent ()
Creates the infobox content of a given entry.
virtual List< string > CreateChapterContent ()
Creates the chapter content of a given entry.
virtual List< string > CreateSectionContent ()
Creates the section content of a given entry.
Protected Member Functions
override List< string > CreateInfoBoxContentInternal ()
Creates the infobox content of a given list of countries.
Protected Member Functions inherited from WikiPageCreator.Export.Create.EntryContentCreator
EntryContentCreator (Entry entry, Formatter formatter, string targetLanguageCode)
Initializes an EntryContentCreator with the given entry, formatter and target language code.
virtual List< string > CreatePageContentInternal ()
Creates the page content of the entry.
virtual List< string > CreatePageHeader ()
Creates the formatted header content of a given entry.
virtual List< string > CreatePageTitle ()
Creates the formatted file title content of a given entry.
virtual List< string > CreateInfoBoxBegin ()
Creates the formatted infobox begin content of a given entry
virtual List< string > CreateInfoBoxContentInternal ()
Creates the infobox content of a given entry.
void CreateInfoBoxContentHelper (List< string > content, string title, string[] path, string pagename, string text, string additionalInfo)
Creates the specific row of the infobox content.
void CreateInfoBoxContentHelper (List< string > content, string title, string[] path, string pagename, Image image, int size, string additionalInfo)
Creates the specific row of the infobox content.
void CreateInfoBoxContentHelper (List< string > content, string title, int runtime, string[] path, string pagename, string text, string additionalInfo)
Creates the specific row of the infobox content.
virtual List< string > CreateInfoBoxEnd ()
Creates the formatted infobox end content of a given entry
virtual List< string > CreateNewChapter (Dictionary< string, string > title)
Creates a formatted chapter heading with the given title.
virtual List< string > CreateChapterContentInternal ()
Creates the chapter content of a given entry.
virtual List< string > CreateNewSection (Dictionary< string, string > title)
Creates a formatted section heading with the given title.
virtual List< string > CreateSectionContentInternal ()
Creates the section content of a given entry.
virtual List< string > CreatePageFooter ()
Creates the formatted footer content of a given entry.
Properties
List< CountryItem > Countries [get, set]
The list of country items to be used to create the content.
Properties inherited from WikiPageCreator.Export.Create.EntryContentCreator
Formatter Formatter [get, protected set]
The formatter to be used to format the information of the entry.
Entry Entry [get, protected set]
The entry to be used to create the content.
string TargetLanguageCode [get, protected set]
The target language (as a language code) to specify the language of the created content.
Static Private Attributes
static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides a content creator for a country.
Constructor & Destructor Documentation
CountryContentCreator()
WikiPageCreator.Export.Create.CountryContentCreator.CountryContentCreator (List< CountryItem > countries, Formatter formatter, string targetLanguageCode)
Initializes a new CountryContentCreator.
Parameters
countries The list of country items to be used to create content.
formatter The formatter to be used to format the content.
targetLanguageCode The language code for the created content.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Member Function Documentation
CreateInfoBoxContent()
override List< string > WikiPageCreator.Export.Create.CountryContentCreator.CreateInfoBoxContent () virtual
Creates the infobox content of a given country.
Returns
The formatted content of the country.
Reimplemented from WikiPageCreator.Export.Create.EntryContentCreator.
Referenced by WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator.CreateInfoBoxCountry().
CreateInfoBoxContentInternal()
override List< string > WikiPageCreator.Export.Create.CountryContentCreator.CreateInfoBoxContentInternal () protected virtual
Creates the infobox content of a given list of countries.
Returns
The formatted content of the list of countries.
Reimplemented from WikiPageCreator.Export.Create.EntryContentCreator.
Referenced by WikiPageCreator.Export.Create.CountryContentCreator.CreateInfoBoxContent().
Member Data Documentation
Logger
readonly NLog.Logger WikiPageCreator.Export.Create.CountryContentCreator.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by WikiPageCreator.Export.Create.CountryContentCreator.CountryContentCreator(), and WikiPageCreator.Export.Create.CountryContentCreator.CreateInfoBoxContentInternal().
Property Documentation
Countries
List<CountryItem> WikiPageCreator.Export.Create.CountryContentCreator.Countries get set
The list of country items to be used to create the content.
Referenced by WikiPageCreator.Export.Create.CountryContentCreator.CountryContentCreator(), and WikiPageCreator.Export.Create.CountryContentCreator.CreateInfoBoxContentInternal().
The documentation for this class was generated from the following file:
EntertainmentInfothek/src/WikiPageCreator/Export/Create/CountryContentCreator.cs