EntertainmentInfothek: EntertainmentDB.Data.Series Class Reference
EntertainmentDB.Data.Series Class Reference
Provides a series.
Public Member Functions
Series (DBReader reader)
Initializes a series with an empty id string.
Series (DBReader reader, string id)
Initializes a series with the given id string.
Public Member Functions inherited from EntertainmentDB.Data.Entry
virtual int Retrieve (bool retrieveBasicInfoOnly)
Retrieves the information of the entry from the database.
int Retrieve (bool retrieveBasicInfoOnly)
Retrieves the information from the database.
Static Public Member Functions
static List< Series > RetrieveList (DBReader reader, string status, string order="ID")
Retrieves a list of series from the database.
Protected Member Functions
override int RetrieveBasicInformation (bool retrieveBasicInfoOnly)
Retrieves the basic information of the series from the database.
override int RetrieveAdditionalInformation ()
Retrieves the additional information of the series from the database.
Protected Member Functions inherited from EntertainmentDB.Data.MovieAndTVArticle
MovieAndTVArticle (DBReader reader)
Initializes a movie and tv article with an empty id string.
MovieAndTVArticle (DBReader reader, string id)
Initializes a movie and tv article with the given id string.
Protected Member Functions inherited from EntertainmentDB.Data.Article
Article (DBReader reader)
Initializes an article with an empty id string.
Article (DBReader reader, string id)
Initializes an article with the given id string.
Protected Member Functions inherited from EntertainmentDB.Data.Entry
Entry (DBReader reader)
Initializes an entry with the given reader and id string.
Entry (DBReader reader, string id)
Initializes an entry with the given reader and id string.
abstract int RetrieveBasicInformation (bool retrieveBasicInfoOnly)
Retrieves the basic information of the entry from the database.
virtual int RetrieveAdditionalInformation ()
Retrieves the additional information of the entry from the database.
Properties
string ReleaseDateFirstEpisode [get, set]
The release date of the first episode (or pilot) of the series.
string ReleaseDateLastEpisode [get, set]
The release date of the last episode of the series.
string NoOfSeasons [get, set]
The number of seasons of the series.
string NoOfEpisodes [get, set]
The number of episodes of the series.
Properties inherited from EntertainmentDB.Data.MovieAndTVArticle
string Budget [get, set]
The budget of the movie and tv article.
string WorldwideGross [get, set]
The worldwide gross of the movie and tv article.
string WorldwideGrossDate [get, set]
The corresponding date to the worldwide gross of the movie and tv article.
List< CountryItem > Countries [get, set]
The list of countries of the movie and tv article.
List< LanguageItem > Languages [get, set]
The list of languages of the movie and tv article.
List< SoundMixItem > SoundMixes [get, set]
The list of sound mixes of the movie and tv article.
Status CastStatus [get, set]
The cast status of the movie and tv article.
Status CrewStatus [get, set]
The crew status of the movie ant tv article.
Properties inherited from EntertainmentDB.Data.Article
string OriginalTitle [get, set]
The original title of the article.
string EnglishTitle [get, set]
The english title of the article.
string GermanTitle [get, set]
The german title of the article.
Type Type [get, set]
The type of the article.
string ReleaseDate [get, set]
The release date of the article.
List< GenreItem > Genres [get, set]
The list of genres of the article.
List< CertificationItem > Certifications [get, set]
The list of certifications of the article.
Connection Connection [get, set]
The connection of the article.
Properties inherited from EntertainmentDB.Data.Entry
DBReader Reader [get, protected set]
The database reader to be used to read the entry information from the database.
string ID [get, set]
The id of the entry.
string Details [get, set]
The details of the entry.
Status Status [get, set]
The status of the entry.
string LastUpdated [get, set]
The date of last update of the entry.
Static Private Attributes
static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides a series.
Constructor & Destructor Documentation
Series() [1/2]
EntertainmentDB.Data.Series.Series (DBReader reader)
Initializes a series with an empty id string.
Parameters
reader The database reader to be used to read the series information from the database.
Series() [2/2]
EntertainmentDB.Data.Series.Series (DBReader reader, string id)
Initializes a series with the given id string.
Parameters
reader The database reader to be used to read the series information from the database.
id The id of the series.
Exceptions
ArgumentNullException Thrown when the given id is null.
Member Function Documentation
RetrieveAdditionalInformation()
override int EntertainmentDB.Data.Series.RetrieveAdditionalInformation () protected virtual
Retrieves the additional information of the series from the database.
Returns
The number of data records retrieved.
Reimplemented from EntertainmentDB.Data.Entry.
RetrieveBasicInformation()
override int EntertainmentDB.Data.Series.RetrieveBasicInformation (bool retrieveBasicInfoOnly) protected virtual
Retrieves the basic information of the series from the database.
Parameters
retrieveBasicInfoOnly true if only the basic info is to be retrieved; false if also additional data is to be retrieved.
Returns
1 if data record was retrieved; 0 if no data record matched the id.
Implements EntertainmentDB.Data.Entry.
RetrieveList()
static List< Series > EntertainmentDB.Data.Series.RetrieveList (DBReader reader, string status, string order = "ID") static
Retrieves a list of series from the database.
Parameters
reader The reader to be used to retrieve the data records.
status The status of the series.
order The order in which the data records are to be sorted.
Returns
The list of series.
Exceptions
ArgumentNullException Thrown when the given status or order is null.
Referenced by WikiPageCreator.Program.Main().
Member Data Documentation
Logger
readonly NLog.Logger EntertainmentDB.Data.Series.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by EntertainmentDB.Data.Series.RetrieveAdditionalInformation(), EntertainmentDB.Data.Series.RetrieveBasicInformation(), EntertainmentDB.Data.Series.RetrieveList(), and EntertainmentDB.Data.Series.Series().
Property Documentation
NoOfEpisodes
string EntertainmentDB.Data.Series.NoOfEpisodes get set
The number of episodes of the series.
Referenced by WikiPageCreator.Export.Create.SeriesContentCreator.CreateInfoBoxNoOfEpisodes(), and EntertainmentDB.Data.Series.RetrieveBasicInformation().
NoOfSeasons
string EntertainmentDB.Data.Series.NoOfSeasons get set
The number of seasons of the series.
Referenced by WikiPageCreator.Export.Create.SeriesContentCreator.CreateInfoBoxNoOfSeasons(), and EntertainmentDB.Data.Series.RetrieveBasicInformation().
ReleaseDateFirstEpisode
string EntertainmentDB.Data.Series.ReleaseDateFirstEpisode get set
The release date of the first episode (or pilot) of the series.
Referenced by WikiPageCreator.Export.Create.SeriesContentCreator.CreateInfoBoxReleaseDateFirstEpisode(), and EntertainmentDB.Data.Series.RetrieveBasicInformation().
ReleaseDateLastEpisode
string EntertainmentDB.Data.Series.ReleaseDateLastEpisode get set
The release date of the last episode of the series.
Referenced by WikiPageCreator.Export.Create.SeriesContentCreator.CreateInfoBoxReleaseDateLastEpisode(), and EntertainmentDB.Data.Series.RetrieveBasicInformation().
The documentation for this class was generated from the following file:
EntertainmentInfothek/src/EntertainmentDB/Data/Series.cs