EntertainmentInfothek: WikiPageCreator.Program Class Reference
WikiPageCreator.Program Class Reference
Static Private Member Functions
static void Main (string[] args)
static void CreateMoviePage (string id, string targetLanguageCode, string outputFolder)
Creates a movie page with the specified parameters.
static void CreateSeriesPage (string id, string targetLanguageCode, string outputFolder)
Creates a series page with the specified parameters.
Static Private Attributes
static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Member Function Documentation
CreateMoviePage()
static void WikiPageCreator.Program.CreateMoviePage (string id, string targetLanguageCode, string outputFolder) static private
Creates a movie page with the specified parameters.
Parameters
id The id of the movie.
targetLanguageCode The target language for the page.
outputFolder The output folder for the page.
Referenced by WikiPageCreator.Program.Main().
CreateSeriesPage()
static void WikiPageCreator.Program.CreateSeriesPage (string id, string targetLanguageCode, string outputFolder) static private
Creates a series page with the specified parameters.
Parameters
id The id of the series.
targetLanguageCode The target language for the page.
outputFolder The output folder for the page.
Referenced by WikiPageCreator.Program.Main().
Main()
static void WikiPageCreator.Program.Main (string[] args) static private
Member Data Documentation
Logger
readonly NLog.Logger WikiPageCreator.Program.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by WikiPageCreator.Program.CreateMoviePage(), WikiPageCreator.Program.CreateSeriesPage(), and WikiPageCreator.Program.Main().
The documentation for this class was generated from the following file:
EntertainmentInfothek/src/WikiPageCreator/Program.cs