EntertainmentInfothek: EntertainmentDB.DBAccess.Read.DBReader Class Reference
EntertainmentDB.DBAccess.Read.DBReader Class Reference abstract
Provides a database reader.
Public Member Functions
abstract DBReader New ()
Creates a new DBReader of the same class as the current DBReader.
abstract int Retrieve (bool retrieveBasicInfoOnly)
Retrieves the information from the database.
Protected Member Functions
DBReader ()
Initializes a database reader.
Properties
string Query = "" [getset]
The query of the database reader.
DataTable Table = new DataTable() [getprotected set]
The data table of the database reader.
Static Private Attributes
static NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides a database reader.
Constructor & Destructor Documentation
DBReader()
EntertainmentDB.DBAccess.Read.DBReader.DBReader () protected
Initializes a database reader.
Member Function Documentation
New()
abstract DBReader EntertainmentDB.DBAccess.Read.DBReader.New () pure virtual
Creates a new DBReader of the same class as the current DBReader.
Returns
A new DBReader which the same class as the current DBReader.
Implemented in EntertainmentDB.DBAccess.Read.SQLiteReader.
Referenced by EntertainmentDB.Data.AspectRatio.RetrieveBasicInformation(), EntertainmentDB.Data.AspectRatioItem.RetrieveBasicInformation(), EntertainmentDB.Data.Award.RetrieveBasicInformation(), EntertainmentDB.Data.AwardItem.RetrieveBasicInformation(), EntertainmentDB.Data.Camera.RetrieveBasicInformation(), EntertainmentDB.Data.CameraItem.RetrieveBasicInformation(), EntertainmentDB.Data.CastPersonItem.RetrieveBasicInformation(), EntertainmentDB.Data.Certification.RetrieveBasicInformation(), EntertainmentDB.Data.CertificationItem.RetrieveBasicInformation(), EntertainmentDB.Data.CinematographicProcess.RetrieveBasicInformation(), EntertainmentDB.Data.CinematographicProcessItem.RetrieveBasicInformation(), EntertainmentDB.Data.Color.RetrieveBasicInformation(), EntertainmentDB.Data.ColorItem.RetrieveBasicInformation(), EntertainmentDB.Data.Company.RetrieveBasicInformation(), EntertainmentDB.Data.CompanyItem.RetrieveBasicInformation(), EntertainmentDB.Data.Connection.RetrieveBasicInformation(), EntertainmentDB.Data.Country.RetrieveBasicInformation(), EntertainmentDB.Data.CountryItem.RetrieveBasicInformation(), EntertainmentDB.Data.DistributorCompanyItem.RetrieveBasicInformation(), EntertainmentDB.Data.Edition.RetrieveBasicInformation(), EntertainmentDB.Data.FilmFormat.RetrieveBasicInformation(), EntertainmentDB.Data.FilmLengthItem.RetrieveBasicInformation(), EntertainmentDB.Data.Genre.RetrieveBasicInformation(), EntertainmentDB.Data.GenreItem.RetrieveBasicInformation(), EntertainmentDB.Data.Image.RetrieveBasicInformation(), EntertainmentDB.Data.ImageItem.RetrieveBasicInformation(), EntertainmentDB.Data.Laboratory.RetrieveBasicInformation(), EntertainmentDB.Data.LaboratoryItem.RetrieveBasicInformation(), EntertainmentDB.Data.Language.RetrieveBasicInformation(), EntertainmentDB.Data.LanguageItem.RetrieveBasicInformation(), EntertainmentDB.Data.Location.RetrieveBasicInformation(), EntertainmentDB.Data.LocationItem.RetrieveBasicInformation(), EntertainmentDB.Data.Movie.RetrieveBasicInformation(), EntertainmentDB.Data.NegativeFormatItem.RetrieveBasicInformation(), EntertainmentDB.Data.Person.RetrieveBasicInformation(), EntertainmentDB.Data.PersonItem.RetrieveBasicInformation(), EntertainmentDB.Data.PrintedFilmFormatItem.RetrieveBasicInformation(), EntertainmentDB.Data.RuntimeItem.RetrieveBasicInformation(), EntertainmentDB.Data.Series.RetrieveBasicInformation(), EntertainmentDB.Data.SoundMix.RetrieveBasicInformation(), EntertainmentDB.Data.SoundMixItem.RetrieveBasicInformation(), EntertainmentDB.Data.Text.RetrieveBasicInformation(), EntertainmentDB.Data.TextItem.RetrieveBasicInformation(), EntertainmentDB.Data.TimespanItem.RetrieveBasicInformation(), EntertainmentDB.Data.Type.RetrieveBasicInformation(), EntertainmentDB.Data.Weblink.RetrieveBasicInformation(), EntertainmentDB.Data.WeblinkItem.RetrieveBasicInformation(), EntertainmentDB.Data.AspectRatioItem.RetrieveList(), EntertainmentDB.Data.AwardItem.RetrieveList(), EntertainmentDB.Data.CameraItem.RetrieveList(), EntertainmentDB.Data.CastPersonItem.RetrieveList(), EntertainmentDB.Data.CertificationItem.RetrieveList(), EntertainmentDB.Data.CinematographicProcessItem.RetrieveList(), EntertainmentDB.Data.ColorItem.RetrieveList(), EntertainmentDB.Data.CompanyItem.RetrieveList(), EntertainmentDB.Data.CountryItem.RetrieveList(), EntertainmentDB.Data.DistributorCompanyItem.RetrieveList(), EntertainmentDB.Data.FilmLengthItem.RetrieveList(), EntertainmentDB.Data.GenreItem.RetrieveList(), EntertainmentDB.Data.ImageItem.RetrieveList(), EntertainmentDB.Data.LaboratoryItem.RetrieveList(), EntertainmentDB.Data.LanguageItem.RetrieveList(), EntertainmentDB.Data.LocationItem.RetrieveList(), EntertainmentDB.Data.NegativeFormatItem.RetrieveList(), EntertainmentDB.Data.PersonItem.RetrieveList(), EntertainmentDB.Data.PrintedFilmFormatItem.RetrieveList(), EntertainmentDB.Data.RuntimeItem.RetrieveList(), EntertainmentDB.Data.SoundMixItem.RetrieveList(), EntertainmentDB.Data.TextItem.RetrieveList(), EntertainmentDB.Data.TimespanItem.RetrieveList(), EntertainmentDB.Data.WeblinkItem.RetrieveList(), EntertainmentDB.Data.Movie.RetrieveList(), and EntertainmentDB.Data.Series.RetrieveList().
Retrieve()
abstract int EntertainmentDB.DBAccess.Read.DBReader.Retrieve (bool retrieveBasicInfoOnly) pure virtual
Retrieves the information from the database.
Parameters
retrieveBasicInfoOnly true if only the basic info is to be retrieved; false if also additional data is to be retrieved.
Returns
The number of data records retrieved.
Implements EntertainmentDB.DBAccess.Read.IDBReadable.
Implemented in EntertainmentDB.DBAccess.Read.SQLiteReader.
Referenced by EntertainmentDB.Data.AspectRatio.RetrieveBasicInformation(), EntertainmentDB.Data.AspectRatioItem.RetrieveBasicInformation(), EntertainmentDB.Data.Award.RetrieveBasicInformation(), EntertainmentDB.Data.AwardItem.RetrieveBasicInformation(), EntertainmentDB.Data.Camera.RetrieveBasicInformation(), EntertainmentDB.Data.CameraItem.RetrieveBasicInformation(), EntertainmentDB.Data.CastPersonItem.RetrieveBasicInformation(), EntertainmentDB.Data.Certification.RetrieveBasicInformation(), EntertainmentDB.Data.CertificationItem.RetrieveBasicInformation(), EntertainmentDB.Data.CinematographicProcess.RetrieveBasicInformation(), EntertainmentDB.Data.CinematographicProcessItem.RetrieveBasicInformation(), EntertainmentDB.Data.Color.RetrieveBasicInformation(), EntertainmentDB.Data.ColorItem.RetrieveBasicInformation(), EntertainmentDB.Data.Company.RetrieveBasicInformation(), EntertainmentDB.Data.CompanyItem.RetrieveBasicInformation(), EntertainmentDB.Data.Connection.RetrieveBasicInformation(), EntertainmentDB.Data.Country.RetrieveBasicInformation(), EntertainmentDB.Data.CountryItem.RetrieveBasicInformation(), EntertainmentDB.Data.DistributorCompanyItem.RetrieveBasicInformation(), EntertainmentDB.Data.Edition.RetrieveBasicInformation(), EntertainmentDB.Data.FilmFormat.RetrieveBasicInformation(), EntertainmentDB.Data.FilmLengthItem.RetrieveBasicInformation(), EntertainmentDB.Data.Genre.RetrieveBasicInformation(), EntertainmentDB.Data.GenreItem.RetrieveBasicInformation(), EntertainmentDB.Data.Image.RetrieveBasicInformation(), EntertainmentDB.Data.ImageItem.RetrieveBasicInformation(), EntertainmentDB.Data.Laboratory.RetrieveBasicInformation(), EntertainmentDB.Data.LaboratoryItem.RetrieveBasicInformation(), EntertainmentDB.Data.Language.RetrieveBasicInformation(), EntertainmentDB.Data.LanguageItem.RetrieveBasicInformation(), EntertainmentDB.Data.Location.RetrieveBasicInformation(), EntertainmentDB.Data.LocationItem.RetrieveBasicInformation(), EntertainmentDB.Data.Movie.RetrieveBasicInformation(), EntertainmentDB.Data.NegativeFormatItem.RetrieveBasicInformation(), EntertainmentDB.Data.Person.RetrieveBasicInformation(), EntertainmentDB.Data.PersonItem.RetrieveBasicInformation(), EntertainmentDB.Data.PrintedFilmFormatItem.RetrieveBasicInformation(), EntertainmentDB.Data.RuntimeItem.RetrieveBasicInformation(), EntertainmentDB.Data.Series.RetrieveBasicInformation(), EntertainmentDB.Data.SoundMix.RetrieveBasicInformation(), EntertainmentDB.Data.SoundMixItem.RetrieveBasicInformation(), EntertainmentDB.Data.Status.RetrieveBasicInformation(), EntertainmentDB.Data.Text.RetrieveBasicInformation(), EntertainmentDB.Data.TextItem.RetrieveBasicInformation(), EntertainmentDB.Data.TimespanItem.RetrieveBasicInformation(), EntertainmentDB.Data.Type.RetrieveBasicInformation(), EntertainmentDB.Data.Weblink.RetrieveBasicInformation(), EntertainmentDB.Data.WeblinkItem.RetrieveBasicInformation(), EntertainmentDB.Data.AspectRatioItem.RetrieveList(), EntertainmentDB.Data.AwardItem.RetrieveList(), EntertainmentDB.Data.CameraItem.RetrieveList(), EntertainmentDB.Data.CastPersonItem.RetrieveList(), EntertainmentDB.Data.CertificationItem.RetrieveList(), EntertainmentDB.Data.CinematographicProcessItem.RetrieveList(), EntertainmentDB.Data.ColorItem.RetrieveList(), EntertainmentDB.Data.CompanyItem.RetrieveList(), EntertainmentDB.Data.CountryItem.RetrieveList(), EntertainmentDB.Data.DistributorCompanyItem.RetrieveList(), EntertainmentDB.Data.FilmLengthItem.RetrieveList(), EntertainmentDB.Data.GenreItem.RetrieveList(), EntertainmentDB.Data.ImageItem.RetrieveList(), EntertainmentDB.Data.LaboratoryItem.RetrieveList(), EntertainmentDB.Data.LanguageItem.RetrieveList(), EntertainmentDB.Data.LocationItem.RetrieveList(), EntertainmentDB.Data.NegativeFormatItem.RetrieveList(), EntertainmentDB.Data.PersonItem.RetrieveList(), EntertainmentDB.Data.PrintedFilmFormatItem.RetrieveList(), EntertainmentDB.Data.RuntimeItem.RetrieveList(), EntertainmentDB.Data.SoundMixItem.RetrieveList(), EntertainmentDB.Data.TextItem.RetrieveList(), EntertainmentDB.Data.TimespanItem.RetrieveList(), EntertainmentDB.Data.WeblinkItem.RetrieveList(), EntertainmentDB.Data.Movie.RetrieveList(), and EntertainmentDB.Data.Series.RetrieveList().
Member Data Documentation
Logger
NLog.Logger EntertainmentDB.DBAccess.Read.DBReader.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by EntertainmentDB.DBAccess.Read.DBReader.DBReader().
Property Documentation
Query
string EntertainmentDB.DBAccess.Read.DBReader.Query = "" get set
The query of the database reader.
Referenced by EntertainmentDB.DBAccess.Read.SQLiteReader.Retrieve(), EntertainmentDB.Data.AspectRatio.RetrieveBasicInformation(), EntertainmentDB.Data.AspectRatioItem.RetrieveBasicInformation(), EntertainmentDB.Data.Award.RetrieveBasicInformation(), EntertainmentDB.Data.AwardItem.RetrieveBasicInformation(), EntertainmentDB.Data.Camera.RetrieveBasicInformation(), EntertainmentDB.Data.CameraItem.RetrieveBasicInformation(), EntertainmentDB.Data.CastPersonItem.RetrieveBasicInformation(), EntertainmentDB.Data.Certification.RetrieveBasicInformation(), EntertainmentDB.Data.CertificationItem.RetrieveBasicInformation(), EntertainmentDB.Data.CinematographicProcess.RetrieveBasicInformation(), EntertainmentDB.Data.CinematographicProcessItem.RetrieveBasicInformation(), EntertainmentDB.Data.Color.RetrieveBasicInformation(), EntertainmentDB.Data.ColorItem.RetrieveBasicInformation(), EntertainmentDB.Data.Company.RetrieveBasicInformation(), EntertainmentDB.Data.CompanyItem.RetrieveBasicInformation(), EntertainmentDB.Data.Connection.RetrieveBasicInformation(), EntertainmentDB.Data.Country.RetrieveBasicInformation(), EntertainmentDB.Data.CountryItem.RetrieveBasicInformation(), EntertainmentDB.Data.DistributorCompanyItem.RetrieveBasicInformation(), EntertainmentDB.Data.Edition.RetrieveBasicInformation(), EntertainmentDB.Data.FilmFormat.RetrieveBasicInformation(), EntertainmentDB.Data.FilmLengthItem.RetrieveBasicInformation(), EntertainmentDB.Data.Genre.RetrieveBasicInformation(), EntertainmentDB.Data.GenreItem.RetrieveBasicInformation(), EntertainmentDB.Data.Image.RetrieveBasicInformation(), EntertainmentDB.Data.ImageItem.RetrieveBasicInformation(), EntertainmentDB.Data.Laboratory.RetrieveBasicInformation(), EntertainmentDB.Data.LaboratoryItem.RetrieveBasicInformation(), EntertainmentDB.Data.Language.RetrieveBasicInformation(), EntertainmentDB.Data.LanguageItem.RetrieveBasicInformation(), EntertainmentDB.Data.Location.RetrieveBasicInformation(), EntertainmentDB.Data.LocationItem.RetrieveBasicInformation(), EntertainmentDB.Data.Movie.RetrieveBasicInformation(), EntertainmentDB.Data.NegativeFormatItem.RetrieveBasicInformation(), EntertainmentDB.Data.Person.RetrieveBasicInformation(), EntertainmentDB.Data.PersonItem.RetrieveBasicInformation(), EntertainmentDB.Data.PrintedFilmFormatItem.RetrieveBasicInformation(), EntertainmentDB.Data.RuntimeItem.RetrieveBasicInformation(), EntertainmentDB.Data.Series.RetrieveBasicInformation(), EntertainmentDB.Data.SoundMix.RetrieveBasicInformation(), EntertainmentDB.Data.SoundMixItem.RetrieveBasicInformation(), EntertainmentDB.Data.Status.RetrieveBasicInformation(), EntertainmentDB.Data.Text.RetrieveBasicInformation(), EntertainmentDB.Data.TextItem.RetrieveBasicInformation(), EntertainmentDB.Data.TimespanItem.RetrieveBasicInformation(), EntertainmentDB.Data.Type.RetrieveBasicInformation(), EntertainmentDB.Data.Weblink.RetrieveBasicInformation(), EntertainmentDB.Data.WeblinkItem.RetrieveBasicInformation(), EntertainmentDB.Data.AspectRatioItem.RetrieveList(), EntertainmentDB.Data.AwardItem.RetrieveList(), EntertainmentDB.Data.CameraItem.RetrieveList(), EntertainmentDB.Data.CastPersonItem.RetrieveList(), EntertainmentDB.Data.CertificationItem.RetrieveList(), EntertainmentDB.Data.CinematographicProcessItem.RetrieveList(), EntertainmentDB.Data.ColorItem.RetrieveList(), EntertainmentDB.Data.CompanyItem.RetrieveList(), EntertainmentDB.Data.CountryItem.RetrieveList(), EntertainmentDB.Data.DistributorCompanyItem.RetrieveList(), EntertainmentDB.Data.FilmLengthItem.RetrieveList(), EntertainmentDB.Data.GenreItem.RetrieveList(), EntertainmentDB.Data.ImageItem.RetrieveList(), EntertainmentDB.Data.LaboratoryItem.RetrieveList(), EntertainmentDB.Data.LanguageItem.RetrieveList(), EntertainmentDB.Data.LocationItem.RetrieveList(), EntertainmentDB.Data.NegativeFormatItem.RetrieveList(), EntertainmentDB.Data.PersonItem.RetrieveList(), EntertainmentDB.Data.PrintedFilmFormatItem.RetrieveList(), EntertainmentDB.Data.RuntimeItem.RetrieveList(), EntertainmentDB.Data.SoundMixItem.RetrieveList(), EntertainmentDB.Data.TextItem.RetrieveList(), EntertainmentDB.Data.TimespanItem.RetrieveList(), EntertainmentDB.Data.WeblinkItem.RetrieveList(), EntertainmentDB.Data.Movie.RetrieveList(), and EntertainmentDB.Data.Series.RetrieveList().
Table
DataTable EntertainmentDB.DBAccess.Read.DBReader.Table = new DataTable() get protected set
The data table of the database reader.
Referenced by EntertainmentDB.DBAccess.Read.SQLiteReader.Retrieve(), EntertainmentDB.Data.AspectRatio.RetrieveBasicInformation(), EntertainmentDB.Data.AspectRatioItem.RetrieveBasicInformation(), EntertainmentDB.Data.Award.RetrieveBasicInformation(), EntertainmentDB.Data.AwardItem.RetrieveBasicInformation(), EntertainmentDB.Data.Camera.RetrieveBasicInformation(), EntertainmentDB.Data.CameraItem.RetrieveBasicInformation(), EntertainmentDB.Data.CastPersonItem.RetrieveBasicInformation(), EntertainmentDB.Data.Certification.RetrieveBasicInformation(), EntertainmentDB.Data.CertificationItem.RetrieveBasicInformation(), EntertainmentDB.Data.CinematographicProcess.RetrieveBasicInformation(), EntertainmentDB.Data.CinematographicProcessItem.RetrieveBasicInformation(), EntertainmentDB.Data.Color.RetrieveBasicInformation(), EntertainmentDB.Data.ColorItem.RetrieveBasicInformation(), EntertainmentDB.Data.Company.RetrieveBasicInformation(), EntertainmentDB.Data.CompanyItem.RetrieveBasicInformation(), EntertainmentDB.Data.Connection.RetrieveBasicInformation(), EntertainmentDB.Data.Country.RetrieveBasicInformation(), EntertainmentDB.Data.CountryItem.RetrieveBasicInformation(), EntertainmentDB.Data.DistributorCompanyItem.RetrieveBasicInformation(), EntertainmentDB.Data.Edition.RetrieveBasicInformation(), EntertainmentDB.Data.FilmFormat.RetrieveBasicInformation(), EntertainmentDB.Data.FilmLengthItem.RetrieveBasicInformation(), EntertainmentDB.Data.Genre.RetrieveBasicInformation(), EntertainmentDB.Data.GenreItem.RetrieveBasicInformation(), EntertainmentDB.Data.Image.RetrieveBasicInformation(), EntertainmentDB.Data.ImageItem.RetrieveBasicInformation(), EntertainmentDB.Data.Laboratory.RetrieveBasicInformation(), EntertainmentDB.Data.LaboratoryItem.RetrieveBasicInformation(), EntertainmentDB.Data.Language.RetrieveBasicInformation(), EntertainmentDB.Data.LanguageItem.RetrieveBasicInformation(), EntertainmentDB.Data.Location.RetrieveBasicInformation(), EntertainmentDB.Data.LocationItem.RetrieveBasicInformation(), EntertainmentDB.Data.Movie.RetrieveBasicInformation(), EntertainmentDB.Data.NegativeFormatItem.RetrieveBasicInformation(), EntertainmentDB.Data.Person.RetrieveBasicInformation(), EntertainmentDB.Data.PersonItem.RetrieveBasicInformation(), EntertainmentDB.Data.PrintedFilmFormatItem.RetrieveBasicInformation(), EntertainmentDB.Data.RuntimeItem.RetrieveBasicInformation(), EntertainmentDB.Data.Series.RetrieveBasicInformation(), EntertainmentDB.Data.SoundMix.RetrieveBasicInformation(), EntertainmentDB.Data.SoundMixItem.RetrieveBasicInformation(), EntertainmentDB.Data.Status.RetrieveBasicInformation(), EntertainmentDB.Data.Text.RetrieveBasicInformation(), EntertainmentDB.Data.TextItem.RetrieveBasicInformation(), EntertainmentDB.Data.TimespanItem.RetrieveBasicInformation(), EntertainmentDB.Data.Type.RetrieveBasicInformation(), EntertainmentDB.Data.Weblink.RetrieveBasicInformation(), EntertainmentDB.Data.WeblinkItem.RetrieveBasicInformation(), EntertainmentDB.Data.AspectRatioItem.RetrieveList(), EntertainmentDB.Data.AwardItem.RetrieveList(), EntertainmentDB.Data.CameraItem.RetrieveList(), EntertainmentDB.Data.CastPersonItem.RetrieveList(), EntertainmentDB.Data.CertificationItem.RetrieveList(), EntertainmentDB.Data.CinematographicProcessItem.RetrieveList(), EntertainmentDB.Data.ColorItem.RetrieveList(), EntertainmentDB.Data.CompanyItem.RetrieveList(), EntertainmentDB.Data.CountryItem.RetrieveList(), EntertainmentDB.Data.DistributorCompanyItem.RetrieveList(), EntertainmentDB.Data.FilmLengthItem.RetrieveList(), EntertainmentDB.Data.GenreItem.RetrieveList(), EntertainmentDB.Data.ImageItem.RetrieveList(), EntertainmentDB.Data.LaboratoryItem.RetrieveList(), EntertainmentDB.Data.LanguageItem.RetrieveList(), EntertainmentDB.Data.LocationItem.RetrieveList(), EntertainmentDB.Data.NegativeFormatItem.RetrieveList(), EntertainmentDB.Data.PersonItem.RetrieveList(), EntertainmentDB.Data.PrintedFilmFormatItem.RetrieveList(), EntertainmentDB.Data.RuntimeItem.RetrieveList(), EntertainmentDB.Data.SoundMixItem.RetrieveList(), EntertainmentDB.Data.TextItem.RetrieveList(), EntertainmentDB.Data.TimespanItem.RetrieveList(), EntertainmentDB.Data.WeblinkItem.RetrieveList(), EntertainmentDB.Data.Movie.RetrieveList(), and EntertainmentDB.Data.Series.RetrieveList().
The documentation for this class was generated from the following file:
C:/Users/Sandra/Projekte/GitHub/EntertainmentInfothek_public/src/EntertainmentDB/DBAccess/Read/DBReader.cs