EntertainmentInfothek: EntertainmentDB.Data.NegativeFormatItem Class Reference
EntertainmentDB.Data.NegativeFormatItem Class Reference
Provides a negative format item.
Public Member Functions
NegativeFormatItem (DBReader reader)
Initializes a negative format item with an empty id string.
NegativeFormatItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes a negative format item with the given id string.
override int RetrieveBasicInformation (bool retrieveBasicInfoOnly)
Retrieves the basic information of the negative format item from the database.
override int RetrieveAdditionalInformation ()
Retrieves the additional information of the negative format item from the database (none available).
Public Member Functions inherited from EntertainmentDB.Data.Entry
virtual int Retrieve (bool retrieveBasicInfoOnly)
Retrieves the information of the entry from the database.
Static Public Member Functions
static List< NegativeFormatItem > RetrieveList (DBReader reader, string baseTableName, string baseTableID, string targetTableName, string order="ID")
Retrieves a list of negative format items from the database.
Properties
FilmFormat FilmFormat [getset]
The film format of the negative format item.
Properties inherited from EntertainmentDB.Data.EntryItem
string BaseTableName [getset]
The base table name of the entry item.
string TargetTableName [getset]
The target table name of the entry item.
Properties inherited from EntertainmentDB.Data.Entry
DBReader Reader [getprotected set]
The database reader to be used to read the entry information from the database.
string ID [getset]
The id of the entry.
string Details [getset]
The details of the entry.
Status Status [getset]
The status of the entry.
string LastUpdated [getset]
The date of last update of the entry.
Static Private Attributes
static NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Additional Inherited Members
Protected Member Functions inherited from EntertainmentDB.Data.EntryItem
EntryItem (DBReader reader)
Initializes an entry item with an emtpy id string.
EntryItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes an entry item with the given id string.
Protected Member Functions inherited from EntertainmentDB.Data.Entry
Entry (DBReader reader)
Initializes an entry with the given reader and id string.
Entry (DBReader reader, string id)
Initializes an entry with the given reader and id string.
Detailed Description
Provides a negative format item.
Constructor & Destructor Documentation
NegativeFormatItem() [1/2]
EntertainmentDB.Data.NegativeFormatItem.NegativeFormatItem (DBReader reader)
Initializes a negative format item with an empty id string.
Parameters
reader The database reader to be used to read the negative format item information from the database.
Referenced by EntertainmentDB.Data.NegativeFormatItem.RetrieveList().
NegativeFormatItem() [2/2]
EntertainmentDB.Data.NegativeFormatItem.NegativeFormatItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes a negative format item with the given id string.
Parameters
reader The database reader to be used to read the negative format item information from the database.
id The id of the negative format item.
baseTableName The base table name of the negative format item.
targetTableName The target table name of the negative format item.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Member Function Documentation
RetrieveAdditionalInformation()
override int EntertainmentDB.Data.NegativeFormatItem.RetrieveAdditionalInformation () virtual
Retrieves the additional information of the negative format item from the database (none available).
Returns
0
Implements EntertainmentDB.Data.Entry.
RetrieveBasicInformation()
override int EntertainmentDB.Data.NegativeFormatItem.RetrieveBasicInformation (bool retrieveBasicInfoOnly) virtual
Retrieves the basic information of the negative format item from the database.
Parameters
retrieveBasicInfoOnly true if only the basic info is to be retrieved; false if also additional data is to be retrieved.
Returns
1 if data record was retrieved; 0 if no data record matched the id.
Implements EntertainmentDB.Data.Entry.
RetrieveList()
static List< NegativeFormatItem > EntertainmentDB.Data.NegativeFormatItem.RetrieveList (DBReader reader, string baseTableName, string baseTableID, string targetTableName, string order = "ID") static
Retrieves a list of negative format items from the database.
Parameters
reader The reader to be used to retrieve the data records.
baseTableName The base table name of the negative format item.
baseTableID The base table id of the negative format item.
targetTableName The target table name of the negative format item.
order The order in which the data records are to be sorted.
Returns
The list of negative format items.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Referenced by EntertainmentDB.Data.Movie.RetrieveAdditionalInformation().
Member Data Documentation
Logger
NLog.Logger EntertainmentDB.Data.NegativeFormatItem.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by EntertainmentDB.Data.NegativeFormatItem.NegativeFormatItem().
Property Documentation
FilmFormat
FilmFormat EntertainmentDB.Data.NegativeFormatItem.FilmFormat get set
The film format of the negative format item.
Referenced by EntertainmentDB.Data.NegativeFormatItem.RetrieveBasicInformation().
The documentation for this class was generated from the following file:
C:/Users/Sandra/Projekte/GitHub/EntertainmentInfothek_public/src/EntertainmentDB/Data/NegativeFormatItem.cs