EntertainmentInfothek: WikiPageCreator.Export.Create.MovieFileContentCreator Class Reference
WikiPageCreator.Export.Create.MovieFileContentCreator Class Reference
Provides a file content crator for a movie.
Public Member Functions
MovieFileContentCreator (Movie movie)
Initializes a new movie file content creator with the given movie.
string GetFileName ()
Creates the file name of the movie page.
List< string > CreateContent (string targetLanguageCode)
Creates the formatted content of the movie page.
void CreateHeader (string targetLanguageCode)
Creates the formatted header of the movie page.
void CreateFooter (string targetLanguageCode)
Creates the formatted footer of the movie page.
void CreateTitle (string targetLanguageCode)
Creates the formatted title of the movie page.
void CreateInfoBoxHeader (string targetLanguageCode)
Creates the formatted infobox header of the movie page.
void CreateInfoBoxEnd (string targetLanguageCode)
Creates the formatted infobox footer of the movie page.
void CreateInfoBoxTitle (string targetLanguageCode)
Creates the formatted infobox title field of the movie page.
void CreateInfoBoxLogo (string targetLanguageCode)
Creates the formatted infobox logo field of the movie page.
void CreateInfoBoxType (string targetLanguageCode)
Creates the formatted infobox type field of the movie page.
void CreateInfoBoxOriginalReleaseDate (string targetLanguageCode)
Creates the formatted infobox release date field of the movie page.
void CreateInfoBoxGenre (string targetLanguageCode)
Creates the formatted infobox genre field of the movie page.
void CreateInfoBoxCertification (string targetLanguageCode)
Creates the formatted infobox certification field of the movie page.
void CreateInfoBoxCountry (string targetLanguageCode)
Creates the formatted infobox country field of the movie page.
virtual void CreateInfoBoxLanguage (string targetLanguageCode)
Creates the formatted infobox language field of the movie page.
void CreateInfoBoxBudget (string targetLanguageCode)
Creates the formatted infobox budget field of the movie page.
void CreateInfoBoxWorldwideGross (string targetLanguageCode)
Creates the formatted infobox worldwide gross field of the movie page.
void CreateInfoBoxRuntime (string targetLanguageCode)
Creates the formatted infobox runtime field of the movie page.
void CreateInfoBoxSoundMix (string targetLanguageCode)
Creates the formatted infobox sound mixes field of the movie page.
void CreateInfoBoxColor (string targetLanguageCode)
Creates the formatted infobox color field of the movie page.
void CreateInfoBoxAspectRatio (string targetLanguageCode)
Creates the formatted infobox aspect ratio field of the movie page.
void CreateInfoBoxCamera (string targetLanguageCode)
Creates the formatted infobox camera field of the movie page.
void CreateInfoBoxLaboratory (string targetLanguageCode)
Creates the formatted infobox laboratory field of the movie page.
void CreateInfoBoxFilmLength (string targetLanguageCode)
Creates the formatted infobox film length field of the movie page.
void CreateInfoBoxNegativeFormat (string targetLanguageCode)
Creates the formatted infobox negative format field of the movie page.
void CreateInfoBoxCinematographicProcess (string targetLanguageCode)
Creates the formatted infobox cinematographic process field of the movie page.
void CreateInfoBoxPrintedFilmFormat (string targetLanguageCode)
Creates the formatted infobox printed film format of the movie page.
virtual void CreatePosterChapter (string targetLanguageCode)
Creates the formatted poster chapter of the movie page.
virtual void CreateCoverChapter (string targetLanguageCode)
Creates the formatted cover chapter of the movie page.
virtual void CreateDescriptionChapter (string targetLanguageCode)
Creates the formatted description chapter of the movie page.
virtual void CreateReviewChapter (string targetLanguageCode)
Creates the formatted review chapter of the movie page.
virtual void CreateImageChapter (string targetLanguageCode)
Creates the formatted image chapter of the movie page.
virtual void CreateCastAndCrewChapter (string targetLanguageCode)
Creates the formatted cast and crew chapter of the movie page.
virtual void CreateCompanyChapter (string targetLanguageCode)
Creates the formatted company chapter of the movie page.
virtual void CreateFilmingAndProductionChapter (string targetLanguageCode)
Creates the formatted filming and production chapter of the movie page.
virtual void CreateAwardChapter (string targetLanguageCode)
Creates the formatted award chapter of the movie page.
virtual void CreateWeblinkChapter (string targetLanguageCode)
Creates the formatted weblink chapter of the movie page.
virtual void CreateConnectionChapter (string targetLanguageCode)
Creates the formatted connection chapter of the movie page.
Properties
Formatter Formatter = new DokuWikiFormatter() [getset]
The formatter to be used to format the content of the movie.
Movie Movie [getset]
The movie of the movie file content creator.
List< string > Content = new List<string>() [getset]
The Content of the movie file content creator.
Private Member Functions
void CreateTextItemSection (string targetLanguageCode, List< TextItem > texts)
Creates a formatted text section of the movie page.
void CreateImageItemSection (string targetLanguageCode, List< ImageItem > images)
Creates a formatted image section of the movie page.
void CreatePersonItemSection (string targetLanguageCode, string[] heading, List< PersonItem > persons)
Creates a formatted person section of the movie page.
void CreateCastPersonItemSection (string targetLanguageCode, string[] heading, List< CastPersonItem > persons)
Creates a formatted cast person section of the movie page.
void CreateCompanyItemSection (string targetLanguageCode, string[] heading, List< CompanyItem > companies)
Creates a formatted company section of the movie page.
void CreateDistributorCompanyItemSection (string targetLanguageCode, string[] heading, List< DistributorCompanyItem > companies)
Creates a formatted distributor company section of the movie page.
Static Private Attributes
static NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides a file content crator for a movie.
Constructor & Destructor Documentation
MovieFileContentCreator()
WikiPageCreator.Export.Create.MovieFileContentCreator.MovieFileContentCreator (Movie movie)
Initializes a new movie file content creator with the given movie.
Parameters
movie
Member Function Documentation
CreateAwardChapter()
virtual void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateAwardChapter (string targetLanguageCode) virtual
Creates the formatted award chapter of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateCastAndCrewChapter()
virtual void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCastAndCrewChapter (string targetLanguageCode) virtual
Creates the formatted cast and crew chapter of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateCastPersonItemSection()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCastPersonItemSection (string targetLanguageCode, string[] heading, List< CastPersonItem > persons) private
Creates a formatted cast person section of the movie page.
Parameters
targetLanguageCode The language code of the target language.
heading The heading for the section; [0] english; [1] german.
persons The list of persons for the section.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCastAndCrewChapter().
CreateCompanyChapter()
virtual void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCompanyChapter (string targetLanguageCode) virtual
Creates the formatted company chapter of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateCompanyItemSection()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCompanyItemSection (string targetLanguageCode, string[] heading, List< CompanyItem > companies) private
Creates a formatted company section of the movie page.
Parameters
targetLanguageCode The language code of the target language.
heading The heading for the section; [0] english; [1] german.
companies The list of companies for the section.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCompanyChapter().
CreateConnectionChapter()
virtual void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateConnectionChapter (string targetLanguageCode) virtual
Creates the formatted connection chapter of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateContent()
List< string > WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent (string targetLanguageCode)
Creates the formatted content of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Returns
The formatted content of the movie.
CreateCoverChapter()
virtual void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCoverChapter (string targetLanguageCode) virtual
Creates the formatted cover chapter of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateDescriptionChapter()
virtual void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateDescriptionChapter (string targetLanguageCode) virtual
Creates the formatted description chapter of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateDistributorCompanyItemSection()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateDistributorCompanyItemSection (string targetLanguageCode, string[] heading, List< DistributorCompanyItem > companies) private
Creates a formatted distributor company section of the movie page.
Parameters
targetLanguageCode The language code of the target language.
heading The heading for the section; [0] english; [1] german.
companies The list of distributor companies for the section.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCompanyChapter().
CreateFilmingAndProductionChapter()
virtual void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateFilmingAndProductionChapter (string targetLanguageCode) virtual
Creates the formatted filming and production chapter of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateFooter()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateFooter (string targetLanguageCode)
Creates the formatted footer of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateHeader()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateHeader (string targetLanguageCode)
Creates the formatted header of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateImageChapter()
virtual void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateImageChapter (string targetLanguageCode) virtual
Creates the formatted image chapter of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateImageItemSection()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateImageItemSection (string targetLanguageCode, List< ImageItem > images) private
Creates a formatted image section of the movie page.
Parameters
targetLanguageCode The language code of the target language.
images The list of images for the section.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCoverChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateImageChapter(), and WikiPageCreator.Export.Create.MovieFileContentCreator.CreatePosterChapter().
CreateInfoBoxAspectRatio()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxAspectRatio (string targetLanguageCode)
Creates the formatted infobox aspect ratio field of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxBudget()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxBudget (string targetLanguageCode)
Creates the formatted infobox budget field of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxCamera()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCamera (string targetLanguageCode)
Creates the formatted infobox camera field of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxCertification()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCertification (string targetLanguageCode)
Creates the formatted infobox certification field of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxCinematographicProcess()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCinematographicProcess (string targetLanguageCode)
Creates the formatted infobox cinematographic process field of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxColor()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxColor (string targetLanguageCode)
Creates the formatted infobox color field of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxCountry()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCountry (string targetLanguageCode)
Creates the formatted infobox country field of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxEnd()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxEnd (string targetLanguageCode)
Creates the formatted infobox footer of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxFilmLength()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxFilmLength (string targetLanguageCode)
Creates the formatted infobox film length field of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxGenre()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxGenre (string targetLanguageCode)
Creates the formatted infobox genre field of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxHeader()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxHeader (string targetLanguageCode)
Creates the formatted infobox header of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxLaboratory()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxLaboratory (string targetLanguageCode)
Creates the formatted infobox laboratory field of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxLanguage()
virtual void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxLanguage (string targetLanguageCode) virtual
Creates the formatted infobox language field of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxLogo()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxLogo (string targetLanguageCode)
Creates the formatted infobox logo field of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxNegativeFormat()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxNegativeFormat (string targetLanguageCode)
Creates the formatted infobox negative format field of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxOriginalReleaseDate()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxOriginalReleaseDate (string targetLanguageCode)
Creates the formatted infobox release date field of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxPrintedFilmFormat()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxPrintedFilmFormat (string targetLanguageCode)
Creates the formatted infobox printed film format of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxRuntime()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxRuntime (string targetLanguageCode)
Creates the formatted infobox runtime field of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxSoundMix()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxSoundMix (string targetLanguageCode)
Creates the formatted infobox sound mixes field of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxTitle()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxTitle (string targetLanguageCode)
Creates the formatted infobox title field of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxType()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxType (string targetLanguageCode)
Creates the formatted infobox type field of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateInfoBoxWorldwideGross()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxWorldwideGross (string targetLanguageCode)
Creates the formatted infobox worldwide gross field of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreatePersonItemSection()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreatePersonItemSection (string targetLanguageCode, string[] heading, List< PersonItem > persons) private
Creates a formatted person section of the movie page.
Parameters
targetLanguageCode The language code of the target language.
heading The heading for the section; [0] english; [1] german.
persons The list of persons for the section.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCastAndCrewChapter().
CreatePosterChapter()
virtual void WikiPageCreator.Export.Create.MovieFileContentCreator.CreatePosterChapter (string targetLanguageCode) virtual
Creates the formatted poster chapter of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateReviewChapter()
virtual void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateReviewChapter (string targetLanguageCode) virtual
Creates the formatted review chapter of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateTextItemSection()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateTextItemSection (string targetLanguageCode, List< TextItem > texts) private
Creates a formatted text section of the movie page.
Parameters
targetLanguageCode The language code of the target language.
texts The list of texts for the section.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateDescriptionChapter(), and WikiPageCreator.Export.Create.MovieFileContentCreator.CreateReviewChapter().
CreateTitle()
void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateTitle (string targetLanguageCode)
Creates the formatted title of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
CreateWeblinkChapter()
virtual void WikiPageCreator.Export.Create.MovieFileContentCreator.CreateWeblinkChapter (string targetLanguageCode) virtual
Creates the formatted weblink chapter of the movie page.
Parameters
targetLanguageCode The language code of the target language.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent().
GetFileName()
string WikiPageCreator.Export.Create.MovieFileContentCreator.GetFileName ()
Creates the file name of the movie page.
Returns
The formatted file name.
Member Data Documentation
Logger
NLog.Logger WikiPageCreator.Export.Create.MovieFileContentCreator.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateAwardChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCastAndCrewChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCastPersonItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCompanyChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCompanyItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateConnectionChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCoverChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateDescriptionChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateDistributorCompanyItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateFilmingAndProductionChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateFooter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateHeader(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateImageChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateImageItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxAspectRatio(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxBudget(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCamera(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCertification(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCinematographicProcess(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxColor(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCountry(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxEnd(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxFilmLength(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxGenre(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxHeader(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxLaboratory(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxLanguage(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxLogo(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxNegativeFormat(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxOriginalReleaseDate(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxPrintedFilmFormat(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxRuntime(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxSoundMix(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxTitle(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxType(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxWorldwideGross(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreatePersonItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreatePosterChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateReviewChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateTextItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateTitle(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateWeblinkChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.GetFileName(), and WikiPageCreator.Export.Create.MovieFileContentCreator.MovieFileContentCreator().
Property Documentation
Content
List<string> WikiPageCreator.Export.Create.MovieFileContentCreator.Content = new List<string>() get set
The Content of the movie file content creator.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateAwardChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCastAndCrewChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCastPersonItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCompanyChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCompanyItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateConnectionChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateContent(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCoverChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateDescriptionChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateDistributorCompanyItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateFilmingAndProductionChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateHeader(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateImageChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateImageItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxAspectRatio(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxBudget(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCamera(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCertification(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCinematographicProcess(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxColor(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCountry(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxEnd(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxFilmLength(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxGenre(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxHeader(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxLaboratory(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxLanguage(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxLogo(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxNegativeFormat(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxOriginalReleaseDate(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxPrintedFilmFormat(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxRuntime(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxSoundMix(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxTitle(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxType(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxWorldwideGross(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreatePersonItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreatePosterChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateReviewChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateTextItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateTitle(), and WikiPageCreator.Export.Create.MovieFileContentCreator.CreateWeblinkChapter().
Formatter
Formatter WikiPageCreator.Export.Create.MovieFileContentCreator.Formatter = new DokuWikiFormatter() get set
The formatter to be used to format the content of the movie.
Movie
Movie WikiPageCreator.Export.Create.MovieFileContentCreator.Movie get set
The movie of the movie file content creator.
The documentation for this class was generated from the following file:
C:/Users/Sandra/Projekte/GitHub/EntertainmentInfothek_public/src/WikiPageCreator/Export/Create/MovieFileContentCreator.cs