EntertainmentInfothek: EntertainmentDB.DBAccess.Read.SQLiteReader Class Reference
EntertainmentDB.DBAccess.Read.SQLiteReader Class Reference
Provides a SQLite database reader.
Public Member Functions
SQLiteReader ()
Initializes a SQLite database reader.
override DBReader New ()
Returns a new SQLiteReader.
override int Retrieve (bool retrieveBasicInfoOnly)
Retrieves the information from the SQLite database.
Static Private Attributes
static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Additional Inherited Members
Protected Member Functions inherited from EntertainmentDB.DBAccess.Read.DBReader
DBReader ()
Initializes a database reader.
Properties inherited from EntertainmentDB.DBAccess.Read.DBReader
string Query = "" [getset]
The query of the database reader.
DataTable Table = new DataTable() [getprotected set]
The data table of the database reader.
Detailed Description
Provides a SQLite database reader.
Constructor & Destructor Documentation
SQLiteReader()
EntertainmentDB.DBAccess.Read.SQLiteReader.SQLiteReader ()
Initializes a SQLite database reader.
Referenced by EntertainmentDB.DBAccess.Read.SQLiteReader.New().
Member Function Documentation
New()
override DBReader EntertainmentDB.DBAccess.Read.SQLiteReader.New () virtual
Returns a new SQLiteReader.
Returns
A new SQLiteReader.
Implements EntertainmentDB.DBAccess.Read.DBReader.
Retrieve()
override int EntertainmentDB.DBAccess.Read.SQLiteReader.Retrieve (bool retrieveBasicInfoOnly) virtual
Retrieves the information from the SQLite database.
Returns
The number of data records retrieved.
Exceptions
NullReferenceException Thrown when the query/command text is null.
Implements EntertainmentDB.DBAccess.Read.DBReader.
Member Data Documentation
Logger
readonly NLog.Logger EntertainmentDB.DBAccess.Read.SQLiteReader.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by EntertainmentDB.DBAccess.Read.SQLiteReader.Retrieve(), and EntertainmentDB.DBAccess.Read.SQLiteReader.SQLiteReader().
The documentation for this class was generated from the following file:
EntertainmentInfothek/src/EntertainmentDB/DBAccess/Read/SQLiteReader.cs