EntertainmentInfothek: WikiPageCreator.Export.Create.TypeContentCreator Class Reference
WikiPageCreator.Export.Create.TypeContentCreator Class Reference
Provides a content creator for a type
Public Member Functions
TypeContentCreator (Type type, Formatter formatter, string targetLanguageCode)
Initializes a new TypeContentCreator.
override string GetPageName ()
Returns the page name of the types page.
override List< string > CreatePageContent ()
Creates the page content of the type.
override List< string > CreateInfoBoxContent ()
Creates the infobox content of a given type.
override List< string > CreateChapterContent ()
Creates the chapter content of a given type.
override List< string > CreateSectionContent ()
Creates the section content of a given type.
Protected Member Functions
override List< string > CreatePageHeader ()
Creates the formatted header content of a given type.
override List< string > CreatePageTitle ()
Creates the formatted file title content of a given type.
override List< string > CreateNewChapter (Dictionary< string, string > title)
Creates a formatted chapter heading with the given title.
override List< string > CreateNewSection (Dictionary< string, string > title)
Creates a formatted section heading with the given title.
Protected Member Functions inherited from WikiPageCreator.Export.Create.EntryContentCreator
EntryContentCreator (Entry entry, Formatter formatter, string targetLanguageCode)
Initializes an EntryContentCreator with the given entry, formatter and target language code.
virtual List< string > CreateInfoBoxBegin ()
Creates the formatted infobox begin content of a given entry
virtual List< string > CreateInfoBoxEnd ()
Creates the formatted infobox end content of a given entry
virtual List< string > CreatePageFooter ()
Creates the formatted footer content of a given entry.
Properties
Type Type [getset]
The type to be used to create the content.
Properties inherited from WikiPageCreator.Export.Create.EntryContentCreator
Formatter Formatter [getprotected set]
The formatter to be used to format the information of the entry.
Entry Entry [getprotected set]
The entry to be used to create the content.
string TargetLanguageCode [getprotected set]
The target language (as a language code) to specify the language of the created content.
Static Private Attributes
static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides a content creator for a type
Constructor & Destructor Documentation
TypeContentCreator()
WikiPageCreator.Export.Create.TypeContentCreator.TypeContentCreator (Type type, Formatter formatter, string targetLanguageCode)
Initializes a new TypeContentCreator.
Parameters
type The type to be used to create content.
formatter The formatter to be used to format the content
targetLanguageCode The language code for the created content.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Member Function Documentation
CreateChapterContent()
override List< string > WikiPageCreator.Export.Create.TypeContentCreator.CreateChapterContent () virtual
Creates the chapter content of a given type.
Returns
The formatted content of the type.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Implements WikiPageCreator.Export.Create.EntryContentCreator.
CreateInfoBoxContent()
override List< string > WikiPageCreator.Export.Create.TypeContentCreator.CreateInfoBoxContent () virtual
Creates the infobox content of a given type.
Returns
The formatted content of the type.
Implements WikiPageCreator.Export.Create.EntryContentCreator.
Referenced by WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxType().
CreateNewChapter()
override List< string > WikiPageCreator.Export.Create.TypeContentCreator.CreateNewChapter (Dictionary< string, string > title) protected virtual
Creates a formatted chapter heading with the given title.
Parameters
title The title that is to be used as heading.
Returns
The fomatted chapter heading.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Reimplemented from WikiPageCreator.Export.Create.EntryContentCreator.
CreateNewSection()
override List< string > WikiPageCreator.Export.Create.TypeContentCreator.CreateNewSection (Dictionary< string, string > title) protected virtual
Creates a formatted section heading with the given title.
Parameters
title The title that is to be used as heading.
Returns
The fomatted chapter heading.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Reimplemented from WikiPageCreator.Export.Create.EntryContentCreator.
CreatePageContent()
override List< string > WikiPageCreator.Export.Create.TypeContentCreator.CreatePageContent () virtual
Creates the page content of the type.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Reimplemented from WikiPageCreator.Export.Create.EntryContentCreator.
CreatePageHeader()
override List< string > WikiPageCreator.Export.Create.TypeContentCreator.CreatePageHeader () protected virtual
Creates the formatted header content of a given type.
Returns
The formatted header content of the type.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Implements WikiPageCreator.Export.Create.EntryContentCreator.
CreatePageTitle()
override List< string > WikiPageCreator.Export.Create.TypeContentCreator.CreatePageTitle () protected virtual
Creates the formatted file title content of a given type.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Implements WikiPageCreator.Export.Create.EntryContentCreator.
CreateSectionContent()
override List< string > WikiPageCreator.Export.Create.TypeContentCreator.CreateSectionContent () virtual
Creates the section content of a given type.
Returns
The formatted section content of the type.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Implements WikiPageCreator.Export.Create.EntryContentCreator.
GetPageName()
override string WikiPageCreator.Export.Create.TypeContentCreator.GetPageName () virtual
Returns the page name of the types page.
Returns
The formatted page name for the type.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Implements WikiPageCreator.Export.Create.EntryContentCreator.
Member Data Documentation
Logger
readonly NLog.Logger WikiPageCreator.Export.Create.TypeContentCreator.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by WikiPageCreator.Export.Create.TypeContentCreator.CreateInfoBoxContent(), and WikiPageCreator.Export.Create.TypeContentCreator.TypeContentCreator().
Property Documentation
Type
Type WikiPageCreator.Export.Create.TypeContentCreator.Type get set
The type to be used to create the content.
The documentation for this class was generated from the following file:
C:/Users/Sandra/Projekte/GitHub/EntertainmentInfothek_public/src/WikiPageCreator/Export/Create/TypeContentCreator.cs