EntertainmentInfothek: WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator Class Reference
WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator Class Reference
Provides a content creator for an article.
Protected Member Functions
MovieAndTVArticleContentCreator (MovieAndTVArticle article, Formatter formatter, string targetLanguageCode)
Initializes a new MovieAndTVArticleContentCreator.
virtual List< string > CreateInfoBoxBudget ()
Creates the formatted infobox budget content of a given movie and tv article.
virtual List< string > CreateInfoBoxWorldwideGross ()
Creates the formatted infobox worldwide gross content of a given movie and tv article.
virtual List< string > CreateInfoBoxCountry ()
Creates the formatted infobox country content of a given movie and tv article.
virtual List< string > CreateInfoBoxLanguage ()
Creates the formatted infobox language content of a given movie and tv article.
Protected Member Functions inherited from WikiPageCreator.Export.Create.ArticleContentCreator
ArticleContentCreator (Article article, Formatter formatter, string targetLanguageCode)
Initializes a new ArticleContentCreator.
override List< string > CreatePageHeader ()
Creates the formatted header content of a given article.
override List< string > CreatePageTitle ()
Creates the formatted file title content of a given article.
virtual List< string > CreateInfoBoxTitle ()
Creates the formatted infobox title content of a given article.
virtual List< string > CreateInfoBoxType ()
Creates the formatted infobox type content of a given article.
virtual List< string > CreateInfoBoxReleaseDate ()
Creates the formatted infobox release date content of a given article.
virtual List< string > CreateInfoBoxGenre ()
Creates the formatted infobox genre content of a given article.
virtual List< string > CreateInfoBoxCertification ()
Creates the formatted infobox certification content of a given article.
virtual List< string > CreateChapterConnection ()
Creates the formatted connection chapter content of a given article.
Protected Member Functions inherited from WikiPageCreator.Export.Create.EntryContentCreator
EntryContentCreator (Entry entry, Formatter formatter, string targetLanguageCode)
Initializes an EntryContentCreator with the given entry, formatter and target language code.
virtual List< string > CreatePageContentInternal ()
Creates the page content of the entry.
virtual List< string > CreatePageHeader ()
Creates the formatted header content of a given entry.
virtual List< string > CreatePageTitle ()
Creates the formatted file title content of a given entry.
virtual List< string > CreateInfoBoxBegin ()
Creates the formatted infobox begin content of a given entry
virtual List< string > CreateInfoBoxContentInternal ()
Creates the infobox content of a given entry.
void CreateInfoBoxContentHelper (List< string > content, string title, string[] path, string pagename, string text, string additionalInfo)
Creates the specific row of the infobox content.
void CreateInfoBoxContentHelper (List< string > content, string title, string[] path, string pagename, Image image, int size, string additionalInfo)
virtual List< string > CreateInfoBoxEnd ()
Creates the formatted infobox end content of a given entry
virtual List< string > CreateNewChapter (Dictionary< string, string > title)
Creates a formatted chapter heading with the given title.
virtual List< string > CreateChapterContentInternal ()
Creates the chapter content of a given entry.
virtual List< string > CreateNewSection (Dictionary< string, string > title)
Creates a formatted section heading with the given title.
virtual List< string > CreateSectionContentInternal ()
Creates the section content of a given entry.
virtual List< string > CreatePageFooter ()
Creates the formatted footer content of a given entry.
Properties
MovieAndTVArticle MovieAndTVArticle [get, protected set]
The movie and tv article to be used to create the content.
Properties inherited from WikiPageCreator.Export.Create.ArticleContentCreator
Article Article [get, protected set]
The article to be used to create the content.
Properties inherited from WikiPageCreator.Export.Create.EntryContentCreator
Formatter Formatter [get, protected set]
The formatter to be used to format the information of the entry.
Entry Entry [get, protected set]
The entry to be used to create the content.
string TargetLanguageCode [get, protected set]
The target language (as a language code) to specify the language of the created content.
Static Private Attributes
static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Additional Inherited Members
Public Member Functions inherited from WikiPageCreator.Export.Create.ArticleContentCreator
override string GetPageName ()
Creates the page name of the article page.
override List< string > CreatePageContent ()
Creates the page content of the entry.
Public Member Functions inherited from WikiPageCreator.Export.Create.EntryContentCreator
virtual string GetPageName ()
Returns the page name of the entrys page.
virtual List< string > CreatePageContent ()
Creates the page content of the entry.
virtual List< string > CreateInfoBoxContent ()
Creates the infobox content of a given entry.
virtual List< string > CreateChapterContent ()
Creates the chapter content of a given entry.
virtual List< string > CreateSectionContent ()
Creates the section content of a given entry.
Detailed Description
Provides a content creator for an article.
Constructor & Destructor Documentation
MovieAndTVArticleContentCreator()
WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator.MovieAndTVArticleContentCreator (MovieAndTVArticle article, Formatter formatter, string targetLanguageCode) protected
Initializes a new MovieAndTVArticleContentCreator.
Parameters
article The movie and tv article to be used to create content.
formatter The formatter to be used to format the content
targetLanguageCode The language code for the created content.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Member Function Documentation
CreateInfoBoxBudget()
virtual List< string > WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator.CreateInfoBoxBudget () protected virtual
Creates the formatted infobox budget content of a given movie and tv article.
Returns
The formatted infobox budget content of the movie and tv article.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContentInternal(), and WikiPageCreator.Export.Create.SeriesContentCreator.CreateInfoBoxContentInternal().
CreateInfoBoxCountry()
virtual List< string > WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator.CreateInfoBoxCountry () protected virtual
Creates the formatted infobox country content of a given movie and tv article.
Returns
The formatted infobox country content of the movie and tv article.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContentInternal(), and WikiPageCreator.Export.Create.SeriesContentCreator.CreateInfoBoxContentInternal().
CreateInfoBoxLanguage()
virtual List< string > WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator.CreateInfoBoxLanguage () protected virtual
Creates the formatted infobox language content of a given movie and tv article.
Returns
The formatted infobox language content of the movie and tv article.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContentInternal(), and WikiPageCreator.Export.Create.SeriesContentCreator.CreateInfoBoxContentInternal().
CreateInfoBoxWorldwideGross()
virtual List< string > WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator.CreateInfoBoxWorldwideGross () protected virtual
Creates the formatted infobox worldwide gross content of a given movie and tv article.
Returns
The formatted infobox worldwide gross content of the movie and tv article.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContentInternal(), and WikiPageCreator.Export.Create.SeriesContentCreator.CreateInfoBoxContentInternal().
Member Data Documentation
Logger
readonly NLog.Logger WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator.CreateInfoBoxBudget(), WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator.CreateInfoBoxCountry(), WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator.CreateInfoBoxLanguage(), WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator.CreateInfoBoxWorldwideGross(), and WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator.MovieAndTVArticleContentCreator().
Property Documentation
MovieAndTVArticle
MovieAndTVArticle WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator.MovieAndTVArticle get protected set
The movie and tv article to be used to create the content.
The documentation for this class was generated from the following file:
EntertainmentInfothek/src/WikiPageCreator/Export/Create/MovieAndTVArticleContentCreator.cs