EntertainmentInfothek: EntertainmentDB.Data.PersonItem Class Reference
EntertainmentDB.Data.PersonItem Class Reference
Provides a person item.
Public Member Functions
PersonItem ()
Initializes a person item with an empty id string.
PersonItem (string id, string targetTableName)
Initializes a person item with the given id string.
override int RetrieveBasicInformation (bool retrieveBasicInfoOnly)
Retrieves the basic information of the person item from the database.
override int RetrieveAdditionalInformation ()
Retrieves the additional information of the person item from the database (none available).
Public Member Functions inherited from EntertainmentDB.Data.Entry
virtual int Retrieve (bool retrieveBasicInfoOnly)
Retrieves the information of the entry from the database.
Static Public Member Functions
static List< PersonItem > RetrieveList (DBReader reader, string baseTableName, string baseTableID, string targetTableName, string order="ID")
Retrieves a list of person items from the database.
Properties
Person Person [getset]
The person of the person item.
string Role [getset]
The role of the person item.
Properties inherited from EntertainmentDB.Data.EntryItem
string BaseTableName [getset]
The base table name of the entry.
string TargetTableName [getset]
The target table name of the entry.
Properties inherited from EntertainmentDB.Data.Entry
DBReader Reader = new SQLiteReader() [getprotected set]
The database reader to be used to read the entry information from the database.
string ID [getset]
The id of the entry.
string Details [getset]
The details of the entry.
Status Status [getset]
The status of the entry.
string LastUpdated [getset]
The date of last update of the entry.
Static Private Attributes
static NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Additional Inherited Members
Protected Member Functions inherited from EntertainmentDB.Data.EntryItem
EntryItem ()
Initializes an entry item with an emtpy id string.
EntryItem (string id, string targetTableName)
Initializes an entry item with the given id string.
Protected Member Functions inherited from EntertainmentDB.Data.Entry
Entry ()
Initializes an entry with an empty id string.
Entry (string id)
Initializes an entry with the given id string.
Detailed Description
Provides a person item.
Constructor & Destructor Documentation
PersonItem() [1/2]
EntertainmentDB.Data.PersonItem.PersonItem ()
Initializes a person item with an empty id string.
Referenced by EntertainmentDB.Data.PersonItem.RetrieveList().
PersonItem() [2/2]
EntertainmentDB.Data.PersonItem.PersonItem (string id, string targetTableName)
Initializes a person item with the given id string.
Parameters
id The id of the person item.
targetTableName The target table name of the person item.
Exceptions
ArgumentNullException Thrown when the given id or target table name is null.
Member Function Documentation
RetrieveAdditionalInformation()
override int EntertainmentDB.Data.PersonItem.RetrieveAdditionalInformation () virtual
Retrieves the additional information of the person item from the database (none available).
Returns
0
Implements EntertainmentDB.Data.Entry.
RetrieveBasicInformation()
override int EntertainmentDB.Data.PersonItem.RetrieveBasicInformation (bool retrieveBasicInfoOnly) virtual
Retrieves the basic information of the person item from the database.
Parameters
retrieveBasicInfoOnly true if only the basic info is to be retrieved; false if also additional data is to be retrieved.
Returns
1 if data record was retrieved; 0 if no data record matched the id.
Implements EntertainmentDB.Data.Entry.
RetrieveList()
static List< PersonItem > EntertainmentDB.Data.PersonItem.RetrieveList (DBReader reader, string baseTableName, string baseTableID, string targetTableName, string order = "ID") static
Retrieves a list of person items from the database.
Parameters
reader The reader to be used to retrieve the data records.
baseTableName The base table name of the person item.
baseTableID The base table id of the person item.
targetTableName The target table name of the person item.
order The order in which the data records are to be sorted.
Returns
The list of person items.
Exceptions
ArgumentNullException Thrown when the given reader, base table name, base table id, target table name or order is null.
Referenced by EntertainmentDB.Data.AwardItem.RetrieveAdditionalInformation(), EntertainmentDB.Data.Movie.RetrieveAdditionalInformation(), and EntertainmentDB.Data.Text.RetrieveAdditionalInformation().
Member Data Documentation
Logger
NLog.Logger EntertainmentDB.Data.PersonItem.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by EntertainmentDB.Data.PersonItem.PersonItem().
Property Documentation
Person
Person EntertainmentDB.Data.PersonItem.Person get set
The person of the person item.
Referenced by EntertainmentDB.Data.CastPersonItem.RetrieveBasicInformation(), and EntertainmentDB.Data.PersonItem.RetrieveBasicInformation().
Role
string EntertainmentDB.Data.PersonItem.Role get set
The role of the person item.
Referenced by EntertainmentDB.Data.PersonItem.RetrieveBasicInformation().
The documentation for this class was generated from the following file:
C:/Users/Sandra/Projekte/GitHub/EntertainmentInfothek_public/src/EntertainmentDB/Data/PersonItem.cs