EntertainmentInfothek: EntertainmentDB.Data.CastPersonItem Class Reference
EntertainmentDB.Data.CastPersonItem Class Reference
Provides a cast person item.
Public Member Functions
CastPersonItem (DBReader reader)
Initializes a cast person item with an empty id string.
CastPersonItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes a cast person item with the given id string.
Public Member Functions inherited from EntertainmentDB.Data.PersonItem
PersonItem (DBReader reader)
Initializes a person item with an empty id string.
PersonItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes a person item with the given id string.
Public Member Functions inherited from EntertainmentDB.Data.Entry
virtual int Retrieve (bool retrieveBasicInfoOnly)
Retrieves the information of the entry from the database.
Static Public Member Functions
static new List< CastPersonItem > RetrieveList (DBReader reader, string baseTableName, string baseTableID, string targetTableName, string order="ID")
Retrieves a list of person items from the database.
Static Public Member Functions inherited from EntertainmentDB.Data.PersonItem
static List< PersonItem > RetrieveList (DBReader reader, string baseTableName, string baseTableID, string targetTableName, string order="ID")
Retrieves a list of person items from the database.
Protected Member Functions
override int RetrieveBasicInformation (bool retrieveBasicInfoOnly)
Retrieves the basic information of the person item from the database.
Protected Member Functions inherited from EntertainmentDB.Data.PersonItem
override int RetrieveBasicInformation (bool retrieveBasicInfoOnly)
Retrieves the basic information of the person item from the database.
Protected Member Functions inherited from EntertainmentDB.Data.EntryItem
EntryItem (DBReader reader)
Initializes an entry item with an emtpy id string.
EntryItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes an entry item with the given id string.
Protected Member Functions inherited from EntertainmentDB.Data.Entry
Entry (DBReader reader)
Initializes an entry with the given reader and id string.
Entry (DBReader reader, string id)
Initializes an entry with the given reader and id string.
virtual int RetrieveAdditionalInformation ()
Retrieves the additional information of the entry from the database.
Properties
Person Actor [getset]
The actor of the cast person item.
Person GermanDubber [getset]
The dubber of the cast person item.
string Character [getset]
The character of the cast person item.
Properties inherited from EntertainmentDB.Data.PersonItem
Person Person [getset]
The person of the person item.
string Role [getset]
The role of the person item.
Properties inherited from EntertainmentDB.Data.EntryItem
string BaseTableName [getset]
The base table name of the entry item.
string TargetTableName [getset]
The target table name of the entry item.
Properties inherited from EntertainmentDB.Data.Entry
DBReader Reader [getprotected set]
The database reader to be used to read the entry information from the database.
string ID [getset]
The id of the entry.
string Details [getset]
The details of the entry.
Status Status [getset]
The status of the entry.
string LastUpdated [getset]
The date of last update of the entry.
Static Private Attributes
static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides a cast person item.
Constructor & Destructor Documentation
CastPersonItem() [1/2]
EntertainmentDB.Data.CastPersonItem.CastPersonItem (DBReader reader)
Initializes a cast person item with an empty id string.
Parameters
reader The database reader to be used to read the cast person item information from the database.
Referenced by EntertainmentDB.Data.CastPersonItem.RetrieveList().
CastPersonItem() [2/2]
EntertainmentDB.Data.CastPersonItem.CastPersonItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes a cast person item with the given id string.
Parameters
reader The database reader to be used to read the cast person item information from the database.
id The id of the cast person item.
baseTableName The base table name of the cast person item.
targetTableName The target table name of the cast person item.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Member Function Documentation
RetrieveBasicInformation()
override int EntertainmentDB.Data.CastPersonItem.RetrieveBasicInformation (bool retrieveBasicInfoOnly) protected virtual
Retrieves the basic information of the person item from the database.
Parameters
retrieveBasicInfoOnly true if only the basic info is to be retrieved; false if also additional data is to be retrieved.
Returns
1 if data record was retrieved; 0 if no data record matched the id.
Implements EntertainmentDB.Data.Entry.
RetrieveList()
static new List< CastPersonItem > EntertainmentDB.Data.CastPersonItem.RetrieveList (DBReader reader, string baseTableName, string baseTableID, string targetTableName, string order = "ID") static
Retrieves a list of person items from the database.
Parameters
reader The reader to be used to retrieve the data records.
baseTableName The base table name of the person item.
baseTableID The base table id of the person item.
targetTableName The target table name of the person item.
order The order in which the data records are to be sorted.
Returns
The list of cast person items.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Referenced by EntertainmentDB.Data.Movie.RetrieveAdditionalInformation().
Member Data Documentation
Logger
readonly NLog.Logger EntertainmentDB.Data.CastPersonItem.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by EntertainmentDB.Data.CastPersonItem.CastPersonItem(), and EntertainmentDB.Data.CastPersonItem.RetrieveList().
Property Documentation
Actor
Person EntertainmentDB.Data.CastPersonItem.Actor get set
The actor of the cast person item.
Referenced by EntertainmentDB.Data.CastPersonItem.RetrieveBasicInformation().
Character
string EntertainmentDB.Data.CastPersonItem.Character get set
The character of the cast person item.
Referenced by EntertainmentDB.Data.CastPersonItem.RetrieveBasicInformation().
GermanDubber
Person EntertainmentDB.Data.CastPersonItem.GermanDubber get set
The dubber of the cast person item.
Referenced by EntertainmentDB.Data.CastPersonItem.RetrieveBasicInformation().
The documentation for this class was generated from the following file:
EntertainmentInfothek/src/EntertainmentDB/Data/CastPersonItem.cs