EntertainmentInfothek: WikiPageCreator.Export.Create.SoundMixContentCreator Class Reference
WikiPageCreator.Export.Create.SoundMixContentCreator Class Reference
Provides a content creator for a sound mix.
Public Member Functions
SoundMixContentCreator (List< SoundMixItem > soundmixes, Formatter formatter, string targetLanguageCode)
Initializes a new SoundMixContentCreator.
override List< string > CreateInfoBoxContent ()
Creates the infobox content of a given sound mix.
Public Member Functions inherited from WikiPageCreator.Export.Create.EntryContentCreator
virtual string GetPageName ()
Returns the page name of the entrys page.
virtual List< string > CreatePageContent ()
Creates the page content of the entry.
virtual List< string > CreateInfoBoxContent ()
Creates the infobox content of a given entry.
virtual List< string > CreateChapterContent ()
Creates the chapter content of a given entry.
virtual List< string > CreateSectionContent ()
Creates the section content of a given entry.
Protected Member Functions
override List< string > CreateInfoBoxContentInternal ()
Creates the infobox content of a given list of sound mixes.
Protected Member Functions inherited from WikiPageCreator.Export.Create.EntryContentCreator
EntryContentCreator (Entry entry, Formatter formatter, string targetLanguageCode)
Initializes an EntryContentCreator with the given entry, formatter and target language code.
virtual List< string > CreatePageContentInternal ()
Creates the page content of the entry.
virtual List< string > CreatePageHeader ()
Creates the formatted header content of a given entry.
virtual List< string > CreatePageTitle ()
Creates the formatted file title content of a given entry.
virtual List< string > CreateInfoBoxBegin ()
Creates the formatted infobox begin content of a given entry
virtual List< string > CreateInfoBoxContentInternal ()
Creates the infobox content of a given entry.
void CreateInfoBoxContentHelper (List< string > content, string title, string[] path, string pagename, string text, string additionalInfo)
Creates the specific row of the infobox content.
void CreateInfoBoxContentHelper (List< string > content, string title, string[] path, string pagename, Image image, int size, string additionalInfo)
virtual List< string > CreateInfoBoxEnd ()
Creates the formatted infobox end content of a given entry
virtual List< string > CreateNewChapter (Dictionary< string, string > title)
Creates a formatted chapter heading with the given title.
virtual List< string > CreateChapterContentInternal ()
Creates the chapter content of a given entry.
virtual List< string > CreateNewSection (Dictionary< string, string > title)
Creates a formatted section heading with the given title.
virtual List< string > CreateSectionContentInternal ()
Creates the section content of a given entry.
virtual List< string > CreatePageFooter ()
Creates the formatted footer content of a given entry.
Properties
List< SoundMixItem > SoundMixes [get, set]
The list of sound mix items to be used to create the content.
Properties inherited from WikiPageCreator.Export.Create.EntryContentCreator
Formatter Formatter [get, protected set]
The formatter to be used to format the information of the entry.
Entry Entry [get, protected set]
The entry to be used to create the content.
string TargetLanguageCode [get, protected set]
The target language (as a language code) to specify the language of the created content.
Static Private Attributes
static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides a content creator for a sound mix.
Constructor & Destructor Documentation
SoundMixContentCreator()
WikiPageCreator.Export.Create.SoundMixContentCreator.SoundMixContentCreator (List< SoundMixItem > soundmixes, Formatter formatter, string targetLanguageCode)
Initializes a new SoundMixContentCreator.
Parameters
soundmixes The list of sound mix items to be used to create content.
formatter The formatter to be used to format the content.
targetLanguageCode The language code for the created content.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Member Function Documentation
CreateInfoBoxContent()
override List< string > WikiPageCreator.Export.Create.SoundMixContentCreator.CreateInfoBoxContent () virtual
Creates the infobox content of a given sound mix.
Returns
The formatted content of the sound mix.
Reimplemented from WikiPageCreator.Export.Create.EntryContentCreator.
Referenced by WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator.CreateInfoBoxSoundMix().
CreateInfoBoxContentInternal()
override List< string > WikiPageCreator.Export.Create.SoundMixContentCreator.CreateInfoBoxContentInternal () protected virtual
Creates the infobox content of a given list of sound mixes.
Returns
The formatted content of the list of sound mixes.
Reimplemented from WikiPageCreator.Export.Create.EntryContentCreator.
Referenced by WikiPageCreator.Export.Create.SoundMixContentCreator.CreateInfoBoxContent().
Member Data Documentation
Logger
readonly NLog.Logger WikiPageCreator.Export.Create.SoundMixContentCreator.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by WikiPageCreator.Export.Create.SoundMixContentCreator.CreateInfoBoxContentInternal(), and WikiPageCreator.Export.Create.SoundMixContentCreator.SoundMixContentCreator().
Property Documentation
SoundMixes
List<SoundMixItem> WikiPageCreator.Export.Create.SoundMixContentCreator.SoundMixes get set
The list of sound mix items to be used to create the content.
Referenced by WikiPageCreator.Export.Create.SoundMixContentCreator.CreateInfoBoxContentInternal(), and WikiPageCreator.Export.Create.SoundMixContentCreator.SoundMixContentCreator().
The documentation for this class was generated from the following file:
EntertainmentInfothek/src/WikiPageCreator/Export/Create/SoundMixContentCreator.cs