EntertainmentInfothek: EntertainmentDB.Data.PrintedFilmFormatItem Class Reference
EntertainmentDB.Data.PrintedFilmFormatItem Class Reference
Provides a printed film format item.
Public Member Functions
PrintedFilmFormatItem (DBReader reader)
Initializes a printed film format item with an empty id string.
PrintedFilmFormatItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes a printed film format item with the given id string.
Public Member Functions inherited from EntertainmentDB.Data.Entry
virtual int Retrieve (bool retrieveBasicInfoOnly)
Retrieves the information of the entry from the database.
Static Public Member Functions
static List< PrintedFilmFormatItem > RetrieveList (DBReader reader, string baseTableName, string baseTableID, string targetTableName, string order="ID")
Retrieves a list of printed film format items from the database.
Protected Member Functions
override int RetrieveBasicInformation (bool retrieveBasicInfoOnly)
Retrieves the basic information of the printed film format item from the database.
Protected Member Functions inherited from EntertainmentDB.Data.EntryItem
EntryItem (DBReader reader)
Initializes an entry item with an emtpy id string.
EntryItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes an entry item with the given id string.
Protected Member Functions inherited from EntertainmentDB.Data.Entry
Entry (DBReader reader)
Initializes an entry with the given reader and id string.
Entry (DBReader reader, string id)
Initializes an entry with the given reader and id string.
virtual int RetrieveAdditionalInformation ()
Retrieves the additional information of the entry from the database.
Properties
FilmFormat FilmFormat [getset]
The film format of the printed film format item.
Properties inherited from EntertainmentDB.Data.EntryItem
string BaseTableName [getset]
The base table name of the entry item.
string TargetTableName [getset]
The target table name of the entry item.
Properties inherited from EntertainmentDB.Data.Entry
DBReader Reader [getprotected set]
The database reader to be used to read the entry information from the database.
string ID [getset]
The id of the entry.
string Details [getset]
The details of the entry.
Status Status [getset]
The status of the entry.
string LastUpdated [getset]
The date of last update of the entry.
Static Private Attributes
static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides a printed film format item.
Constructor & Destructor Documentation
PrintedFilmFormatItem() [1/2]
EntertainmentDB.Data.PrintedFilmFormatItem.PrintedFilmFormatItem (DBReader reader)
Initializes a printed film format item with an empty id string.
Parameters
reader The database reader to be used to read the printed film format item information from the database.
Referenced by EntertainmentDB.Data.PrintedFilmFormatItem.RetrieveList().
PrintedFilmFormatItem() [2/2]
EntertainmentDB.Data.PrintedFilmFormatItem.PrintedFilmFormatItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes a printed film format item with the given id string.
Parameters
reader The database reader to be used to read the printed film format item information from the database.
id The id of the printed film format item.
baseTableName The base table name of the printed film format item.
targetTableName The target table name of the printed film format item.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Member Function Documentation
RetrieveBasicInformation()
override int EntertainmentDB.Data.PrintedFilmFormatItem.RetrieveBasicInformation (bool retrieveBasicInfoOnly) protected virtual
Retrieves the basic information of the printed film format item from the database.
Parameters
retrieveBasicInfoOnly true if only the basic info is to be retrieved; false if also additional data is to be retrieved.
Returns
1 if data record was retrieved; 0 if no data record matched the id.
Implements EntertainmentDB.Data.Entry.
RetrieveList()
static List< PrintedFilmFormatItem > EntertainmentDB.Data.PrintedFilmFormatItem.RetrieveList (DBReader reader, string baseTableName, string baseTableID, string targetTableName, string order = "ID") static
Retrieves a list of printed film format items from the database.
Parameters
reader The reader to be used to retrieve the data records.
baseTableName The base table name of the printed film format item.
baseTableID The base table id of the printed film format item.
targetTableName The target table name of the printed film format item.
order The order in which the data records are to be sorted.
Returns
The list of printed film format items.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Referenced by EntertainmentDB.Data.Movie.RetrieveAdditionalInformation().
Member Data Documentation
Logger
readonly NLog.Logger EntertainmentDB.Data.PrintedFilmFormatItem.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by EntertainmentDB.Data.PrintedFilmFormatItem.PrintedFilmFormatItem(), and EntertainmentDB.Data.PrintedFilmFormatItem.RetrieveList().
Property Documentation
FilmFormat
FilmFormat EntertainmentDB.Data.PrintedFilmFormatItem.FilmFormat get set
The film format of the printed film format item.
Referenced by EntertainmentDB.Data.PrintedFilmFormatItem.RetrieveBasicInformation().
The documentation for this class was generated from the following file:
EntertainmentInfothek/src/EntertainmentDB/Data/PrintedFilmFormatItem.cs