EntertainmentInfothek: WikiPageCreator.Export.Create.ConnectionContentCreator Class Reference
WikiPageCreator.Export.Create.ConnectionContentCreator Class Reference
Provides a content creator for a connection.
Public Member Functions
ConnectionContentCreator (Connection connection, Formatter formatter, string targetLanguageCode)
Initializes a new ConnectionContentCreator.
override string GetPageName ()
Returns the page name of the types page.
override List< string > CreatePageContent ()
Creates the page content of the type.
override List< string > CreateInfoBoxContent ()
Creates the infobox content of a given type.
override List< string > CreateChapterContent ()
Creates the chapter content of a given type.
override List< string > CreateSectionContent ()
Creates the section content of a given type.
Protected Member Functions
override List< string > CreatePageHeader ()
Creates the formatted header content of a given type.
override List< string > CreatePageTitle ()
Creates the formatted file title content of a given type.
Protected Member Functions inherited from WikiPageCreator.Export.Create.EntryContentCreator
EntryContentCreator (Entry entry, Formatter formatter, string targetLanguageCode)
Initializes an EntryContentCreator with the given entry, formatter and target language code.
virtual List< string > CreateInfoBoxBegin ()
Creates the formatted infobox begin content of a given entry
virtual List< string > CreateInfoBoxEnd ()
Creates the formatted infobox end content of a given entry
virtual List< string > CreateNewChapter (Dictionary< string, string > title)
Creates a formatted chapter heading with the given title.
virtual List< string > CreateNewSection (Dictionary< string, string > title)
Creates a formatted section heading with the given title.
virtual List< string > CreatePageFooter ()
Creates the formatted footer content of a given entry.
Properties
Connection Connection [getset]
The connection to be used to create the content.
Properties inherited from WikiPageCreator.Export.Create.EntryContentCreator
Formatter Formatter [getprotected set]
The formatter to be used to format the information of the entry.
Entry Entry [getprotected set]
The entry to be used to create the content.
string TargetLanguageCode [getprotected set]
The target language (as a language code) to specify the language of the created content.
Static Private Attributes
static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides a content creator for a connection.
Constructor & Destructor Documentation
ConnectionContentCreator()
WikiPageCreator.Export.Create.ConnectionContentCreator.ConnectionContentCreator (Connection connection, Formatter formatter, string targetLanguageCode)
Initializes a new ConnectionContentCreator.
Parameters
connection The connection to be used to create content.
formatter The formatter to be used to format the content
targetLanguageCode The language code for the created content.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Member Function Documentation
CreateChapterContent()
override List< string > WikiPageCreator.Export.Create.ConnectionContentCreator.CreateChapterContent () virtual
Creates the chapter content of a given type.
Returns
The formatted content of the type.
Implements WikiPageCreator.Export.Create.EntryContentCreator.
Referenced by WikiPageCreator.Export.Create.ArticleContentCreator.CreateChapterConnection(), and WikiPageCreator.Export.Create.ConnectionContentCreator.CreateSectionContent().
CreateInfoBoxContent()
override List< string > WikiPageCreator.Export.Create.ConnectionContentCreator.CreateInfoBoxContent () virtual
Creates the infobox content of a given type.
Returns
The formatted content of the type.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Implements WikiPageCreator.Export.Create.EntryContentCreator.
CreatePageContent()
override List< string > WikiPageCreator.Export.Create.ConnectionContentCreator.CreatePageContent () virtual
Creates the page content of the type.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Reimplemented from WikiPageCreator.Export.Create.EntryContentCreator.
CreatePageHeader()
override List< string > WikiPageCreator.Export.Create.ConnectionContentCreator.CreatePageHeader () protected virtual
Creates the formatted header content of a given type.
Returns
The formatted header content of the type.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Implements WikiPageCreator.Export.Create.EntryContentCreator.
CreatePageTitle()
override List< string > WikiPageCreator.Export.Create.ConnectionContentCreator.CreatePageTitle () protected virtual
Creates the formatted file title content of a given type.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Implements WikiPageCreator.Export.Create.EntryContentCreator.
CreateSectionContent()
override List< string > WikiPageCreator.Export.Create.ConnectionContentCreator.CreateSectionContent () virtual
Creates the section content of a given type.
Returns
The formatted section content of the type.
Implements WikiPageCreator.Export.Create.EntryContentCreator.
GetPageName()
override string WikiPageCreator.Export.Create.ConnectionContentCreator.GetPageName () virtual
Returns the page name of the types page.
Returns
The formatted page name for the type.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Implements WikiPageCreator.Export.Create.EntryContentCreator.
Member Data Documentation
Logger
readonly NLog.Logger WikiPageCreator.Export.Create.ConnectionContentCreator.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by WikiPageCreator.Export.Create.ConnectionContentCreator.ConnectionContentCreator(), and WikiPageCreator.Export.Create.ConnectionContentCreator.CreateChapterContent().
Property Documentation
Connection
Connection WikiPageCreator.Export.Create.ConnectionContentCreator.Connection get set
The connection to be used to create the content.
The documentation for this class was generated from the following file:
C:/Users/Sandra/Projekte/GitHub/EntertainmentInfothek_public/src/WikiPageCreator/Export/Create/ConnectionContentCreator.cs