EntertainmentInfothek: WikiPageCreator.Export.Write.FileWriter Class Reference
WikiPageCreator.Export.Write.FileWriter Class Reference
Provides a file writer.
Public Member Functions
FileWriter ()
Initializes a new file writer.
void WriteToFile (string directory, string filename, List< string > content)
Static Private Attributes
static NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides a file writer.
Constructor & Destructor Documentation
FileWriter()
WikiPageCreator.Export.Write.FileWriter.FileWriter ()
Initializes a new file writer.
Member Function Documentation
WriteToFile()
void WikiPageCreator.Export.Write.FileWriter.WriteToFile (string directory, string filename, List< string > content)
Referenced by WikiPageCreator.Program.CreateMoviePage(), and WikiPageCreator.Program.CreateSeriesPage().
Member Data Documentation
Logger
NLog.Logger WikiPageCreator.Export.Write.FileWriter.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by WikiPageCreator.Export.Write.FileWriter.FileWriter(), and WikiPageCreator.Export.Write.FileWriter.WriteToFile().
The documentation for this class was generated from the following file:
C:/Users/Sandra/Projekte/GitHub/EntertainmentInfothek_public/src/WikiPageCreator/Export/Write/FileWriter.cs