EntertainmentInfothek: EntertainmentDB.Data.LanguageItem Class Reference
EntertainmentDB.Data.LanguageItem Class Reference
Provides a language item.
Public Member Functions
LanguageItem ()
Initializes a language item with an empty id string.
LanguageItem (string id, string targetTableName)
Initializes a language item with the given id string.
override int RetrieveBasicInformation (bool retrieveBasicInfoOnly)
Retrieves the basic information of the language item from the database.
override int RetrieveAdditionalInformation ()
Retrieves the additional information of the language item from the database (none available).
Public Member Functions inherited from EntertainmentDB.Data.Entry
virtual int Retrieve (bool retrieveBasicInfoOnly)
Retrieves the information of the entry from the database.
Static Public Member Functions
static List< LanguageItem > RetrieveList (DBReader reader, string baseTableName, string baseTableID, string targetTableName, string order="ID")
Retrieves a list of language items from the database.
Properties
Language Language [getset]
The language of the language item.
Properties inherited from EntertainmentDB.Data.EntryItem
string BaseTableName [getset]
The base table name of the entry.
string TargetTableName [getset]
The target table name of the entry.
Properties inherited from EntertainmentDB.Data.Entry
DBReader Reader = new SQLiteReader() [getprotected set]
The database reader to be used to read the entry information from the database.
string ID [getset]
The id of the entry.
string Details [getset]
The details of the entry.
Status Status [getset]
The status of the entry.
string LastUpdated [getset]
The date of last update of the entry.
Static Private Attributes
static NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Additional Inherited Members
Protected Member Functions inherited from EntertainmentDB.Data.EntryItem
EntryItem ()
Initializes an entry item with an emtpy id string.
EntryItem (string id, string targetTableName)
Initializes an entry item with the given id string.
Protected Member Functions inherited from EntertainmentDB.Data.Entry
Entry ()
Initializes an entry with an empty id string.
Entry (string id)
Initializes an entry with the given id string.
Detailed Description
Provides a language item.
Constructor & Destructor Documentation
LanguageItem() [1/2]
EntertainmentDB.Data.LanguageItem.LanguageItem ()
Initializes a language item with an empty id string.
Referenced by EntertainmentDB.Data.LanguageItem.RetrieveList().
LanguageItem() [2/2]
EntertainmentDB.Data.LanguageItem.LanguageItem (string id, string targetTableName)
Initializes a language item with the given id string.
Parameters
id The id of the language item.
targetTableName The target table name of the language item.
Exceptions
ArgumentNullException Thrown when the given id or target table name is null.
Member Function Documentation
RetrieveAdditionalInformation()
override int EntertainmentDB.Data.LanguageItem.RetrieveAdditionalInformation () virtual
Retrieves the additional information of the language item from the database (none available).
Returns
0
Implements EntertainmentDB.Data.Entry.
RetrieveBasicInformation()
override int EntertainmentDB.Data.LanguageItem.RetrieveBasicInformation (bool retrieveBasicInfoOnly) virtual
Retrieves the basic information of the language item from the database.
Parameters
retrieveBasicInfoOnly true if only the basic info is to be retrieved; false if also additional data is to be retrieved.
Returns
1 if data record was retrieved; 0 if no data record matched the id.
Implements EntertainmentDB.Data.Entry.
RetrieveList()
static List< LanguageItem > EntertainmentDB.Data.LanguageItem.RetrieveList (DBReader reader, string baseTableName, string baseTableID, string targetTableName, string order = "ID") static
Retrieves a list of language items from the database.
Parameters
reader The reader to be used to retrieve the data records.
baseTableName The base table name of the language item.
baseTableID The base table id of the language item.
targetTableName The target table name of the language item.
order The order in which the data records are to be sorted.
Returns
The list of language items.
Exceptions
ArgumentNullException Thrown when the given reader, base table name, base table id, target table name or order is null.
Referenced by EntertainmentDB.Data.Movie.RetrieveAdditionalInformation().
Member Data Documentation
Logger
NLog.Logger EntertainmentDB.Data.LanguageItem.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by EntertainmentDB.Data.LanguageItem.LanguageItem().
Property Documentation
Language
Language EntertainmentDB.Data.LanguageItem.Language get set
The language of the language item.
Referenced by EntertainmentDB.Data.LanguageItem.RetrieveBasicInformation().
The documentation for this class was generated from the following file:
C:/Users/Sandra/Projekte/GitHub/EntertainmentInfothek_public/src/EntertainmentDB/Data/LanguageItem.cs