EntertainmentInfothek: EntertainmentDB.Data.AwardItem Class Reference
EntertainmentDB.Data.AwardItem Class Reference
Provides an award item.
Public Member Functions
AwardItem (DBReader reader)
Initializes an award item with an empty id string.
AwardItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes an award item with the given id string.
Public Member Functions inherited from EntertainmentDB.Data.Entry
virtual int Retrieve (bool retrieveBasicInfoOnly)
Retrieves the information of the entry from the database.
Static Public Member Functions
static List< AwardItem > RetrieveList (DBReader reader, string baseTableName, string baseTableID, string targetTableName, string order="ID")
Retrieves a list of award items from the database.
Protected Member Functions
override int RetrieveBasicInformation (bool retrieveBasicInfoOnly)
Retrieves the basic information of the award item from the database.
override int RetrieveAdditionalInformation ()
Retrieves the additional information of the award item from the database.
Protected Member Functions inherited from EntertainmentDB.Data.EntryItem
EntryItem (DBReader reader)
Initializes an entry item with an emtpy id string.
EntryItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes an entry item with the given id string.
Protected Member Functions inherited from EntertainmentDB.Data.Entry
Entry (DBReader reader)
Initializes an entry with the given reader and id string.
Entry (DBReader reader, string id)
Initializes an entry with the given reader and id string.
Properties
Award Award [getset]
The award of the award item.
string Category [getset]
The category of the award item.
string Date [getset]
The date of the award item.
string Winner [getset]
The winner info of the award item.
List< PersonItem > Persons [getset]
The list of persons of the award item.
Properties inherited from EntertainmentDB.Data.EntryItem
string BaseTableName [getset]
The base table name of the entry item.
string TargetTableName [getset]
The target table name of the entry item.
Properties inherited from EntertainmentDB.Data.Entry
DBReader Reader [getprotected set]
The database reader to be used to read the entry information from the database.
string ID [getset]
The id of the entry.
string Details [getset]
The details of the entry.
Status Status [getset]
The status of the entry.
string LastUpdated [getset]
The date of last update of the entry.
Static Private Attributes
static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides an award item.
Constructor & Destructor Documentation
AwardItem() [1/2]
EntertainmentDB.Data.AwardItem.AwardItem (DBReader reader)
Initializes an award item with an empty id string.
Parameters
reader The database reader to be used to read the award item information from the database.
Referenced by EntertainmentDB.Data.AwardItem.RetrieveList().
AwardItem() [2/2]
EntertainmentDB.Data.AwardItem.AwardItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes an award item with the given id string.
Parameters
reader The database reader to be used to read the award item information from the database.
id The id of the award item.
baseTableName The base table name of the aspect ratio item.
targetTableName The target table name of the award item.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Member Function Documentation
RetrieveAdditionalInformation()
override int EntertainmentDB.Data.AwardItem.RetrieveAdditionalInformation () protected virtual
Retrieves the additional information of the award item from the database.
Returns
The number of data records retrieved.
Reimplemented from EntertainmentDB.Data.Entry.
RetrieveBasicInformation()
override int EntertainmentDB.Data.AwardItem.RetrieveBasicInformation (bool retrieveBasicInfoOnly) protected virtual
Retrieves the basic information of the award item from the database.
Parameters
retrieveBasicInfoOnly true if only the basic info is to be retrieved; false if also additional data is to be retrieved.
Returns
1 if data record was retrieved; 0 if no data record matched the id.
Implements EntertainmentDB.Data.Entry.
RetrieveList()
static List< AwardItem > EntertainmentDB.Data.AwardItem.RetrieveList (DBReader reader, string baseTableName, string baseTableID, string targetTableName, string order = "ID") static
Retrieves a list of award items from the database.
Parameters
reader The reader to be used to retrieve the data records.
baseTableName The base table name of the aspect ratio item.
baseTableID The base table id of the award item.
targetTableName The target table name of the award item.
order The order in which the data records are to be sorted.
Returns
The list of award items.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Referenced by EntertainmentDB.Data.Movie.RetrieveAdditionalInformation().
Member Data Documentation
Logger
readonly NLog.Logger EntertainmentDB.Data.AwardItem.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by EntertainmentDB.Data.AwardItem.AwardItem(), EntertainmentDB.Data.AwardItem.RetrieveAdditionalInformation(), EntertainmentDB.Data.AwardItem.RetrieveBasicInformation(), and EntertainmentDB.Data.AwardItem.RetrieveList().
Property Documentation
Award
Award EntertainmentDB.Data.AwardItem.Award get set
The award of the award item.
Referenced by EntertainmentDB.Data.AwardItem.RetrieveBasicInformation().
Category
string EntertainmentDB.Data.AwardItem.Category get set
The category of the award item.
Referenced by EntertainmentDB.Data.AwardItem.RetrieveBasicInformation().
Date
string EntertainmentDB.Data.AwardItem.Date get set
The date of the award item.
Referenced by EntertainmentDB.Data.AwardItem.RetrieveBasicInformation().
Persons
List<PersonItem> EntertainmentDB.Data.AwardItem.Persons get set
The list of persons of the award item.
Referenced by EntertainmentDB.Data.AwardItem.RetrieveAdditionalInformation().
Winner
string EntertainmentDB.Data.AwardItem.Winner get set
The winner info of the award item.
Referenced by EntertainmentDB.Data.AwardItem.RetrieveBasicInformation().
The documentation for this class was generated from the following file:
EntertainmentInfothek_public/src/EntertainmentDB/Data/AwardItem.cs