using DocuWikiExporter.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace DocuWikiExporter.Infrastructure.Persistence;

/// <summary>
/// Read-only EF-Core-Kontext für die bestehende EntertainmentInfothek-SQLite-Datenbank.
/// Es werden keine Migrationen benötigt oder ausgeführt.
/// </summary>
public sealed class AppDbContext : DbContext
{
    public DbSet<AspectRatio> AspectRatios => Set<AspectRatio>();
    public DbSet<Award> Awards => Set<Award>();
    public DbSet<Camera> Cameras => Set<Camera>();
    public DbSet<Certification> Certifications => Set<Certification>();
    public DbSet<CinematographicProcess> CinematographicProcesses => Set<CinematographicProcess>();
    public DbSet<Color> Colors => Set<Color>();
    public DbSet<Company> Companys => Set<Company>();
    public DbSet<Connection> Connections => Set<Connection>();
    public DbSet<Country> Countrys => Set<Country>();
    public DbSet<Edition> Editions => Set<Edition>();
    public DbSet<Episode> Episodes => Set<Episode>();
    public DbSet<EpisodeAnimationDepartment> EpisodeAnimationDepartments => Set<EpisodeAnimationDepartment>();
    public DbSet<EpisodeArtDepartment> EpisodeArtDepartments => Set<EpisodeArtDepartment>();
    public DbSet<EpisodeArtDirection> EpisodeArtDirections => Set<EpisodeArtDirection>();
    public DbSet<EpisodeAssistantDirector> EpisodeAssistantDirectors => Set<EpisodeAssistantDirector>();
    public DbSet<EpisodeAward> EpisodeAwards => Set<EpisodeAward>();
    public DbSet<EpisodeAwardPerson> EpisodeAwardPersons => Set<EpisodeAwardPerson>();
    public DbSet<EpisodeCast> EpisodeCasts => Set<EpisodeCast>();
    public DbSet<EpisodeCasting> EpisodeCastings => Set<EpisodeCasting>();
    public DbSet<EpisodeCastingDepartment> EpisodeCastingDepartments => Set<EpisodeCastingDepartment>();
    public DbSet<EpisodeCinematography> EpisodeCinematographys => Set<EpisodeCinematography>();
    public DbSet<EpisodeContinuityDepartment> EpisodeContinuityDepartments => Set<EpisodeContinuityDepartment>();
    public DbSet<EpisodeCostumeDepartment> EpisodeCostumeDepartments => Set<EpisodeCostumeDepartment>();
    public DbSet<EpisodeCostumeDesign> EpisodeCostumeDesigns => Set<EpisodeCostumeDesign>();
    public DbSet<EpisodeDescription> EpisodeDescriptions => Set<EpisodeDescription>();
    public DbSet<EpisodeDirector> EpisodeDirectors => Set<EpisodeDirector>();
    public DbSet<EpisodeDistributor> EpisodeDistributors => Set<EpisodeDistributor>();
    public DbSet<EpisodeEditorialDepartment> EpisodeEditorialDepartments => Set<EpisodeEditorialDepartment>();
    public DbSet<EpisodeElectricalDepartment> EpisodeElectricalDepartments => Set<EpisodeElectricalDepartment>();
    public DbSet<EpisodeFilmEditing> EpisodeFilmEditings => Set<EpisodeFilmEditing>();
    public DbSet<EpisodeFilmingDate> EpisodeFilmingDates => Set<EpisodeFilmingDate>();
    public DbSet<EpisodeFilmingLocation> EpisodeFilmingLocations => Set<EpisodeFilmingLocation>();
    public DbSet<EpisodeImage> EpisodeImages => Set<EpisodeImage>();
    public DbSet<EpisodeLocationManagement> EpisodeLocationManagements => Set<EpisodeLocationManagement>();
    public DbSet<EpisodeMakeupDepartment> EpisodeMakeupDepartments => Set<EpisodeMakeupDepartment>();
    public DbSet<EpisodeMusic> EpisodeMusics => Set<EpisodeMusic>();
    public DbSet<EpisodeMusicDepartment> EpisodeMusicDepartments => Set<EpisodeMusicDepartment>();
    public DbSet<EpisodeOtherCompany> EpisodeOtherCompanys => Set<EpisodeOtherCompany>();
    public DbSet<EpisodeOtherCrew> EpisodeOtherCrews => Set<EpisodeOtherCrew>();
    public DbSet<EpisodeProducer> EpisodeProducers => Set<EpisodeProducer>();
    public DbSet<EpisodeProductionCompany> EpisodeProductionCompanys => Set<EpisodeProductionCompany>();
    public DbSet<EpisodeProductionDate> EpisodeProductionDates => Set<EpisodeProductionDate>();
    public DbSet<EpisodeProductionDesign> EpisodeProductionDesigns => Set<EpisodeProductionDesign>();
    public DbSet<EpisodeProductionManagement> EpisodeProductionManagements => Set<EpisodeProductionManagement>();
    public DbSet<EpisodeReview> EpisodeReviews => Set<EpisodeReview>();
    public DbSet<EpisodeSetDecoration> EpisodeSetDecorations => Set<EpisodeSetDecoration>();
    public DbSet<EpisodeSoundDepartment> EpisodeSoundDepartments => Set<EpisodeSoundDepartment>();
    public DbSet<EpisodeSpecialEffects> EpisodeSpecialEffectses => Set<EpisodeSpecialEffects>();
    public DbSet<EpisodeSpecialEffectsCompany> EpisodeSpecialEffectsCompanys => Set<EpisodeSpecialEffectsCompany>();
    public DbSet<EpisodeStunts> EpisodeStuntses => Set<EpisodeStunts>();
    public DbSet<EpisodeThanks> EpisodeThankses => Set<EpisodeThanks>();
    public DbSet<EpisodeTransportationDepartment> EpisodeTransportationDepartments => Set<EpisodeTransportationDepartment>();
    public DbSet<EpisodeVisualEffects> EpisodeVisualEffectses => Set<EpisodeVisualEffects>();
    public DbSet<EpisodeWriter> EpisodeWriters => Set<EpisodeWriter>();
    public DbSet<FilmFormat> FilmFormats => Set<FilmFormat>();
    public DbSet<Genre> Genres => Set<Genre>();
    public DbSet<Image> Images => Set<Image>();
    public DbSet<Laboratory> Laboratorys => Set<Laboratory>();
    public DbSet<Language> Languages => Set<Language>();
    public DbSet<Location> Locations => Set<Location>();
    public DbSet<Movie> Movies => Set<Movie>();
    public DbSet<MovieAnimationDepartment> MovieAnimationDepartments => Set<MovieAnimationDepartment>();
    public DbSet<MovieArtDepartment> MovieArtDepartments => Set<MovieArtDepartment>();
    public DbSet<MovieArtDirection> MovieArtDirections => Set<MovieArtDirection>();
    public DbSet<MovieAspectRatio> MovieAspectRatios => Set<MovieAspectRatio>();
    public DbSet<MovieAssistantDirector> MovieAssistantDirectors => Set<MovieAssistantDirector>();
    public DbSet<MovieAward> MovieAwards => Set<MovieAward>();
    public DbSet<MovieAwardPerson> MovieAwardPersons => Set<MovieAwardPerson>();
    public DbSet<MovieCamera> MovieCameras => Set<MovieCamera>();
    public DbSet<MovieCast> MovieCasts => Set<MovieCast>();
    public DbSet<MovieCasting> MovieCastings => Set<MovieCasting>();
    public DbSet<MovieCastingDepartment> MovieCastingDepartments => Set<MovieCastingDepartment>();
    public DbSet<MovieCertification> MovieCertifications => Set<MovieCertification>();
    public DbSet<MovieCinematographicProcess> MovieCinematographicProcesses => Set<MovieCinematographicProcess>();
    public DbSet<MovieCinematography> MovieCinematographys => Set<MovieCinematography>();
    public DbSet<MovieColor> MovieColors => Set<MovieColor>();
    public DbSet<MovieContinuityDepartment> MovieContinuityDepartments => Set<MovieContinuityDepartment>();
    public DbSet<MovieCostumeDepartment> MovieCostumeDepartments => Set<MovieCostumeDepartment>();
    public DbSet<MovieCostumeDesign> MovieCostumeDesigns => Set<MovieCostumeDesign>();
    public DbSet<MovieCountry> MovieCountrys => Set<MovieCountry>();
    public DbSet<MovieCover> MovieCovers => Set<MovieCover>();
    public DbSet<MovieDescription> MovieDescriptions => Set<MovieDescription>();
    public DbSet<MovieDirector> MovieDirectors => Set<MovieDirector>();
    public DbSet<MovieDistributor> MovieDistributors => Set<MovieDistributor>();
    public DbSet<MovieEditorialDepartment> MovieEditorialDepartments => Set<MovieEditorialDepartment>();
    public DbSet<MovieElectricalDepartment> MovieElectricalDepartments => Set<MovieElectricalDepartment>();
    public DbSet<MovieFilmEditing> MovieFilmEditings => Set<MovieFilmEditing>();
    public DbSet<MovieFilmLength> MovieFilmLengths => Set<MovieFilmLength>();
    public DbSet<MovieFilmingDate> MovieFilmingDates => Set<MovieFilmingDate>();
    public DbSet<MovieFilmingLocation> MovieFilmingLocations => Set<MovieFilmingLocation>();
    public DbSet<MovieGenre> MovieGenres => Set<MovieGenre>();
    public DbSet<MovieImage> MovieImages => Set<MovieImage>();
    public DbSet<MovieLaboratory> MovieLaboratorys => Set<MovieLaboratory>();
    public DbSet<MovieLanguage> MovieLanguages => Set<MovieLanguage>();
    public DbSet<MovieLocationManagement> MovieLocationManagements => Set<MovieLocationManagement>();
    public DbSet<MovieMakeupDepartment> MovieMakeupDepartments => Set<MovieMakeupDepartment>();
    public DbSet<MovieMusic> MovieMusics => Set<MovieMusic>();
    public DbSet<MovieMusicDepartment> MovieMusicDepartments => Set<MovieMusicDepartment>();
    public DbSet<MovieNegativeFormat> MovieNegativeFormats => Set<MovieNegativeFormat>();
    public DbSet<MovieOtherCompany> MovieOtherCompanys => Set<MovieOtherCompany>();
    public DbSet<MovieOtherCrew> MovieOtherCrews => Set<MovieOtherCrew>();
    public DbSet<MoviePoster> MoviePosters => Set<MoviePoster>();
    public DbSet<MoviePrintedFilmFormat> MoviePrintedFilmFormats => Set<MoviePrintedFilmFormat>();
    public DbSet<MovieProducer> MovieProducers => Set<MovieProducer>();
    public DbSet<MovieProductionCompany> MovieProductionCompanys => Set<MovieProductionCompany>();
    public DbSet<MovieProductionDate> MovieProductionDates => Set<MovieProductionDate>();
    public DbSet<MovieProductionDesign> MovieProductionDesigns => Set<MovieProductionDesign>();
    public DbSet<MovieProductionManagement> MovieProductionManagements => Set<MovieProductionManagement>();
    public DbSet<MovieReview> MovieReviews => Set<MovieReview>();
    public DbSet<MovieRuntime> MovieRuntimes => Set<MovieRuntime>();
    public DbSet<MovieSetDecoration> MovieSetDecorations => Set<MovieSetDecoration>();
    public DbSet<MovieSoundDepartment> MovieSoundDepartments => Set<MovieSoundDepartment>();
    public DbSet<MovieSoundMix> MovieSoundMixs => Set<MovieSoundMix>();
    public DbSet<MovieSpecialEffects> MovieSpecialEffectses => Set<MovieSpecialEffects>();
    public DbSet<MovieSpecialEffectsCompany> MovieSpecialEffectsCompanys => Set<MovieSpecialEffectsCompany>();
    public DbSet<MovieStunts> MovieStuntses => Set<MovieStunts>();
    public DbSet<MovieThanks> MovieThankses => Set<MovieThanks>();
    public DbSet<MovieTransportationDepartment> MovieTransportationDepartments => Set<MovieTransportationDepartment>();
    public DbSet<MovieUser> MovieUsers => Set<MovieUser>();
    public DbSet<MovieVisualEffects> MovieVisualEffectses => Set<MovieVisualEffects>();
    public DbSet<MovieWeblink> MovieWeblinks => Set<MovieWeblink>();
    public DbSet<MovieWriter> MovieWriters => Set<MovieWriter>();
    public DbSet<Person> Persons => Set<Person>();
    public DbSet<Priority> Prioritys => Set<Priority>();
    public DbSet<Series> Serieses => Set<Series>();
    public DbSet<SeriesAnimationDepartment> SeriesAnimationDepartments => Set<SeriesAnimationDepartment>();
    public DbSet<SeriesArtDepartment> SeriesArtDepartments => Set<SeriesArtDepartment>();
    public DbSet<SeriesArtDirection> SeriesArtDirections => Set<SeriesArtDirection>();
    public DbSet<SeriesAspectRatio> SeriesAspectRatios => Set<SeriesAspectRatio>();
    public DbSet<SeriesAssistantDirector> SeriesAssistantDirectors => Set<SeriesAssistantDirector>();
    public DbSet<SeriesAward> SeriesAwards => Set<SeriesAward>();
    public DbSet<SeriesAwardPerson> SeriesAwardPersons => Set<SeriesAwardPerson>();
    public DbSet<SeriesCamera> SeriesCameras => Set<SeriesCamera>();
    public DbSet<SeriesCast> SeriesCasts => Set<SeriesCast>();
    public DbSet<SeriesCasting> SeriesCastings => Set<SeriesCasting>();
    public DbSet<SeriesCastingDepartment> SeriesCastingDepartments => Set<SeriesCastingDepartment>();
    public DbSet<SeriesCertification> SeriesCertifications => Set<SeriesCertification>();
    public DbSet<SeriesCinematographicProcess> SeriesCinematographicProcesses => Set<SeriesCinematographicProcess>();
    public DbSet<SeriesCinematography> SeriesCinematographys => Set<SeriesCinematography>();
    public DbSet<SeriesColor> SeriesColors => Set<SeriesColor>();
    public DbSet<SeriesContinuityDepartment> SeriesContinuityDepartments => Set<SeriesContinuityDepartment>();
    public DbSet<SeriesCostumeDepartment> SeriesCostumeDepartments => Set<SeriesCostumeDepartment>();
    public DbSet<SeriesCostumeDesign> SeriesCostumeDesigns => Set<SeriesCostumeDesign>();
    public DbSet<SeriesCountry> SeriesCountrys => Set<SeriesCountry>();
    public DbSet<SeriesCover> SeriesCovers => Set<SeriesCover>();
    public DbSet<SeriesCreator> SeriesCreators => Set<SeriesCreator>();
    public DbSet<SeriesDescription> SeriesDescriptions => Set<SeriesDescription>();
    public DbSet<SeriesDirector> SeriesDirectors => Set<SeriesDirector>();
    public DbSet<SeriesDistributor> SeriesDistributors => Set<SeriesDistributor>();
    public DbSet<SeriesEditorialDepartment> SeriesEditorialDepartments => Set<SeriesEditorialDepartment>();
    public DbSet<SeriesElectricalDepartment> SeriesElectricalDepartments => Set<SeriesElectricalDepartment>();
    public DbSet<SeriesFilmEditing> SeriesFilmEditings => Set<SeriesFilmEditing>();
    public DbSet<SeriesFilmLength> SeriesFilmLengths => Set<SeriesFilmLength>();
    public DbSet<SeriesFilmingDate> SeriesFilmingDates => Set<SeriesFilmingDate>();
    public DbSet<SeriesFilmingLocation> SeriesFilmingLocations => Set<SeriesFilmingLocation>();
    public DbSet<SeriesGenre> SeriesGenres => Set<SeriesGenre>();
    public DbSet<SeriesImage> SeriesImages => Set<SeriesImage>();
    public DbSet<SeriesLaboratory> SeriesLaboratorys => Set<SeriesLaboratory>();
    public DbSet<SeriesLanguage> SeriesLanguages => Set<SeriesLanguage>();
    public DbSet<SeriesLocationManagement> SeriesLocationManagements => Set<SeriesLocationManagement>();
    public DbSet<SeriesLogo> SeriesLogos => Set<SeriesLogo>();
    public DbSet<SeriesMakeupDepartment> SeriesMakeupDepartments => Set<SeriesMakeupDepartment>();
    public DbSet<SeriesMusic> SeriesMusics => Set<SeriesMusic>();
    public DbSet<SeriesMusicDepartment> SeriesMusicDepartments => Set<SeriesMusicDepartment>();
    public DbSet<SeriesNegativeFormat> SeriesNegativeFormats => Set<SeriesNegativeFormat>();
    public DbSet<SeriesOtherCompany> SeriesOtherCompanys => Set<SeriesOtherCompany>();
    public DbSet<SeriesOtherCrew> SeriesOtherCrews => Set<SeriesOtherCrew>();
    public DbSet<SeriesPoster> SeriesPosters => Set<SeriesPoster>();
    public DbSet<SeriesPrintedFilmFormat> SeriesPrintedFilmFormats => Set<SeriesPrintedFilmFormat>();
    public DbSet<SeriesProducer> SeriesProducers => Set<SeriesProducer>();
    public DbSet<SeriesProductionCompany> SeriesProductionCompanys => Set<SeriesProductionCompany>();
    public DbSet<SeriesProductionDate> SeriesProductionDates => Set<SeriesProductionDate>();
    public DbSet<SeriesProductionDesign> SeriesProductionDesigns => Set<SeriesProductionDesign>();
    public DbSet<SeriesProductionManagement> SeriesProductionManagements => Set<SeriesProductionManagement>();
    public DbSet<SeriesReview> SeriesReviews => Set<SeriesReview>();
    public DbSet<SeriesRuntime> SeriesRuntimes => Set<SeriesRuntime>();
    public DbSet<SeriesSetDecoration> SeriesSetDecorations => Set<SeriesSetDecoration>();
    public DbSet<SeriesSoundDepartment> SeriesSoundDepartments => Set<SeriesSoundDepartment>();
    public DbSet<SeriesSoundMix> SeriesSoundMixs => Set<SeriesSoundMix>();
    public DbSet<SeriesSpecialEffects> SeriesSpecialEffectses => Set<SeriesSpecialEffects>();
    public DbSet<SeriesSpecialEffectsCompany> SeriesSpecialEffectsCompanys => Set<SeriesSpecialEffectsCompany>();
    public DbSet<SeriesStunts> SeriesStuntses => Set<SeriesStunts>();
    public DbSet<SeriesThanks> SeriesThankses => Set<SeriesThanks>();
    public DbSet<SeriesTransportationDepartment> SeriesTransportationDepartments => Set<SeriesTransportationDepartment>();
    public DbSet<SeriesUser> SeriesUsers => Set<SeriesUser>();
    public DbSet<SeriesVisualEffects> SeriesVisualEffectses => Set<SeriesVisualEffects>();
    public DbSet<SeriesWeblink> SeriesWeblinks => Set<SeriesWeblink>();
    public DbSet<SeriesWriter> SeriesWriters => Set<SeriesWriter>();
    public DbSet<SoundMix> SoundMixs => Set<SoundMix>();
    public DbSet<Status> Statuses => Set<Status>();
    public DbSet<Text> Texts => Set<Text>();
    public DbSet<Type> Types => Set<Type>();
    public DbSet<User> Users => Set<User>();
    public DbSet<Weblink> Weblinks => Set<Weblink>();

    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Alle IEntityTypeConfiguration<T>-Klassen aus diesem Assembly laden.
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(AppDbContext).Assembly);
        base.OnModelCreating(modelBuilder);
    }
}
