EntertainmentInfothek: EntertainmentDB.Data.RuntimeItem Class Reference
EntertainmentDB.Data.RuntimeItem Class Reference
Provides a runtime item.
Public Member Functions
RuntimeItem (DBReader reader)
Initializes a runtime item with an empty id string.
RuntimeItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes a runtime item with the given id string.
Public Member Functions inherited from EntertainmentDB.Data.Entry
virtual int Retrieve (bool retrieveBasicInfoOnly)
Retrieves the information of the entry from the database.
Static Public Member Functions
static List< RuntimeItem > RetrieveList (DBReader reader, string baseTableName, string baseTableID, string targetTableName, string order="ID")
Retrieves a list of runtime items from the database.
Protected Member Functions
override int RetrieveBasicInformation (bool retrieveBasicInfoOnly)
Retrieves the basic information of the runtime item from the database.
Protected Member Functions inherited from EntertainmentDB.Data.EntryItem
EntryItem (DBReader reader)
Initializes an entry item with an emtpy id string.
EntryItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes an entry item with the given id string.
Protected Member Functions inherited from EntertainmentDB.Data.Entry
Entry (DBReader reader)
Initializes an entry with the given reader and id string.
Entry (DBReader reader, string id)
Initializes an entry with the given reader and id string.
virtual int RetrieveAdditionalInformation ()
Retrieves the additional information of the entry from the database.
Properties
int Runtime [getset]
The runtime of the runtime item.
Edition Edition [getset]
The edition of the runtime item.
Properties inherited from EntertainmentDB.Data.EntryItem
string BaseTableName [getset]
The base table name of the entry item.
string TargetTableName [getset]
The target table name of the entry item.
Properties inherited from EntertainmentDB.Data.Entry
DBReader Reader [getprotected set]
The database reader to be used to read the entry information from the database.
string ID [getset]
The id of the entry.
string Details [getset]
The details of the entry.
Status Status [getset]
The status of the entry.
string LastUpdated [getset]
The date of last update of the entry.
Static Private Attributes
static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides a runtime item.
Constructor & Destructor Documentation
RuntimeItem() [1/2]
EntertainmentDB.Data.RuntimeItem.RuntimeItem (DBReader reader)
Initializes a runtime item with an empty id string.
Parameters
reader The database reader to be used to read the runtime item information from the database.
Referenced by EntertainmentDB.Data.RuntimeItem.RetrieveList().
RuntimeItem() [2/2]
EntertainmentDB.Data.RuntimeItem.RuntimeItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes a runtime item with the given id string.
Parameters
reader The database reader to be used to read the runtime item information from the database.
id The id of the runtime item.
baseTableName The base table name of the runtime item.
targetTableName The target table name of the runtime item.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Member Function Documentation
RetrieveBasicInformation()
override int EntertainmentDB.Data.RuntimeItem.RetrieveBasicInformation (bool retrieveBasicInfoOnly) protected virtual
Retrieves the basic information of the runtime item from the database.
Parameters
retrieveBasicInfoOnly true if only the basic info is to be retrieved; false if also additional data is to be retrieved.
Returns
1 if data record was retrieved; 0 if no data record matched the id.
Implements EntertainmentDB.Data.Entry.
RetrieveList()
static List< RuntimeItem > EntertainmentDB.Data.RuntimeItem.RetrieveList (DBReader reader, string baseTableName, string baseTableID, string targetTableName, string order = "ID") static
Retrieves a list of runtime items from the database.
Parameters
reader The reader to be used to retrieve the data records.
baseTableName The base table name of the runtime item.
baseTableID The base table id of the runtime item.
targetTableName The target table name of the runtime item.
order The order in which the data records are to be sorted.
Returns
The list of runtime items.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Referenced by EntertainmentDB.Data.Movie.RetrieveAdditionalInformation().
Member Data Documentation
Logger
readonly NLog.Logger EntertainmentDB.Data.RuntimeItem.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by EntertainmentDB.Data.RuntimeItem.RetrieveList(), and EntertainmentDB.Data.RuntimeItem.RuntimeItem().
Property Documentation
Edition
Edition EntertainmentDB.Data.RuntimeItem.Edition get set
The edition of the runtime item.
Referenced by EntertainmentDB.Data.RuntimeItem.RetrieveBasicInformation().
Runtime
int EntertainmentDB.Data.RuntimeItem.Runtime get set
The runtime of the runtime item.
Referenced by EntertainmentDB.Data.RuntimeItem.RetrieveBasicInformation().
The documentation for this class was generated from the following file:
EntertainmentInfothek/src/EntertainmentDB/Data/RuntimeItem.cs