EntertainmentInfothek: WikiPageCreator.Export.Create.EntryContentCreator Class Reference
WikiPageCreator.Export.Create.EntryContentCreator Class Reference
Provides a content creator for an entry.
Public Member Functions
virtual string GetPageName ()
Returns the page name of the entrys page.
virtual List< string > CreatePageContent ()
Creates the page content of the entry.
virtual List< string > CreateInfoBoxContent ()
Creates the infobox content of a given entry.
virtual List< string > CreateChapterContent ()
Creates the chapter content of a given entry.
virtual List< string > CreateSectionContent ()
Creates the section content of a given entry.
Protected Member Functions
EntryContentCreator (Entry entry, Formatter formatter, string targetLanguageCode)
Initializes an EntryContentCreator with the given entry, formatter and target language code.
virtual List< string > CreatePageContentInternal ()
Creates the page content of the entry.
virtual List< string > CreatePageHeader ()
Creates the formatted header content of a given entry.
virtual List< string > CreatePageTitle ()
Creates the formatted file title content of a given entry.
virtual List< string > CreateInfoBoxBegin ()
Creates the formatted infobox begin content of a given entry
virtual List< string > CreateInfoBoxContentInternal ()
Creates the infobox content of a given entry.
void CreateInfoBoxContentHelper (List< string > content, string title, string[] path, string pagename, string text, string additionalInfo)
Creates the specific row of the infobox content.
void CreateInfoBoxContentHelper (List< string > content, string title, string[] path, string pagename, Image image, int size, string additionalInfo)
virtual List< string > CreateInfoBoxEnd ()
Creates the formatted infobox end content of a given entry
virtual List< string > CreateNewChapter (Dictionary< string, string > title)
Creates a formatted chapter heading with the given title.
virtual List< string > CreateChapterContentInternal ()
Creates the chapter content of a given entry.
virtual List< string > CreateNewSection (Dictionary< string, string > title)
Creates a formatted section heading with the given title.
virtual List< string > CreateSectionContentInternal ()
Creates the section content of a given entry.
virtual List< string > CreatePageFooter ()
Creates the formatted footer content of a given entry.
Properties
Formatter Formatter [get, protected set]
The formatter to be used to format the information of the entry.
Entry Entry [get, protected set]
The entry to be used to create the content.
string TargetLanguageCode [get, protected set]
The target language (as a language code) to specify the language of the created content.
Static Private Attributes
static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides a content creator for an entry.
Constructor & Destructor Documentation
EntryContentCreator()
WikiPageCreator.Export.Create.EntryContentCreator.EntryContentCreator (Entry entry, Formatter formatter, string targetLanguageCode) protected
Initializes an EntryContentCreator with the given entry, formatter and target language code.
Parameters
entry The entry to be used to create content.
formatter The formatter to be used to format the content
targetLanguageCode The language code for the created content.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Member Function Documentation
CreateChapterContent()
virtual List< string > WikiPageCreator.Export.Create.EntryContentCreator.CreateChapterContent () virtual
Creates the chapter content of a given entry.
Returns
The formatted content of the entry.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Reimplemented in WikiPageCreator.Export.Create.ConnectionContentCreator.
CreateChapterContentInternal()
virtual List< string > WikiPageCreator.Export.Create.EntryContentCreator.CreateChapterContentInternal () protected virtual
Creates the chapter content of a given entry.
Returns
The formatted content of the entry.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Reimplemented in WikiPageCreator.Export.Create.ConnectionContentCreator, WikiPageCreator.Export.Create.MovieContentCreator, and WikiPageCreator.Export.Create.SeriesContentCreator.
Referenced by WikiPageCreator.Export.Create.EntryContentCreator.CreatePageContentInternal().
CreateInfoBoxBegin()
virtual List< string > WikiPageCreator.Export.Create.EntryContentCreator.CreateInfoBoxBegin () protected virtual
Creates the formatted infobox begin content of a given entry
Returns
The formatted infobox begin content of the entry.
Referenced by WikiPageCreator.Export.Create.EntryContentCreator.CreatePageContentInternal().
CreateInfoBoxContent()
virtual List< string > WikiPageCreator.Export.Create.EntryContentCreator.CreateInfoBoxContent () virtual
Creates the infobox content of a given entry.
Returns
The formatted infobox content of the entry.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Reimplemented in WikiPageCreator.Export.Create.CertificationContentCreator, WikiPageCreator.Export.Create.CountryContentCreator, WikiPageCreator.Export.Create.GenreContentCreator, WikiPageCreator.Export.Create.LanguageContentCreator, and WikiPageCreator.Export.Create.TypeContentCreator.
CreateInfoBoxContentHelper() [1/2]
void WikiPageCreator.Export.Create.EntryContentCreator.CreateInfoBoxContentHelper (List< string > content, string title, string[] path, string pagename, Image image, int size, string additionalInfo) protected
CreateInfoBoxContentHelper() [2/2]
void WikiPageCreator.Export.Create.EntryContentCreator.CreateInfoBoxContentHelper (List< string > content, string title, string[] path, string pagename, string text, string additionalInfo) protected
Creates the specific row of the infobox content.
Parameters
content The list that contains the content of the infobox.
title The title for the row.
path The path for the link.
pagename The pagename for the link.
text The text to be displayed for the link.
additionalInfo Additional info to be displayed after the link.
Referenced by WikiPageCreator.Export.Create.CertificationContentCreator.CreateInfoBoxContentInternal(), WikiPageCreator.Export.Create.CountryContentCreator.CreateInfoBoxContentInternal(), WikiPageCreator.Export.Create.GenreContentCreator.CreateInfoBoxContentInternal(), and WikiPageCreator.Export.Create.LanguageContentCreator.CreateInfoBoxContentInternal().
CreateInfoBoxContentInternal()
virtual List< string > WikiPageCreator.Export.Create.EntryContentCreator.CreateInfoBoxContentInternal () protected virtual
Creates the infobox content of a given entry.
Returns
The formatted infobox content of the entry.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Reimplemented in WikiPageCreator.Export.Create.CertificationContentCreator, WikiPageCreator.Export.Create.CountryContentCreator, WikiPageCreator.Export.Create.GenreContentCreator, WikiPageCreator.Export.Create.LanguageContentCreator, WikiPageCreator.Export.Create.MovieContentCreator, WikiPageCreator.Export.Create.SeriesContentCreator, and WikiPageCreator.Export.Create.TypeContentCreator.
Referenced by WikiPageCreator.Export.Create.EntryContentCreator.CreatePageContentInternal().
CreateInfoBoxEnd()
virtual List< string > WikiPageCreator.Export.Create.EntryContentCreator.CreateInfoBoxEnd () protected virtual
Creates the formatted infobox end content of a given entry
Returns
The formatted infobox end content of the article.
Referenced by WikiPageCreator.Export.Create.EntryContentCreator.CreatePageContentInternal().
CreateNewChapter()
virtual List< string > WikiPageCreator.Export.Create.EntryContentCreator.CreateNewChapter (Dictionary< string, string > title) protected virtual
Creates a formatted chapter heading with the given title.
Parameters
title The title that is to be used as heading.
Returns
The fomatted chapter heading.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.ArticleContentCreator.CreateChapterConnection().
CreateNewSection()
virtual List< string > WikiPageCreator.Export.Create.EntryContentCreator.CreateNewSection (Dictionary< string, string > title) protected virtual
Creates a formatted section heading with the given title.
Parameters
title The title that is to be used as heading.
Returns
The fomatted chapter heading.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
CreatePageContent()
virtual List< string > WikiPageCreator.Export.Create.EntryContentCreator.CreatePageContent () virtual
Creates the page content of the entry.
Returns
The formatted page content of the entry.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Reimplemented in WikiPageCreator.Export.Create.ArticleContentCreator.
CreatePageContentInternal()
virtual List< string > WikiPageCreator.Export.Create.EntryContentCreator.CreatePageContentInternal () protected virtual
Creates the page content of the entry.
Returns
The formatted page content of the entry.
Referenced by WikiPageCreator.Export.Create.ArticleContentCreator.CreatePageContent().
CreatePageFooter()
virtual List< string > WikiPageCreator.Export.Create.EntryContentCreator.CreatePageFooter () protected virtual
Creates the formatted footer content of a given entry.
Returns
The formatted footer content of the entry.
Referenced by WikiPageCreator.Export.Create.EntryContentCreator.CreatePageContentInternal().
CreatePageHeader()
virtual List< string > WikiPageCreator.Export.Create.EntryContentCreator.CreatePageHeader () protected virtual
Creates the formatted header content of a given entry.
Returns
The formatted header content of the entry.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Reimplemented in WikiPageCreator.Export.Create.ArticleContentCreator.
Referenced by WikiPageCreator.Export.Create.EntryContentCreator.CreatePageContentInternal().
CreatePageTitle()
virtual List< string > WikiPageCreator.Export.Create.EntryContentCreator.CreatePageTitle () protected virtual
Creates the formatted file title content of a given entry.
Returns
The formatted file title of the entry.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Reimplemented in WikiPageCreator.Export.Create.ArticleContentCreator.
Referenced by WikiPageCreator.Export.Create.EntryContentCreator.CreatePageContentInternal().
CreateSectionContent()
virtual List< string > WikiPageCreator.Export.Create.EntryContentCreator.CreateSectionContent () virtual
Creates the section content of a given entry.
Returns
The formatted section content of the entry.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Reimplemented in WikiPageCreator.Export.Create.ConnectionContentCreator.
CreateSectionContentInternal()
virtual List< string > WikiPageCreator.Export.Create.EntryContentCreator.CreateSectionContentInternal () protected virtual
Creates the section content of a given entry.
Returns
The formatted section content of the entry.
Exceptions
NotSupportedException Thrown because the operation is not supported.
GetPageName()
virtual string WikiPageCreator.Export.Create.EntryContentCreator.GetPageName () virtual
Returns the page name of the entrys page.
Returns
The formatted page name for the entry.
Exceptions
NotSupportedException Thrown because the operation is not supported.
Reimplemented in WikiPageCreator.Export.Create.ArticleContentCreator.
Member Data Documentation
Logger
readonly NLog.Logger WikiPageCreator.Export.Create.EntryContentCreator.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by WikiPageCreator.Export.Create.EntryContentCreator.CreateChapterContent(), WikiPageCreator.Export.Create.EntryContentCreator.CreateChapterContentInternal(), WikiPageCreator.Export.Create.EntryContentCreator.CreateInfoBoxBegin(), WikiPageCreator.Export.Create.EntryContentCreator.CreateInfoBoxContent(), WikiPageCreator.Export.Create.EntryContentCreator.CreateInfoBoxContentInternal(), WikiPageCreator.Export.Create.EntryContentCreator.CreateInfoBoxEnd(), WikiPageCreator.Export.Create.EntryContentCreator.CreateNewChapter(), WikiPageCreator.Export.Create.EntryContentCreator.CreateNewSection(), WikiPageCreator.Export.Create.EntryContentCreator.CreatePageContent(), WikiPageCreator.Export.Create.EntryContentCreator.CreatePageContentInternal(), WikiPageCreator.Export.Create.EntryContentCreator.CreatePageFooter(), WikiPageCreator.Export.Create.EntryContentCreator.CreatePageHeader(), WikiPageCreator.Export.Create.EntryContentCreator.CreatePageTitle(), WikiPageCreator.Export.Create.EntryContentCreator.CreateSectionContent(), WikiPageCreator.Export.Create.EntryContentCreator.CreateSectionContentInternal(), WikiPageCreator.Export.Create.EntryContentCreator.EntryContentCreator(), and WikiPageCreator.Export.Create.EntryContentCreator.GetPageName().
Property Documentation
Entry
Entry WikiPageCreator.Export.Create.EntryContentCreator.Entry get protected set
The entry to be used to create the content.
Formatter
Formatter WikiPageCreator.Export.Create.EntryContentCreator.Formatter get protected set
The formatter to be used to format the information of the entry.
TargetLanguageCode
string WikiPageCreator.Export.Create.EntryContentCreator.TargetLanguageCode get protected set
The target language (as a language code) to specify the language of the created content.
Referenced by WikiPageCreator.Export.Create.ArticleContentCreator.CreateChapterConnection(), WikiPageCreator.Export.Create.ConnectionContentCreator.CreateChapterContentInternal(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxCertification(), WikiPageCreator.Export.Create.CertificationContentCreator.CreateInfoBoxContentInternal(), WikiPageCreator.Export.Create.CountryContentCreator.CreateInfoBoxContentInternal(), WikiPageCreator.Export.Create.GenreContentCreator.CreateInfoBoxContentInternal(), WikiPageCreator.Export.Create.LanguageContentCreator.CreateInfoBoxContentInternal(), WikiPageCreator.Export.Create.TypeContentCreator.CreateInfoBoxContentInternal(), WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator.CreateInfoBoxCountry(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxGenre(), WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator.CreateInfoBoxLanguage(), WikiPageCreator.Export.Create.SeriesContentCreator.CreateInfoBoxNoOfEpisodes(), WikiPageCreator.Export.Create.SeriesContentCreator.CreateInfoBoxNoOfSeasons(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxReleaseDate(), WikiPageCreator.Export.Create.SeriesContentCreator.CreateInfoBoxReleaseDateFirstEpisode(), WikiPageCreator.Export.Create.SeriesContentCreator.CreateInfoBoxReleaseDateLastEpisode(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxTitle(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxType(), WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator.CreateInfoBoxWorldwideGross(), WikiPageCreator.Export.Create.EntryContentCreator.CreateNewChapter(), WikiPageCreator.Export.Create.EntryContentCreator.CreateNewSection(), WikiPageCreator.Export.Create.ArticleContentCreator.CreatePageTitle(), and WikiPageCreator.Export.Create.EntryContentCreator.EntryContentCreator().
The documentation for this class was generated from the following file:
EntertainmentInfothek/src/WikiPageCreator/Export/Create/EntryContentCreator.cs