EntertainmentInfothek: WikiPageCreator.Export.Format.DokuWikiFormatter Class Reference
WikiPageCreator.Export.Format.DokuWikiFormatter Class Reference
Provides a formatter for a DokuWiki.
Public Member Functions
DokuWikiFormatter ()
Initializes a DokuWiki formatter.
override string AsFilename (string pagename)
Formats the given pagename as a filename.
override string AsBold (string text)
Formats the given text as bold text.
override string AsItalic (string text)
Formats the given text as italic text.
override string AsUnderlined (string text)
Formats the given text as underlinded text.
override string AsSubscript (string text)
Formats the given text as subscript text.
override string AsSuperscript (string text)
Formats the given text as superscript text.
override string AsDeleted (string text)
Formats the given text as deleted text.
override string AsInternalLink (string[] path, string pagename, string section, string text)
Formats the given parameters as an internal link.
override string AsInternalLink (string[] path, string pagename, string text)
Formats the given parameters as an internal link.
override string AsInternalLink (string[] path, string pagename)
Formats the given parameters as an internal link.
override string AsInternalLink (string pagename, string section, string text)
Formats the given parameters as an internal link.
override string AsInternalLink (string pagename, string text)
Formats the given parameters as an internal link.
override string AsInternalLink (string pagename)
Formats the given parameters as an internal link.
override string AsExternalLink (string link, string text)
Formats the given parameters as an external link.
override string AsExternalLink (string link)
Formats the given parameters as an external link.
override string AsEMail (string mail)
Formats the given email adress as an email link.
override string AsHeading1 (string text)
Formats the given text as a level 1 heading.
override string AsHeading2 (string text)
Formats the given text as a level 2 heading.
override string AsHeading3 (string text)
Formats the given text as a level 3 heading.
override string AsHeading4 (string text)
Formats the given text as a level 4 heading.
override string AsHeading5 (string text)
Formats the given text as a level 5 heading.
override string AsImage (string[] path, string filename, int width, int height, string text)
Formats the given parameters as an image.
override string AsImage (string[] path, string filename, int width, int height)
Formats the given parameters as an image.
override string AsImage (string[] path, string filename, int width, string text)
Formats the given parameters as an image.
override string AsImage (string[] path, string filename, int width)
Formats the given parameters as an image.
override string AsImage (string[] path, string filename, string text)
Formats the given parameters as an image.
override string AsImage (string[] path, string filename)
Formats the given parameters as an image.
override string AsImage (string filename, int width, int height, string text)
Formats the given parameters as an image.
override string AsImage (string filename, int width, int height)
Formats the given parameters as an image.
override string AsImage (string filename, int width, string text)
Formats the given parameters as an image.
override string AsImage (string filename, int width)
Formats the given parameters as an image.
override string AsImage (string filename, string text)
Formats the given parameters as an image.
override string AsImage (string filename)
Formats the given parameters as an image.
override string AsImageBox (string imagelink)
Formats the given imagelink as an imagebox.
override string AlignImage (string imagelink, Alignment align)
Aligns the given imagelink as given.
override string ForceNewLine ()
Inserts an indicator to force a new line.
override string ListItemUnsorted ()
Inserts an indicator for a list item for an unsorted list.
override string ListItemSorted ()
Inserts an indicator for a list item for a sorted list.
override string ListItemIndent ()
Inserts an indicator for an indentation.
override string AsInsertPage (string[] path, string pagename)
Formats the given parameters as an inserted page.
override string AsInsertPage (string pagename)
Formats the given parameters ans an inserted page.
override string DisableTOC ()
Inserts an indicator to disable the TOC (table of contents).
override string DisableCache ()
Inserts an indicator to disable the cache.
override string BeginComment ()
Inserts an indicator to begin a (multiline) comment.
override string EndComment ()
Inserts an indicator to end a (multiline) comment.
override string DefineTable (int size, int[] width)
Inserts an indicator to define a table with the given size and column widths.
override string CellSpanVertically ()
Inserts an indicator to span cells vertically.
override string AsTableRow (string[] data)
Formats the given data as a table row.
override string BeginBox (int size, Alignment align)
Inserts an indicator to begin a box with the given size and alignment.
override string EndBox ()
Inserts an indicator to end a box.
override string BeginDataEntry (string name)
Inserts an indicator to begin a data entry.
override string EndDataEntry ()
Inserts an indicator to end a data entry.
Static Private Attributes
static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Additional Inherited Members
Protected Member Functions inherited from WikiPageCreator.Export.Format.Formatter
Formatter ()
Initializes a formatter.
Detailed Description
Provides a formatter for a DokuWiki.
Constructor & Destructor Documentation
DokuWikiFormatter()
WikiPageCreator.Export.Format.DokuWikiFormatter.DokuWikiFormatter ()
Initializes a DokuWiki formatter.
Member Function Documentation
AlignImage()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AlignImage (string imagelink, Alignment align) virtual
Aligns the given imagelink as given.
Parameters
imagelink The imagelink to be aligned.
align The alignment to be used.
Returns
The Imagelink aligned as given.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null or '0'.
Implements WikiPageCreator.Export.Format.Formatter.
AsBold()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsBold (string text) virtual
Formats the given text as bold text.
Parameters
text The text to be formatted.
Returns
The text formatted as bold.
Exceptions
ArgumentNullException Thrown when the given text is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsDeleted()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsDeleted (string text) virtual
Formats the given text as deleted text.
Parameters
text The text to be formatted.
Returns
The text formatted as deleted.
Exceptions
ArgumentNullException Thrown when the given text is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsEMail()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsEMail (string mail) virtual
Formats the given email adress as an email link.
Parameters
mail the email adress for the link.
Returns
The email formatted as an email link.
Exceptions
ArgumentNullException Thrown when the given email address is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsExternalLink() [1/2]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsExternalLink (string link) virtual
Formats the given parameters as an external link.
Parameters
link The link for the link.
Returns
The parameters formatted as an external link.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsExternalLink() [2/2]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsExternalLink (string link, string text) virtual
Formats the given parameters as an external link.
Parameters
link The link for the link.
text The text to be displayed for the link.
Returns
The parameters formatted as an external link.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsFilename()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsFilename (string pagename) virtual
Formats the given pagename as a filename.
Parameters
pagename The pagename to be formatted.
Returns
The formatted filename.
Exceptions
ArgumentNullException Thrown when the given filename is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsHeading1()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsHeading1 (string text) virtual
Formats the given text as a level 1 heading.
Parameters
text The text to be formatted
Returns
The text formatted as a level 1 heading.
Exceptions
ArgumentNullException Thrown when the given text is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsHeading2()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsHeading2 (string text) virtual
Formats the given text as a level 2 heading.
Parameters
text The text to be formatted
Returns
The text formatted as a level 2 heading.
Exceptions
ArgumentNullException Thrown when the given text is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsHeading3()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsHeading3 (string text) virtual
Formats the given text as a level 3 heading.
Parameters
text The text to be formatted
Returns
The text formatted as a level 3 heading.
Exceptions
ArgumentNullException Thrown when the given text is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsHeading4()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsHeading4 (string text) virtual
Formats the given text as a level 4 heading.
Parameters
text The text to be formatted
Returns
The text formatted as a level 4 heading.
Exceptions
ArgumentNullException Thrown when the given text is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsHeading5()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsHeading5 (string text) virtual
Formats the given text as a level 5 heading.
Parameters
text The text to be formatted
Returns
The text formatted as a level 5 heading.
Exceptions
ArgumentNullException Thrown when the given text is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsImage() [1/12]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsImage (string filename) virtual
Formats the given parameters as an image.
Parameters
filename The filename of the image.
Returns
The parameters formatted as an image.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null or '0'.
Implements WikiPageCreator.Export.Format.Formatter.
AsImage() [2/12]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsImage (string filename, int width) virtual
Formats the given parameters as an image.
Parameters
filename The filename of the image.
width The width for the image.
Returns
The parameters formatted as an image.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null or '0'.
Implements WikiPageCreator.Export.Format.Formatter.
AsImage() [3/12]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsImage (string filename, int width, int height) virtual
Formats the given parameters as an image.
Parameters
filename The filename of the image.
width The width for the image.
height The height for the image.
Returns
The parameters formatted as an image.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null or '0'.
Implements WikiPageCreator.Export.Format.Formatter.
AsImage() [4/12]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsImage (string filename, int width, int height, string text) virtual
Formats the given parameters as an image.
Parameters
filename The filename of the image.
width The width for the image.
height The height for the image.
text The text to be displayed for the image.
Returns
The parameters formatted as an image.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null or '0'.
Implements WikiPageCreator.Export.Format.Formatter.
AsImage() [5/12]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsImage (string filename, int width, string text) virtual
Formats the given parameters as an image.
Parameters
filename The filename of the image.
width The width for the image.
text The text to be displayed for the image.
Returns
The parameters formatted as an image.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null or '0'.
Implements WikiPageCreator.Export.Format.Formatter.
AsImage() [6/12]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsImage (string filename, string text) virtual
Formats the given parameters as an image.
Parameters
filename The filename of the image.
text The text to be displayed for the image.
Returns
The parameters formatted as an image.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null or '0'.
Implements WikiPageCreator.Export.Format.Formatter.
AsImage() [7/12]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsImage (string[] path, string filename) virtual
Formats the given parameters as an image.
Parameters
path The path of the image.
filename The filename of the image.
Returns
The parameters formatted as an image.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null or '0'.
Implements WikiPageCreator.Export.Format.Formatter.
AsImage() [8/12]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsImage (string[] path, string filename, int width) virtual
Formats the given parameters as an image.
Parameters
path The path of the image.
filename The filename of the image.
width The width for the image.
Returns
The parameters formatted as an image.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null or '0'.
Implements WikiPageCreator.Export.Format.Formatter.
AsImage() [9/12]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsImage (string[] path, string filename, int width, int height) virtual
Formats the given parameters as an image.
Parameters
path The path of the image.
filename The filename of the image.
width The width for the image.
height The height for the image.
Returns
The parameters formatted as an image.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null or '0'.
Implements WikiPageCreator.Export.Format.Formatter.
AsImage() [10/12]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsImage (string[] path, string filename, int width, int height, string text) virtual
Formats the given parameters as an image.
Parameters
path The path of the image.
filename The filename of the image.
width The width for the image.
height The height for the image.
text The text to be displayed for the image.
Returns
The parameters formatted as an image.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null or '0'.
Implements WikiPageCreator.Export.Format.Formatter.
Referenced by WikiPageCreator.Export.Format.DokuWikiFormatter.AsImage().
AsImage() [11/12]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsImage (string[] path, string filename, int width, string text) virtual
Formats the given parameters as an image.
Parameters
path The path of the image.
filename The filename of the image.
width The width for the image.
text The text to be displayed for the image.
Returns
The parameters formatted as an image.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null or '0'.
Implements WikiPageCreator.Export.Format.Formatter.
AsImage() [12/12]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsImage (string[] path, string filename, string text) virtual
Formats the given parameters as an image.
Parameters
path The path of the image.
filename The filename of the image.
text The text to be displayed for the image.
Returns
The parameters formatted as an image.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null or '0'.
Implements WikiPageCreator.Export.Format.Formatter.
AsImageBox()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsImageBox (string imagelink) virtual
Formats the given imagelink as an imagebox.
Parameters
imagelink The imagelink to be boxed.
Returns
The boxed imagelink.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null or '0'.
Implements WikiPageCreator.Export.Format.Formatter.
AsInsertPage() [1/2]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsInsertPage (string pagename) virtual
Formats the given parameters ans an inserted page.
Parameters
pagename The pagename of the page.
Returns
The parameters formatted as an inserted page.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsInsertPage() [2/2]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsInsertPage (string[] path, string pagename) virtual
Formats the given parameters as an inserted page.
Parameters
path The path of the page.
pagename The pagename of the page.
Returns
The parameters formatted as an inserted page.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Implements WikiPageCreator.Export.Format.Formatter.
Referenced by WikiPageCreator.Export.Format.DokuWikiFormatter.AsInsertPage().
AsInternalLink() [1/6]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsInternalLink (string pagename) virtual
Formats the given parameters as an internal link.
Parameters
pagename The pagename for the link.
Returns
The parameters formatted as an internal link.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsInternalLink() [2/6]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsInternalLink (string pagename, string section, string text) virtual
Formats the given parameters as an internal link.
Parameters
pagename The pagename for the link.
section The section of the page for the link.
text The text to be displayed for the link.
Returns
The parameters formatted as an internal link.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsInternalLink() [3/6]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsInternalLink (string pagename, string text) virtual
Formats the given parameters as an internal link.
Parameters
pagename The pagename for the link.
text The text to be displayed for the link.
Returns
The parameters formatted as an internal link.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsInternalLink() [4/6]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsInternalLink (string[] path, string pagename) virtual
Formats the given parameters as an internal link.
Parameters
path The path for the link.
pagename The pagename for the link.
Returns
The parameters formatted as an internal link.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsInternalLink() [5/6]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsInternalLink (string[] path, string pagename, string section, string text) virtual
Formats the given parameters as an internal link.
Parameters
path The path for the link.
pagename The pagename for the link.
section The section of the page for the link.
text The text to be displayed for the link.
Returns
The parameters formatted as an internal link.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Implements WikiPageCreator.Export.Format.Formatter.
Referenced by WikiPageCreator.Export.Format.DokuWikiFormatter.AsExternalLink(), and WikiPageCreator.Export.Format.DokuWikiFormatter.AsInternalLink().
AsInternalLink() [6/6]
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsInternalLink (string[] path, string pagename, string text) virtual
Formats the given parameters as an internal link.
Parameters
path The path for the link.
pagename The pagename for the link.
text The text to be displayed for the link.
Returns
The parameters formatted as an internal link.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsItalic()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsItalic (string text) virtual
Formats the given text as italic text.
Parameters
text The text to be formatted.
Returns
The text formatted as italic.
Exceptions
ArgumentNullException Thrown when the given text is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsSubscript()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsSubscript (string text) virtual
Formats the given text as subscript text.
Parameters
text The text to be formatted.
Returns
The text formatted as subscript.
Exceptions
ArgumentNullException Thrown when the given text is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsSuperscript()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsSuperscript (string text) virtual
Formats the given text as superscript text.
Parameters
text The text to be formatted.
Returns
The text formatted as superscript.
Exceptions
ArgumentNullException Thrown when the given text is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsTableRow()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsTableRow (string[] data) virtual
Formats the given data as a table row.
Parameters
data The data for the table row.
Returns
The data formatted as a table row.
Exceptions
ArgumentNullException Thrown when the given data is null.
Implements WikiPageCreator.Export.Format.Formatter.
AsUnderlined()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.AsUnderlined (string text) virtual
Formats the given text as underlinded text.
Parameters
text The text to be formatted.
Returns
The text formatted as underlined.
Exceptions
ArgumentNullException Thrown when the given text is null.
Implements WikiPageCreator.Export.Format.Formatter.
BeginBox()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.BeginBox (int size, Alignment align) virtual
Inserts an indicator to begin a box with the given size and alignment.
Parameters
size The width of the box.
align The alignment of the box.
Returns
Indicator to begin a box.
Exceptions
ArgumentNullException Thrown when the given size is '0'.
Implements WikiPageCreator.Export.Format.Formatter.
BeginComment()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.BeginComment () virtual
Inserts an indicator to begin a (multiline) comment.
Returns
Indicator to begin a comment.
Implements WikiPageCreator.Export.Format.Formatter.
BeginDataEntry()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.BeginDataEntry (string name) virtual
Inserts an indicator to begin a data entry.
Parameters
name The name of the data entry.
Returns
Indicator to begin a data entry.
Exceptions
ArgumentNullException Thrown when the given name is null.
Implements WikiPageCreator.Export.Format.Formatter.
CellSpanVertically()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.CellSpanVertically () virtual
Inserts an indicator to span cells vertically.
Returns
Indicator to span cells vertically.
Implements WikiPageCreator.Export.Format.Formatter.
DefineTable()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.DefineTable (int size, int[] width) virtual
Inserts an indicator to define a table with the given size and column widths.
Parameters
size The size of the table
width The width(s) of the columns.
Returns
Indicator to define the table.
Exceptions
ArgumentNullException Thrown when any of the given parameters is '0'.
Implements WikiPageCreator.Export.Format.Formatter.
DisableCache()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.DisableCache () virtual
Inserts an indicator to disable the cache.
Returns
Indicator to disable the cache.
Implements WikiPageCreator.Export.Format.Formatter.
DisableTOC()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.DisableTOC () virtual
Inserts an indicator to disable the TOC (table of contents).
Returns
Indicator to disable the TOC.
Implements WikiPageCreator.Export.Format.Formatter.
EndBox()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.EndBox () virtual
Inserts an indicator to end a box.
Returns
Indicator to end a box.
Implements WikiPageCreator.Export.Format.Formatter.
EndComment()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.EndComment () virtual
Inserts an indicator to end a (multiline) comment.
Returns
Indicator to end a comment.
Implements WikiPageCreator.Export.Format.Formatter.
EndDataEntry()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.EndDataEntry () virtual
Inserts an indicator to end a data entry.
Returns
Indicator to end a data entry.
Implements WikiPageCreator.Export.Format.Formatter.
ForceNewLine()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.ForceNewLine () virtual
Inserts an indicator to force a new line.
Returns
Indicator to force a new line.
Implements WikiPageCreator.Export.Format.Formatter.
ListItemIndent()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.ListItemIndent () virtual
Inserts an indicator for an indentation.
Returns
Indicator for an indentation.
Implements WikiPageCreator.Export.Format.Formatter.
ListItemSorted()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.ListItemSorted () virtual
Inserts an indicator for a list item for a sorted list.
Returns
Indicator for a list item for a sorted list.
Implements WikiPageCreator.Export.Format.Formatter.
ListItemUnsorted()
override string WikiPageCreator.Export.Format.DokuWikiFormatter.ListItemUnsorted () virtual
Inserts an indicator for a list item for an unsorted list.
Returns
Indicator for a list item for an unsorted list.
Implements WikiPageCreator.Export.Format.Formatter.
Member Data Documentation
Logger
readonly NLog.Logger WikiPageCreator.Export.Format.DokuWikiFormatter.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by WikiPageCreator.Export.Format.DokuWikiFormatter.AlignImage(), WikiPageCreator.Export.Format.DokuWikiFormatter.AsBold(), WikiPageCreator.Export.Format.DokuWikiFormatter.AsDeleted(), WikiPageCreator.Export.Format.DokuWikiFormatter.AsEMail(), WikiPageCreator.Export.Format.DokuWikiFormatter.AsExternalLink(), WikiPageCreator.Export.Format.DokuWikiFormatter.AsFilename(), WikiPageCreator.Export.Format.DokuWikiFormatter.AsHeading1(), WikiPageCreator.Export.Format.DokuWikiFormatter.AsHeading2(), WikiPageCreator.Export.Format.DokuWikiFormatter.AsHeading3(), WikiPageCreator.Export.Format.DokuWikiFormatter.AsHeading4(), WikiPageCreator.Export.Format.DokuWikiFormatter.AsHeading5(), WikiPageCreator.Export.Format.DokuWikiFormatter.AsImage(), WikiPageCreator.Export.Format.DokuWikiFormatter.AsImageBox(), WikiPageCreator.Export.Format.DokuWikiFormatter.AsInsertPage(), WikiPageCreator.Export.Format.DokuWikiFormatter.AsInternalLink(), WikiPageCreator.Export.Format.DokuWikiFormatter.AsItalic(), WikiPageCreator.Export.Format.DokuWikiFormatter.AsSubscript(), WikiPageCreator.Export.Format.DokuWikiFormatter.AsSuperscript(), WikiPageCreator.Export.Format.DokuWikiFormatter.AsTableRow(), WikiPageCreator.Export.Format.DokuWikiFormatter.AsUnderlined(), WikiPageCreator.Export.Format.DokuWikiFormatter.BeginBox(), WikiPageCreator.Export.Format.DokuWikiFormatter.BeginComment(), WikiPageCreator.Export.Format.DokuWikiFormatter.BeginDataEntry(), WikiPageCreator.Export.Format.DokuWikiFormatter.CellSpanVertically(), WikiPageCreator.Export.Format.DokuWikiFormatter.DefineTable(), WikiPageCreator.Export.Format.DokuWikiFormatter.DisableCache(), WikiPageCreator.Export.Format.DokuWikiFormatter.DisableTOC(), WikiPageCreator.Export.Format.DokuWikiFormatter.DokuWikiFormatter(), WikiPageCreator.Export.Format.DokuWikiFormatter.EndBox(), WikiPageCreator.Export.Format.DokuWikiFormatter.EndComment(), WikiPageCreator.Export.Format.DokuWikiFormatter.EndDataEntry(), WikiPageCreator.Export.Format.DokuWikiFormatter.ForceNewLine(), WikiPageCreator.Export.Format.DokuWikiFormatter.ListItemIndent(), WikiPageCreator.Export.Format.DokuWikiFormatter.ListItemSorted(), and WikiPageCreator.Export.Format.DokuWikiFormatter.ListItemUnsorted().
The documentation for this class was generated from the following file:
EntertainmentInfothek/src/WikiPageCreator/Export/Format/DokuWikiFormatter.cs