EntertainmentInfothek: EntertainmentDB.Data.TimespanItem Class Reference
EntertainmentDB.Data.TimespanItem Class Reference
Provides a time span item.
Public Member Functions
TimespanItem (DBReader reader)
Initializes a time span item with an empty id string.
TimespanItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes a time span item with the given id string.
Public Member Functions inherited from EntertainmentDB.Data.Entry
virtual int Retrieve (bool retrieveBasicInfoOnly)
Retrieves the information of the entry from the database.
Static Public Member Functions
static List< TimespanItem > RetrieveList (DBReader reader, string baseTableName, string baseTableID, string targetTableName, string order="ID")
Retrieves a list of time span items from the database.
Protected Member Functions
override int RetrieveBasicInformation (bool retrieveBasicInfoOnly)
Retrieves the basic information of the time span item from the database.
Protected Member Functions inherited from EntertainmentDB.Data.EntryItem
EntryItem (DBReader reader)
Initializes an entry item with an emtpy id string.
EntryItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes an entry item with the given id string.
Protected Member Functions inherited from EntertainmentDB.Data.Entry
Entry (DBReader reader)
Initializes an entry with the given reader and id string.
Entry (DBReader reader, string id)
Initializes an entry with the given reader and id string.
virtual int RetrieveAdditionalInformation ()
Retrieves the additional information of the entry from the database.
Properties
string StartDate [getset]
The start date of the time span item.
string EndDate [getset]
The end date of the time span item.
Properties inherited from EntertainmentDB.Data.EntryItem
string BaseTableName [getset]
The base table name of the entry item.
string TargetTableName [getset]
The target table name of the entry item.
Properties inherited from EntertainmentDB.Data.Entry
DBReader Reader [getprotected set]
The database reader to be used to read the entry information from the database.
string ID [getset]
The id of the entry.
string Details [getset]
The details of the entry.
Status Status [getset]
The status of the entry.
string LastUpdated [getset]
The date of last update of the entry.
Static Private Attributes
static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides a time span item.
Constructor & Destructor Documentation
TimespanItem() [1/2]
EntertainmentDB.Data.TimespanItem.TimespanItem (DBReader reader)
Initializes a time span item with an empty id string.
Parameters
reader The database reader to be used to read the time span item information from the database.
Referenced by EntertainmentDB.Data.TimespanItem.RetrieveList().
TimespanItem() [2/2]
EntertainmentDB.Data.TimespanItem.TimespanItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes a time span item with the given id string.
Parameters
reader The database reader to be used to read the time span item information from the database.
id The id of the time span item.
baseTableName The base table name of the time span item.
targetTableName The target table name of the time span item.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Member Function Documentation
RetrieveBasicInformation()
override int EntertainmentDB.Data.TimespanItem.RetrieveBasicInformation (bool retrieveBasicInfoOnly) protected virtual
Retrieves the basic information of the time span item from the database.
Parameters
retrieveBasicInfoOnly true if only the basic info is to be retrieved; false if also additional data is to be retrieved.
Returns
1 if data record was retrieved; 0 if no data record matched the id.
Implements EntertainmentDB.Data.Entry.
RetrieveList()
static List< TimespanItem > EntertainmentDB.Data.TimespanItem.RetrieveList (DBReader reader, string baseTableName, string baseTableID, string targetTableName, string order = "ID") static
Retrieves a list of time span items from the database.
Parameters
reader The reader to be used to retrieve the data records.
baseTableName The base table name of the time span item.
baseTableID The base table id of the time span item.
targetTableName The target table name of the time span item.
order The order in which the data records are to be sorted.
Returns
The list of time span items.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Referenced by EntertainmentDB.Data.Movie.RetrieveAdditionalInformation().
Member Data Documentation
Logger
readonly NLog.Logger EntertainmentDB.Data.TimespanItem.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by EntertainmentDB.Data.TimespanItem.TimespanItem().
Property Documentation
EndDate
string EntertainmentDB.Data.TimespanItem.EndDate get set
The end date of the time span item.
Referenced by EntertainmentDB.Data.TimespanItem.RetrieveBasicInformation().
StartDate
string EntertainmentDB.Data.TimespanItem.StartDate get set
The start date of the time span item.
Referenced by EntertainmentDB.Data.TimespanItem.RetrieveBasicInformation().
The documentation for this class was generated from the following file:
C:/Users/Sandra/Projekte/GitHub/EntertainmentInfothek_public/src/EntertainmentDB/Data/TimespanItem.cs