EntertainmentInfothek: WikiPageCreator.Export.Format.Formatter Class Reference
WikiPageCreator.Export.Format.Formatter Class Reference abstract
Provides a formatter.
Public Member Functions
abstract string AsFilename (string pagename)
Formats the given pagename as a filename.
abstract string AsBold (string text)
Formats the given text as bold text.
abstract string AsItalic (string text)
Formats the given text as italic text.
abstract string AsUnderlined (string text)
Formats the given text as underlinded text.
abstract string AsSubscript (string text)
Formats the given text as subscript text.
abstract string AsSuperscript (string text)
Formats the given text as superscript text.
abstract string AsDeleted (string text)
Formats the given text as deleted text.
abstract string AsInternalLink (string[] path, string pagename, string section, string text)
Formats the given parameters as an internal link.
abstract string AsInternalLink (string[] path, string pagename, string text)
Formats the given parameters as an internal link.
abstract string AsInternalLink (string[] path, string pagename)
Formats the given parameters as an internal link.
abstract string AsInternalLink (string pagename, string section, string text)
Formats the given parameters as an internal link.
abstract string AsInternalLink (string pagename, string text)
Formats the given parameters as an internal link.
abstract string AsInternalLink (string pagename)
Formats the given parameters as an internal link.
abstract string AsExternalLink (string link, string text)
Formats the given parameters as an external link.
abstract string AsExternalLink (string link)
Formats the given parameters as an external link.
abstract string AsEMail (string mail)
Formats the given email adress as an email link.
abstract string AsHeading1 (string text)
Formats the given text as a level 1 heading.
abstract string AsHeading2 (string text)
Formats the given text as a level 2 heading.
abstract string AsHeading3 (string text)
Formats the given text as a level 3 heading.
abstract string AsHeading4 (string text)
Formats the given text as a level 4 heading.
abstract string AsHeading5 (string text)
Formats the given text as a level 5 heading.
abstract string AsImage (string[] path, string filename, int width, int height, string text)
Formats the given parameters as an image.
abstract string AsImage (string[] path, string filename, int width, int height)
Formats the given parameters as an image.
abstract string AsImage (string[] path, string filename, int width, string text)
Formats the given parameters as an image.
abstract string AsImage (string[] path, string filename, int width)
Formats the given parameters as an image.
abstract string AsImage (string[] path, string filename, string text)
Formats the given parameters as an image.
abstract string AsImage (string[] path, string filename)
Formats the given parameters as an image.
abstract string AsImage (string filename, int width, int height, string text)
Formats the given parameters as an image.
abstract string AsImage (string filename, int width, int height)
Formats the given parameters as an image.
abstract string AsImage (string filename, int width, string text)
Formats the given parameters as an image.
abstract string AsImage (string filename, int width)
Formats the given parameters as an image.
abstract string AsImage (string filename, string text)
Formats the given parameters as an image.
abstract string AsImage (string filename)
Formats the given parameters as an image.
abstract string AsImageBox (string imagelink)
Formats the given imagelink as an imagebox.
abstract string AlignImage (string imagelink, Alignment align)
Aligns the given imagelink as given.
abstract string ForceNewLine ()
Inserts an indicator to force a new line.
abstract string ListItemUnsorted ()
Inserts an indicator for a list item for an unsorted list.
abstract string ListItemSorted ()
Inserts an indicator for a list item for a sorted list.
abstract string ListItemIndent ()
Inserts an indicator for an indentation.
abstract string AsInsertPage (string[] path, string pagename)
Formats the given parameters as an inserted page.
abstract string AsInsertPage (string pagename)
Formats the given parameters ans an inserted page.
abstract string DisableTOC ()
Inserts an indicator to disable the TOC (table of contents).
abstract string DisableCache ()
Inserts an indicator to disable the cache.
abstract string BeginComment ()
Inserts an indicator to begin a (multiline) comment.
abstract string EndComment ()
Inserts an indicator to end a (multiline) comment.
abstract string DefineTable (int size, int[] width)
Inserts an indicator to define a table with the given size and column widths.
abstract string CellSpanVertically ()
Inserts an indicator to span cells vertically.
abstract string AsTableRow (string[] data)
Formats the given data as a table row.
abstract string BeginBox (int size, Alignment align)
Inserts an indicator to begin a box with the given size and alignment.
abstract string EndBox ()
Inserts an indicator to end a box.
abstract string BeginDataEntry (string name)
Inserts an indicator to begin a data entry.
abstract string EndDataEntry ()
Inserts an indicator to end a data entry.
Protected Member Functions
Formatter ()
Initializes a formatter.
Static Private Attributes
static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides a formatter.
Constructor & Destructor Documentation
Formatter()
WikiPageCreator.Export.Format.Formatter.Formatter () protected
Initializes a formatter.
Member Function Documentation
AlignImage()
abstract string WikiPageCreator.Export.Format.Formatter.AlignImage (string imagelink, Alignment align) pure virtual
Aligns the given imagelink as given.
Parameters
imagelink The imagelink to be aligned.
align The alignment to be used.
Returns
The Imagelink aligned as given.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsBold()
abstract string WikiPageCreator.Export.Format.Formatter.AsBold (string text) pure virtual
Formats the given text as bold text.
Parameters
text The text to be formatted.
Returns
The text formatted as bold.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsDeleted()
abstract string WikiPageCreator.Export.Format.Formatter.AsDeleted (string text) pure virtual
Formats the given text as deleted text.
Parameters
text The text to be formatted.
Returns
The text formatted as deleted.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsEMail()
abstract string WikiPageCreator.Export.Format.Formatter.AsEMail (string mail) pure virtual
Formats the given email adress as an email link.
Parameters
mail the email adress for the link.
Returns
The email formatted as an email link.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsExternalLink() [1/2]
abstract string WikiPageCreator.Export.Format.Formatter.AsExternalLink (string link) pure virtual
Formats the given parameters as an external link.
Parameters
link The link for the link.
Returns
The parameters formatted as an external link.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsExternalLink() [2/2]
abstract string WikiPageCreator.Export.Format.Formatter.AsExternalLink (string link, string text) pure virtual
Formats the given parameters as an external link.
Parameters
link The link for the link.
text The text to be displayed for the link.
Returns
The parameters formatted as an external link.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsFilename()
abstract string WikiPageCreator.Export.Format.Formatter.AsFilename (string pagename) pure virtual
Formats the given pagename as a filename.
Parameters
pagename The pagename to be formatted.
Returns
The formatted filename.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.GetFileName(), and WikiPageCreator.Export.Create.ArticleContentCreator.GetPageName().
AsHeading1()
abstract string WikiPageCreator.Export.Format.Formatter.AsHeading1 (string text) pure virtual
Formats the given text as a level 1 heading.
Parameters
text The text to be formatted
Returns
The text formatted as a level 1 heading.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
Referenced by WikiPageCreator.Export.Create.ArticleContentCreator.CreatePageTitle(), and WikiPageCreator.Export.Create.MovieFileContentCreator.CreateTitle().
AsHeading2()
abstract string WikiPageCreator.Export.Format.Formatter.AsHeading2 (string text) pure virtual
Formats the given text as a level 2 heading.
Parameters
text The text to be formatted
Returns
The text formatted as a level 2 heading.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateAwardChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCastAndCrewChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCompanyChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateConnectionChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCoverChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateDescriptionChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateFilmingAndProductionChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateImageChapter(), WikiPageCreator.Export.Create.EntryContentCreator.CreateNewChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreatePosterChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateReviewChapter(), and WikiPageCreator.Export.Create.MovieFileContentCreator.CreateWeblinkChapter().
AsHeading3()
abstract string WikiPageCreator.Export.Format.Formatter.AsHeading3 (string text) pure virtual
Formats the given text as a level 3 heading.
Parameters
text The text to be formatted
Returns
The text formatted as a level 3 heading.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCastPersonItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCompanyItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateDistributorCompanyItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateFilmingAndProductionChapter(), WikiPageCreator.Export.Create.EntryContentCreator.CreateNewSection(), and WikiPageCreator.Export.Create.MovieFileContentCreator.CreatePersonItemSection().
AsHeading4()
abstract string WikiPageCreator.Export.Format.Formatter.AsHeading4 (string text) pure virtual
Formats the given text as a level 4 heading.
Parameters
text The text to be formatted
Returns
The text formatted as a level 4 heading.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsHeading5()
abstract string WikiPageCreator.Export.Format.Formatter.AsHeading5 (string text) pure virtual
Formats the given text as a level 5 heading.
Parameters
text The text to be formatted
Returns
The text formatted as a level 5 heading.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsImage() [1/12]
abstract string WikiPageCreator.Export.Format.Formatter.AsImage (string filename) pure virtual
Formats the given parameters as an image.
Parameters
filename The filename of the image.
Returns
The parameters formatted as an image.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsImage() [2/12]
abstract string WikiPageCreator.Export.Format.Formatter.AsImage (string filename, int width) pure virtual
Formats the given parameters as an image.
Parameters
filename The filename of the image.
width The width for the image.
Returns
The parameters formatted as an image.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsImage() [3/12]
abstract string WikiPageCreator.Export.Format.Formatter.AsImage (string filename, int width, int height) pure virtual
Formats the given parameters as an image.
Parameters
filename The filename of the image.
width The width for the image.
height The height for the image.
Returns
The parameters formatted as an image.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsImage() [4/12]
abstract string WikiPageCreator.Export.Format.Formatter.AsImage (string filename, int width, int height, string text) pure virtual
Formats the given parameters as an image.
Parameters
filename The filename of the image.
width The width for the image.
height The height for the image.
text The text to be displayed for the image.
Returns
The parameters formatted as an image.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsImage() [5/12]
abstract string WikiPageCreator.Export.Format.Formatter.AsImage (string filename, int width, string text) pure virtual
Formats the given parameters as an image.
Parameters
filename The filename of the image.
width The width for the image.
text The text to be displayed for the image.
Returns
The parameters formatted as an image.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsImage() [6/12]
abstract string WikiPageCreator.Export.Format.Formatter.AsImage (string filename, string text) pure virtual
Formats the given parameters as an image.
Parameters
filename The filename of the image.
text The text to be displayed for the image.
Returns
The parameters formatted as an image.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsImage() [7/12]
abstract string WikiPageCreator.Export.Format.Formatter.AsImage (string[] path, string filename) pure virtual
Formats the given parameters as an image.
Parameters
path The path of the image.
filename The filename of the image.
Returns
The parameters formatted as an image.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsImage() [8/12]
abstract string WikiPageCreator.Export.Format.Formatter.AsImage (string[] path, string filename, int width) pure virtual
Formats the given parameters as an image.
Parameters
path The path of the image.
filename The filename of the image.
width The width for the image.
Returns
The parameters formatted as an image.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsImage() [9/12]
abstract string WikiPageCreator.Export.Format.Formatter.AsImage (string[] path, string filename, int width, int height) pure virtual
Formats the given parameters as an image.
Parameters
path The path of the image.
filename The filename of the image.
width The width for the image.
height The height for the image.
Returns
The parameters formatted as an image.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsImage() [10/12]
abstract string WikiPageCreator.Export.Format.Formatter.AsImage (string[] path, string filename, int width, int height, string text) pure virtual
Formats the given parameters as an image.
Parameters
path The path of the image.
filename The filename of the image.
width The width for the image.
height The height for the image.
text The text to be displayed for the image.
Returns
The parameters formatted as an image.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateImageItemSection(), and WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxLogo().
AsImage() [11/12]
abstract string WikiPageCreator.Export.Format.Formatter.AsImage (string[] path, string filename, int width, string text) pure virtual
Formats the given parameters as an image.
Parameters
path The path of the image.
filename The filename of the image.
width The width for the image.
text The text to be displayed for the image.
Returns
The parameters formatted as an image.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsImage() [12/12]
abstract string WikiPageCreator.Export.Format.Formatter.AsImage (string[] path, string filename, string text) pure virtual
Formats the given parameters as an image.
Parameters
path The path of the image.
filename The filename of the image.
text The text to be displayed for the image.
Returns
The parameters formatted as an image.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsImageBox()
abstract string WikiPageCreator.Export.Format.Formatter.AsImageBox (string imagelink) pure virtual
Formats the given imagelink as an imagebox.
Parameters
imagelink The imagelink to be boxed.
Returns
The boxed imagelink.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateImageItemSection().
AsInsertPage() [1/2]
abstract string WikiPageCreator.Export.Format.Formatter.AsInsertPage (string pagename) pure virtual
Formats the given parameters ans an inserted page.
Parameters
pagename The pagename of the page.
Returns
The parameters formatted as an inserted page.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsInsertPage() [2/2]
abstract string WikiPageCreator.Export.Format.Formatter.AsInsertPage (string[] path, string pagename) pure virtual
Formats the given parameters as an inserted page.
Parameters
path The path of the page.
pagename The pagename of the page.
Returns
The parameters formatted as an inserted page.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
Referenced by WikiPageCreator.Export.Create.ConnectionContentCreator.CreateChapterContentInternal(), and WikiPageCreator.Export.Create.MovieFileContentCreator.CreateConnectionChapter().
AsInternalLink() [1/6]
abstract string WikiPageCreator.Export.Format.Formatter.AsInternalLink (string pagename) pure virtual
Formats the given parameters as an internal link.
Parameters
pagename The pagename for the link.
Returns
The parameters formatted as an internal link.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsInternalLink() [2/6]
abstract string WikiPageCreator.Export.Format.Formatter.AsInternalLink (string pagename, string section, string text) pure virtual
Formats the given parameters as an internal link.
Parameters
pagename The pagename for the link.
section The section of the page for the link.
text The text to be displayed for the link.
Returns
The parameters formatted as an internal link.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsInternalLink() [3/6]
abstract string WikiPageCreator.Export.Format.Formatter.AsInternalLink (string pagename, string text) pure virtual
Formats the given parameters as an internal link.
Parameters
pagename The pagename for the link.
text The text to be displayed for the link.
Returns
The parameters formatted as an internal link.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsInternalLink() [4/6]
abstract string WikiPageCreator.Export.Format.Formatter.AsInternalLink (string[] path, string pagename) pure virtual
Formats the given parameters as an internal link.
Parameters
path The path for the link.
pagename The pagename for the link.
Returns
The parameters formatted as an internal link.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsInternalLink() [5/6]
abstract string WikiPageCreator.Export.Format.Formatter.AsInternalLink (string[] path, string pagename, string section, string text) pure virtual
Formats the given parameters as an internal link.
Parameters
path The path for the link.
pagename The pagename for the link.
section The section of the page for the link.
text The text to be displayed for the link.
Returns
The parameters formatted as an internal link.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateAwardChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCastPersonItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCompanyItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateDistributorCompanyItemSection(), WikiPageCreator.Export.Create.TypeContentCreator.CreateInfoBoxContentInternal(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxOriginalReleaseDate(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxReleaseDate(), WikiPageCreator.Export.Create.SeriesContentCreator.CreateInfoBoxReleaseDateFirstEpisode(), WikiPageCreator.Export.Create.SeriesContentCreator.CreateInfoBoxReleaseDateLastEpisode(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxType(), and WikiPageCreator.Export.Create.MovieFileContentCreator.CreatePersonItemSection().
AsInternalLink() [6/6]
abstract string WikiPageCreator.Export.Format.Formatter.AsInternalLink (string[] path, string pagename, string text) pure virtual
Formats the given parameters as an internal link.
Parameters
path The path for the link.
pagename The pagename for the link.
text The text to be displayed for the link.
Returns
The parameters formatted as an internal link.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsItalic()
abstract string WikiPageCreator.Export.Format.Formatter.AsItalic (string text) pure virtual
Formats the given text as italic text.
Parameters
text The text to be formatted.
Returns
The text formatted as italic.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsSubscript()
abstract string WikiPageCreator.Export.Format.Formatter.AsSubscript (string text) pure virtual
Formats the given text as subscript text.
Parameters
text The text to be formatted.
Returns
The text formatted as subscript.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsSuperscript()
abstract string WikiPageCreator.Export.Format.Formatter.AsSuperscript (string text) pure virtual
Formats the given text as superscript text.
Parameters
text The text to be formatted.
Returns
The text formatted as superscript.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
AsTableRow()
abstract string WikiPageCreator.Export.Format.Formatter.AsTableRow (string[] data) pure virtual
Formats the given data as a table row.
Parameters
data The data for the table row.
Returns
The data formatted as a table row.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateAwardChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCastPersonItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateCompanyItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateDistributorCompanyItemSection(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateFilmingAndProductionChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxAspectRatio(), WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator.CreateInfoBoxBudget(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxBudget(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCamera(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCertification(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCinematographicProcess(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxColor(), WikiPageCreator.Export.Create.EntryContentCreator.CreateInfoBoxContentHelper(), WikiPageCreator.Export.Create.TypeContentCreator.CreateInfoBoxContentInternal(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCountry(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxFilmLength(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxGenre(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxLaboratory(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxLanguage(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxLogo(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxNegativeFormat(), WikiPageCreator.Export.Create.SeriesContentCreator.CreateInfoBoxNoOfEpisodes(), WikiPageCreator.Export.Create.SeriesContentCreator.CreateInfoBoxNoOfSeasons(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxOriginalReleaseDate(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxPrintedFilmFormat(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxReleaseDate(), WikiPageCreator.Export.Create.SeriesContentCreator.CreateInfoBoxReleaseDateFirstEpisode(), WikiPageCreator.Export.Create.SeriesContentCreator.CreateInfoBoxReleaseDateLastEpisode(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxRuntime(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxSoundMix(), WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxTitle(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxTitle(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxType(), WikiPageCreator.Export.Create.MovieAndTVArticleContentCreator.CreateInfoBoxWorldwideGross(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxWorldwideGross(), and WikiPageCreator.Export.Create.MovieFileContentCreator.CreatePersonItemSection().
AsUnderlined()
abstract string WikiPageCreator.Export.Format.Formatter.AsUnderlined (string text) pure virtual
Formats the given text as underlinded text.
Parameters
text The text to be formatted.
Returns
The text formatted as underlined.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
BeginBox()
abstract string WikiPageCreator.Export.Format.Formatter.BeginBox (int size, Alignment align) pure virtual
Inserts an indicator to begin a box with the given size and alignment.
Parameters
size The width of the box.
align The alignment of the box.
Returns
Indicator to begin a box.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
Referenced by WikiPageCreator.Export.Create.EntryContentCreator.CreateInfoBoxBegin(), and WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxHeader().
BeginComment()
abstract string WikiPageCreator.Export.Format.Formatter.BeginComment () pure virtual
Inserts an indicator to begin a (multiline) comment.
Returns
Indicator to begin a comment.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateHeader(), and WikiPageCreator.Export.Create.ArticleContentCreator.CreatePageHeader().
BeginDataEntry()
abstract string WikiPageCreator.Export.Format.Formatter.BeginDataEntry (string name) pure virtual
Inserts an indicator to begin a data entry.
Parameters
name The name of the data entry.
Returns
Indicator to begin a data entry.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
CellSpanVertically()
abstract string WikiPageCreator.Export.Format.Formatter.CellSpanVertically () pure virtual
Inserts an indicator to span cells vertically.
Returns
Indicator to span cells vertically.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateAwardChapter(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxAspectRatio(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCamera(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCertification(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCinematographicProcess(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxColor(), WikiPageCreator.Export.Create.GenreContentCreator.CreateInfoBoxContentInternal(), WikiPageCreator.Export.Create.LanguageContentCreator.CreateInfoBoxContentInternal(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxCountry(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxFilmLength(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxGenre(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxLaboratory(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxLanguage(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxNegativeFormat(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxPrintedFilmFormat(), WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxRuntime(), and WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxSoundMix().
DefineTable()
abstract string WikiPageCreator.Export.Format.Formatter.DefineTable (int size, int[] width) pure virtual
Inserts an indicator to define a table with the given size and column widths.
Parameters
size The size of the table
width The width(s) of the columns.
Returns
Indicator to define the table.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
Referenced by WikiPageCreator.Export.Create.EntryContentCreator.CreateInfoBoxBegin(), and WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxHeader().
DisableCache()
abstract string WikiPageCreator.Export.Format.Formatter.DisableCache () pure virtual
Inserts an indicator to disable the cache.
Returns
Indicator to disable the cache.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateHeader(), and WikiPageCreator.Export.Create.ArticleContentCreator.CreatePageHeader().
DisableTOC()
abstract string WikiPageCreator.Export.Format.Formatter.DisableTOC () pure virtual
Inserts an indicator to disable the TOC (table of contents).
Returns
Indicator to disable the TOC.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateHeader(), and WikiPageCreator.Export.Create.ArticleContentCreator.CreatePageHeader().
EndBox()
abstract string WikiPageCreator.Export.Format.Formatter.EndBox () pure virtual
Inserts an indicator to end a box.
Returns
Indicator to end a box.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
Referenced by WikiPageCreator.Export.Create.EntryContentCreator.CreateInfoBoxEnd(), and WikiPageCreator.Export.Create.MovieFileContentCreator.CreateInfoBoxEnd().
EndComment()
abstract string WikiPageCreator.Export.Format.Formatter.EndComment () pure virtual
Inserts an indicator to end a (multiline) comment.
Returns
Indicator to end a comment.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
Referenced by WikiPageCreator.Export.Create.MovieFileContentCreator.CreateHeader(), and WikiPageCreator.Export.Create.ArticleContentCreator.CreatePageHeader().
EndDataEntry()
abstract string WikiPageCreator.Export.Format.Formatter.EndDataEntry () pure virtual
Inserts an indicator to end a data entry.
Returns
Indicator to end a data entry.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
ForceNewLine()
abstract string WikiPageCreator.Export.Format.Formatter.ForceNewLine () pure virtual
Inserts an indicator to force a new line.
Returns
Indicator to force a new line.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
ListItemIndent()
abstract string WikiPageCreator.Export.Format.Formatter.ListItemIndent () pure virtual
Inserts an indicator for an indentation.
Returns
Indicator for an indentation.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
ListItemSorted()
abstract string WikiPageCreator.Export.Format.Formatter.ListItemSorted () pure virtual
Inserts an indicator for a list item for a sorted list.
Returns
Indicator for a list item for a sorted list.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
ListItemUnsorted()
abstract string WikiPageCreator.Export.Format.Formatter.ListItemUnsorted () pure virtual
Inserts an indicator for a list item for an unsorted list.
Returns
Indicator for a list item for an unsorted list.
Implemented in WikiPageCreator.Export.Format.DokuWikiFormatter.
Member Data Documentation
Logger
readonly NLog.Logger WikiPageCreator.Export.Format.Formatter.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by WikiPageCreator.Export.Format.Formatter.Formatter().
The documentation for this class was generated from the following file:
EntertainmentInfothek/src/WikiPageCreator/Export/Format/Formatter.cs