EntertainmentInfothek: EntertainmentDB.Data.CompanyItem Class Reference
EntertainmentDB.Data.CompanyItem Class Reference
Provides a company item.
Public Member Functions
CompanyItem (DBReader reader)
Initializes a company item with an empty id string.
CompanyItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes a company item with the given id string.
Public Member Functions inherited from EntertainmentDB.Data.Entry
virtual int Retrieve (bool retrieveBasicInfoOnly)
Retrieves the information of the entry from the database.
int Retrieve (bool retrieveBasicInfoOnly)
Retrieves the information from the database.
Static Public Member Functions
static List< CompanyItem > RetrieveList (DBReader reader, string baseTableName, string baseTableID, string targetTableName, string order="ID")
Retrieves a list of company items from the database.
Protected Member Functions
override int RetrieveBasicInformation (bool retrieveBasicInfoOnly)
Retrieves the basic information of the company item from the database.
Protected Member Functions inherited from EntertainmentDB.Data.EntryItem
EntryItem (DBReader reader)
Initializes an entry item with an emtpy id string.
EntryItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes an entry item with the given id string.
Protected Member Functions inherited from EntertainmentDB.Data.Entry
Entry (DBReader reader)
Initializes an entry with the given reader and id string.
Entry (DBReader reader, string id)
Initializes an entry with the given reader and id string.
abstract int RetrieveBasicInformation (bool retrieveBasicInfoOnly)
Retrieves the basic information of the entry from the database.
virtual int RetrieveAdditionalInformation ()
Retrieves the additional information of the entry from the database.
Properties
Company Company [get, set]
The company of the company item.
string Role [get, set]
The role of the company item.
Properties inherited from EntertainmentDB.Data.EntryItem
string BaseTableName [get, set]
The base table name of the entry item.
string TargetTableName [get, set]
The target table name of the entry item.
Properties inherited from EntertainmentDB.Data.Entry
DBReader Reader [get, protected set]
The database reader to be used to read the entry information from the database.
string ID [get, set]
The id of the entry.
string Details [get, set]
The details of the entry.
Status Status [get, set]
The status of the entry.
string LastUpdated [get, set]
The date of last update of the entry.
Static Private Attributes
static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides a company item.
Constructor & Destructor Documentation
CompanyItem() [1/2]
EntertainmentDB.Data.CompanyItem.CompanyItem (DBReader reader)
Initializes a company item with an empty id string.
Parameters
reader The database reader to be used to read the company item information from the database.
CompanyItem() [2/2]
EntertainmentDB.Data.CompanyItem.CompanyItem (DBReader reader, string id, string baseTableName, string targetTableName)
Initializes a company item with the given id string.
Parameters
reader The database reader to be used to read the company item information from the database.
id The id of the company item.
baseTableName The base table name of the company item.
targetTableName The target table name of the company item.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Member Function Documentation
RetrieveBasicInformation()
override int EntertainmentDB.Data.CompanyItem.RetrieveBasicInformation (bool retrieveBasicInfoOnly) protected virtual
Retrieves the basic information of the company item from the database.
Parameters
retrieveBasicInfoOnly true if only the basic info is to be retrieved; false if also additional data is to be retrieved.
Returns
1 if data record was retrieved; 0 if no data record matched the id.
Implements EntertainmentDB.Data.Entry.
Reimplemented in EntertainmentDB.Data.DistributorCompanyItem.
RetrieveList()
static List< CompanyItem > EntertainmentDB.Data.CompanyItem.RetrieveList (DBReader reader, string baseTableName, string baseTableID, string targetTableName, string order = "ID") static
Retrieves a list of company items from the database.
Parameters
reader The reader to be used to retrieve the data records.
baseTableName The base table name of the company item.
baseTableID The base table id of the company item.
targetTableName The target table name of the company item.
order The order in which the data records are to be sorted.
Returns
The list of company items.
Exceptions
ArgumentNullException Thrown when any of the given parameters is null.
Referenced by EntertainmentDB.Data.Image.RetrieveAdditionalInformation(), EntertainmentDB.Data.Movie.RetrieveAdditionalInformation(), and EntertainmentDB.Data.Text.RetrieveAdditionalInformation().
Member Data Documentation
Logger
readonly NLog.Logger EntertainmentDB.Data.CompanyItem.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by EntertainmentDB.Data.CompanyItem.CompanyItem(), EntertainmentDB.Data.CompanyItem.RetrieveBasicInformation(), and EntertainmentDB.Data.CompanyItem.RetrieveList().
Property Documentation
Company
Company EntertainmentDB.Data.CompanyItem.Company get set
The company of the company item.
Referenced by EntertainmentDB.Data.CompanyItem.RetrieveBasicInformation(), and EntertainmentDB.Data.DistributorCompanyItem.RetrieveBasicInformation().
Role
string EntertainmentDB.Data.CompanyItem.Role get set
The role of the company item.
Referenced by EntertainmentDB.Data.CompanyItem.RetrieveBasicInformation(), and EntertainmentDB.Data.DistributorCompanyItem.RetrieveBasicInformation().
The documentation for this class was generated from the following file:
EntertainmentInfothek/src/EntertainmentDB/Data/CompanyItem.cs