EntertainmentInfothek: WikiPageCreator.Export.Create.CertificationContentCreator Class Reference
WikiPageCreator.Export.Create.CertificationContentCreator Class Reference
Provides a content creator for a certification.
Public Member Functions
CertificationContentCreator (List< CertificationItem > certifications, Formatter formatter, string targetLanguageCode)
override List< string > CreateInfoBoxContent ()
Creates the infobox content of a given certification.
Public Member Functions inherited from WikiPageCreator.Export.Create.EntryContentCreator
virtual string GetPageName ()
Returns the page name of the entrys page.
virtual List< string > CreatePageContent ()
Creates the page content of the entry.
virtual List< string > CreateInfoBoxContent ()
Creates the infobox content of a given entry.
virtual List< string > CreateChapterContent ()
Creates the chapter content of a given entry.
virtual List< string > CreateSectionContent ()
Creates the section content of a given entry.
Protected Member Functions
override List< string > CreateInfoBoxContentInternal ()
Creates the infobox content of a given list of certifications.
Protected Member Functions inherited from WikiPageCreator.Export.Create.EntryContentCreator
EntryContentCreator (Entry entry, Formatter formatter, string targetLanguageCode)
Initializes an EntryContentCreator with the given entry, formatter and target language code.
virtual List< string > CreatePageContentInternal ()
Creates the page content of the entry.
virtual List< string > CreatePageHeader ()
Creates the formatted header content of a given entry.
virtual List< string > CreatePageTitle ()
Creates the formatted file title content of a given entry.
virtual List< string > CreateInfoBoxBegin ()
Creates the formatted infobox begin content of a given entry
virtual List< string > CreateInfoBoxContentInternal ()
Creates the infobox content of a given entry.
void CreateInfoBoxContentHelper (List< string > content, string title, string[] path, string pagename, string text, string additionalInfo)
Creates the specific row of the infobox content.
void CreateInfoBoxContentHelper (List< string > content, string title, string[] path, string pagename, Image image, int size, string additionalInfo)
virtual List< string > CreateInfoBoxEnd ()
Creates the formatted infobox end content of a given entry
virtual List< string > CreateNewChapter (Dictionary< string, string > title)
Creates a formatted chapter heading with the given title.
virtual List< string > CreateChapterContentInternal ()
Creates the chapter content of a given entry.
virtual List< string > CreateNewSection (Dictionary< string, string > title)
Creates a formatted section heading with the given title.
virtual List< string > CreateSectionContentInternal ()
Creates the section content of a given entry.
virtual List< string > CreatePageFooter ()
Creates the formatted footer content of a given entry.
Properties
List< CertificationItem > Certifications [get, set]
The list of certification items to be used to create the content.
Properties inherited from WikiPageCreator.Export.Create.EntryContentCreator
Formatter Formatter [get, protected set]
The formatter to be used to format the information of the entry.
Entry Entry [get, protected set]
The entry to be used to create the content.
string TargetLanguageCode [get, protected set]
The target language (as a language code) to specify the language of the created content.
Static Private Attributes
static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides a content creator for a certification.
Constructor & Destructor Documentation
CertificationContentCreator()
WikiPageCreator.Export.Create.CertificationContentCreator.CertificationContentCreator (List< CertificationItem > certifications, Formatter formatter, string targetLanguageCode)
Member Function Documentation
CreateInfoBoxContent()
override List< string > WikiPageCreator.Export.Create.CertificationContentCreator.CreateInfoBoxContent () virtual
Creates the infobox content of a given certification.
Returns
The formatted content of the certification.
Reimplemented from WikiPageCreator.Export.Create.EntryContentCreator.
Referenced by WikiPageCreator.Export.Create.ArticleContentCreator.CreateInfoBoxCertification().
CreateInfoBoxContentInternal()
override List< string > WikiPageCreator.Export.Create.CertificationContentCreator.CreateInfoBoxContentInternal () protected virtual
Creates the infobox content of a given list of certifications.
Returns
The formatted content of the list of certifications.
Reimplemented from WikiPageCreator.Export.Create.EntryContentCreator.
Referenced by WikiPageCreator.Export.Create.CertificationContentCreator.CreateInfoBoxContent().
Member Data Documentation
Logger
readonly NLog.Logger WikiPageCreator.Export.Create.CertificationContentCreator.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by WikiPageCreator.Export.Create.CertificationContentCreator.CertificationContentCreator(), and WikiPageCreator.Export.Create.CertificationContentCreator.CreateInfoBoxContentInternal().
Property Documentation
Certifications
List<CertificationItem> WikiPageCreator.Export.Create.CertificationContentCreator.Certifications get set
The list of certification items to be used to create the content.
Referenced by WikiPageCreator.Export.Create.CertificationContentCreator.CertificationContentCreator(), and WikiPageCreator.Export.Create.CertificationContentCreator.CreateInfoBoxContentInternal().
The documentation for this class was generated from the following file:
EntertainmentInfothek/src/WikiPageCreator/Export/Create/CertificationContentCreator.cs