EntertainmentInfothek: WikiPageCreator.Export.Create.MovieContentCreator Class Reference
WikiPageCreator.Export.Create.MovieContentCreator Class Reference
Provides a content creator for a movie.
Public Member Functions
MovieContentCreator ()
Initializes a new MovieContentCreator.
Public Member Functions inherited from WikiPageCreator.Export.Create.ArticleContentCreator
virtual string GetFileName (Entry entry, Formatter formatter)
Creates the file name of the article page (or not).
virtual string GetFileName (Article article, Formatter formatter)
Creates the file name of the article page.
virtual List< string > CreateFileContent (Entry entry, string targetLanguageCode, Formatter formatter)
Creates the file content of a given entry.
Protected Member Functions
override List< string > CreateInfoBoxContent (Entry entry, string targetLanguageCode, Formatter formatter)
Creates the infobox content of a given entry.
override List< string > CreateChapterContent (Entry entry, string targetLanguageCode, Formatter formatter)
Creates the chapter content of a given entry.
virtual List< string > CreateInfoBoxLogo (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox logo content of a given movie.
virtual List< string > CreateInfoBoxGenre (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox genre content of a given movie.
virtual List< string > CreateInfoBoxCertification (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox certification content of a given movie.
virtual List< string > CreateInfoBoxCountry (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox country content of a given movie.
virtual List< string > CreateInfoBoxLanguage (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox language content of a given movie.
virtual List< string > CreateInfoBoxBudget (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox budget content of a given movie.
virtual List< string > CreateInfoBoxWorldwideGross (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox worldwide gross content of a given movie.
virtual List< string > CreateInfoBoxRuntime (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox runtime content of a given movie.
virtual List< string > CreateInfoBoxSoundMix (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox soundmix content of a given movie.
virtual List< string > CreateInfoBoxColor (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox color content of a given movie.
virtual List< string > CreateInfoBoxAspectRatio (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox aspect ratio content of a given movie.
virtual List< string > CreateInfoBoxCamera (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox camera content of a given movie.
virtual List< string > CreateInfoBoxLaboratory (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox laboratory content of a given movie.
virtual List< string > CreateInfoBoxFilmLength (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox film length content of a given movie.
virtual List< string > CreateInfoBoxNegativeFormat (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox negative format content of a given movie.
virtual List< string > CreateInfoBoxCinematographicProcess (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox cinematographic process content of a given movie.
virtual List< string > CreateInfoBoxPrintedFilmFormat (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox printed film format content of a given movie.
virtual List< string > CreateChapterPoster (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted poster chapter content of a given movie.
virtual List< string > CreateChapterCover (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted cover chapter content of a given movie.
virtual List< string > CreateChapterDescription (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted description chapter content of a given movie.
virtual List< string > CreateChapterReview (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted review chapter content of a given movie.
virtual List< string > CreateChapterImage (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted image chapter content of a given movie.
virtual List< string > CreateChapterCastAndCrew (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted cast and crew chapter content of a given movie.
virtual List< string > CreateChapterCompany (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted company chapter content of a given movie.
virtual List< string > CreateChapterFilmingAndProduction (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted filming and production chapter content of a given movie.
virtual List< string > CreateChapterAward (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted award chapter content of a given movie.
virtual List< string > CreateChapterWeblink (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted weblink chapter content of a given movie.
virtual List< string > CreateChapterConnection (Movie movie, string targetLanguageCode, Formatter formatter)
Creates the formatted weblink chapter content of a given movie.
Protected Member Functions inherited from WikiPageCreator.Export.Create.ArticleContentCreator
ArticleContentCreator ()
Initializes a new ArticleContentCreator.
virtual List< string > CreateFileHeader (Article article, string targetLanguageCode, Formatter formatter)
Creates the formatted header content of a given article.
virtual List< string > CreateFileFooter (Article article, string targetLanguageCode, Formatter formatter)
Creates the formatted footer content of a given article.
virtual List< string > CreateInfoBoxBegin (Article article, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox begin content of a given article.
virtual List< string > CreateInfoBoxEnd (Article article, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox end content of a given article
virtual List< string > CreateNewChapter (Dictionary< string, string > title, string targetLanguageCode, Formatter formatter)
Creates a formatted chapter heading with the given title.
virtual List< string > CreateNewSection (Dictionary< string, string > title, string targetLanguageCode, Formatter formatter)
Creates a formatted section heading with the given title.
virtual List< string > CreateFileTitle (Article article, string targetLanguageCode, Formatter formatter)
Creates the formatted file title content of a given article.
virtual List< string > CreateInfoBoxTitle (Article article, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox title content of a given article.
virtual List< string > CreateInfoBoxReleaseDate (Article article, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox release date content of a given article.
virtual List< string > CreateInfoboxType (Article article, string targetLanguageCode, Formatter formatter)
Creates the formatted infobox type content of a given article.
virtual List< string > CreateChapterConnection (Article article, string targetLanguageCode, Formatter formatter)
Creates the formatted connection chapter content of a given article.
Static Private Attributes
static NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger()
The logger to log everything.
Detailed Description
Provides a content creator for a movie.
Constructor & Destructor Documentation
MovieContentCreator()
WikiPageCreator.Export.Create.MovieContentCreator.MovieContentCreator ()
Initializes a new MovieContentCreator.
Member Function Documentation
CreateChapterAward()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterAward (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted award chapter content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted award chapter content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterContent().
CreateChapterCastAndCrew()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterCastAndCrew (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted cast and crew chapter content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted cast and crew chapter content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterContent().
CreateChapterCompany()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterCompany (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted company chapter content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted company chapter content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterContent().
CreateChapterConnection()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterConnection (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted weblink chapter content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted weblink chapter content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterContent().
CreateChapterContent()
override List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterContent (Entry entry, string targetLanguageCode, Formatter formatter) protected virtual
Creates the chapter content of a given entry.
Parameters
entry The entry that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted content of the entry.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Implements WikiPageCreator.Export.Create.ArticleContentCreator.
CreateChapterCover()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterCover (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted cover chapter content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted cover chapter content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterContent().
CreateChapterDescription()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterDescription (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted description chapter content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted description chapter content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterContent().
CreateChapterFilmingAndProduction()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterFilmingAndProduction (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted filming and production chapter content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted filming and production chapter content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterContent().
CreateChapterImage()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterImage (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted image chapter content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted image chapter content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterContent().
CreateChapterPoster()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterPoster (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted poster chapter content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted poster chapter content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterContent().
CreateChapterReview()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterReview (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted review chapter content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted review chapter content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterContent().
CreateChapterWeblink()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterWeblink (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted weblink chapter content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted weblink chapter content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterContent().
CreateInfoBoxAspectRatio()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxAspectRatio (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox aspect ratio content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox aspect ratio content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent().
CreateInfoBoxBudget()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxBudget (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox budget content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox budget content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent().
CreateInfoBoxCamera()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxCamera (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox camera content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox camera content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent().
CreateInfoBoxCertification()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxCertification (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox certification content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox certification content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent().
CreateInfoBoxCinematographicProcess()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxCinematographicProcess (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox cinematographic process content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox cinematographic process content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent().
CreateInfoBoxColor()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxColor (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox color content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox color content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent().
CreateInfoBoxContent()
override List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent (Entry entry, string targetLanguageCode, Formatter formatter) protected virtual
Creates the infobox content of a given entry.
Parameters
entry The entry that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted content of the entry.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Reimplemented from WikiPageCreator.Export.Create.ArticleContentCreator.
CreateInfoBoxCountry()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxCountry (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox country content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox country content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent().
CreateInfoBoxFilmLength()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxFilmLength (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox film length content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox film length content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent().
CreateInfoBoxGenre()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxGenre (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox genre content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox genre content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent().
CreateInfoBoxLaboratory()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxLaboratory (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox laboratory content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox laboratory content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent().
CreateInfoBoxLanguage()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxLanguage (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox language content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox language content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent().
CreateInfoBoxLogo()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxLogo (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox logo content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox logo content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent().
CreateInfoBoxNegativeFormat()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxNegativeFormat (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox negative format content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox negative format content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent().
CreateInfoBoxPrintedFilmFormat()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxPrintedFilmFormat (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox printed film format content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox printed film format content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent().
CreateInfoBoxRuntime()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxRuntime (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox runtime content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox runtime content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent().
CreateInfoBoxSoundMix()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxSoundMix (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox soundmix content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox soundmix content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent().
CreateInfoBoxWorldwideGross()
virtual List< string > WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxWorldwideGross (Movie movie, string targetLanguageCode, Formatter formatter) protected virtual
Creates the formatted infobox worldwide gross content of a given movie.
Parameters
movie The movie that is to be used to create the content.
targetLanguageCode The language code of the target language.
formatter The formatter to be used to format the content.
Returns
The formatted infobox worldwide gross content of the movie.
Exceptions
ArgumentNullException Thrown when one the given parameters is null.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent().
Member Data Documentation
Logger
NLog.Logger WikiPageCreator.Export.Create.MovieContentCreator.Logger = NLog.LogManager.GetCurrentClassLogger() static private
The logger to log everything.
Referenced by WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterAward(), WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterCastAndCrew(), WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterCompany(), WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterConnection(), WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterContent(), WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterCover(), WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterDescription(), WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterFilmingAndProduction(), WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterImage(), WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterPoster(), WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterReview(), WikiPageCreator.Export.Create.MovieContentCreator.CreateChapterWeblink(), WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxAspectRatio(), WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxBudget(), WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxCamera(), WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxCertification(), WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxCinematographicProcess(), WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxColor(), WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxContent(), WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxCountry(), WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxFilmLength(), WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxGenre(), WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxLaboratory(), WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxLanguage(), WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxLogo(), WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxNegativeFormat(), WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxPrintedFilmFormat(), WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxRuntime(), WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxSoundMix(), WikiPageCreator.Export.Create.MovieContentCreator.CreateInfoBoxWorldwideGross(), and WikiPageCreator.Export.Create.MovieContentCreator.MovieContentCreator().
The documentation for this class was generated from the following file:
C:/Users/Sandra/Projekte/GitHub/EntertainmentInfothek_public/src/WikiPageCreator/Export/Create/MovieContentCreator.cs